konveyor/tackle-ui-tests

cypress/integration/tests/controls/stakeholders/filter.test.ts
- Test cases were failed because of expected  element not present on that page because items per page are 10 only.
=> RFR: Fixed stakeholder filter test cases

cypress/integration/models/businessservices.ts, cypress/integration/models/jobfunctions.ts, cypress/integration/models/stakeholdergroups.ts
Due to new changes in UI, every row element has been wrapped in a span, this was causing the tests to nest deeper and not able to search their parent tr tag.
Updated below delete and edit functions for -
- Stakeholder groups
- Job functions
- Business Services
NOTE : Stakeholder does not require change as the email field in UI is unaltered and it is working fine.
=> [RFR] Fixed the edit and delete to accomodate new changes in the UI

cypress/integration/tests/controls/stakeholdergroups/sort.test.ts, cypress/integration/types/constants.ts
1. Automate stakeholder groups table sort test case
- Sort by name
- Sort by member(s)
=> RFR: Automate sort stakeholder groups

cypress/integration/tests/controls/stakeholdergroups/crud.test.ts
Fixed Error:
```
Timed out retrying after 4000ms: Expected to find element: tr, but never found it. Queried from element: <span.pf-m-truncate.pf-c-table__text>
cypress/integration/tests/controls/stakeholdergroups/crud.test.tsat line71
69 |         cy.get(tdTag)
70 |             .contains(stakeholdergroup.name)
> 71 |             .parent(trTag)
|              ^
72 |             .within(() => {
73 |                 click(expandRow);
74 |
```
=> RFR: Fixed stakeholder group CRUD test case

cypress/integration/tests/applicationinventory/application/create.test.ts, cypress/integration/tests/controls/stakeholdergroups/filter.test.ts, cypress/integration/tests/controls/stakeholdergroups/interlinked.test.ts, cypress/utils/utils.ts
- Fix for stakeholder groups interlinked test cases
- Fix for stakeholder groups filter test cases
- Unskipp application unique name constraint test case as issue [179](https://issues.redhat.com/browse/TACKLE-179) fixed.
=> RFR: Fix stakeholder group test cases

cypress/utils/utils.ts
After our discussion on the bug - https://issues.redhat.com/browse/TACKLE-231, I agree to the fact that, whatever be the order, it must be consistent as per any one approach, be it database or javascript. Having gone through the comment from Carlos, I understand that, changing database collation and locale, is not best of solution.
Hence, to keep up with the order Tackle UI is producing, I have modified our test sorting function to be consistent with the result produced by Tackle UI sort.
The other issue, was regarding treatment of empty values, for that, I have just ignored them while doing a sort.
Hope, this solution is satisfactory for all of us. And yeah, it works, having tested it on my local env.
Thanks @carlosthe19916 , I have taken your suggestion for sorting of numeric values …
=> [RFR] : Sort function modification to be able to work with postgresql sorting

.github/workflows/prettier.yaml, .github/workflows/pull-requests.yaml, README.md
- In some cases, reviewer wants to trigger the PR run action but he/she cant force the branch.Hence added feature of trigering github action manually
- After merging this PR. Steps to trigger gh action for PR testing manually - Go to Actions tab > Click on GH action(Pull request test) > Click on run workflow dropdown and select PR branch > Click on button Run workflow
=> RFR: Add manual trigger pull requests

.github/workflows/pull-requests.yaml, reportconfig.json
- We don't upload videos to report portal.
- Cypress takes video for every test execution which takes too much time to finish on test execution. Hence keeping video off.
- As per current scenario, it will upload screenshot for filed test case
- For PR tester :- We dont need video recording. Hence keeping off.
=> RFR: Keep video off after test execution

cypress/integration/tests/applicationinventory/application/import.test.ts
The test `import.test.ts` => `Applications import having same name with spaces` is importing the following CSV:
```
Record Type 1,Application Name,Description,Comments,Business Service,Tag Type 1,Tag 1,Tag Type 2,Tag 2,Tag Type 3,Tag 3,Tag Type 4,Tag 4,Tag Type 5,Tag 5,Tag Type 6,Tag 6,Tag Type 7,Tag 7,Tag Type 8,Tag 8,Tag Type 9,Tag 9,Tag Type 10,Tag 10,Tag Type 11,Tag 11,Tag Type 12,Tag 12,Tag Type 13,Tag 13,Tag Type 14,Tag 14,Tag Type 15,Tag 15,Tag Type 16,Tag 16,Tag Type 17,Tag 17,Tag Type 18,Tag 18,Tag Type 19,Tag 19,Tag Type 20,Tag 20
,Import-app-7,App created using import feature,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
, Import-app-7 ,Same app created using import feature having trailing and leading whitespace,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
```
The CSV above is …
=> [TACKLE-274]-Fix duplicate assertions in test

cypress/utils/utils.ts
Changed logic for preserving all the cookies that contain keyword "SESSION"
As previous logic was relying on fixed number of cookies (3). However, on testing it was found that, cookies vary in number.
=> [RFR] Preserve cookies which contain "Session" keyword

README.md, cypress/integration/tests/controls/stakeholders/create.test.ts, cypress/integration/tests/controls/stakeholders/crud.test.ts, cypress/integration/tests/controls/stakeholders/filter.test.ts, cypress/integration/tests/controls/stakeholders/interlinked.test.ts, cypress/integration/tests/controls/stakeholders/pagination.test.ts, cypress/integration/tests/controls/stakeholders/sort.test.ts, cypress/plugins/index.js, cypress/support/index.js, cypress/utils/utils.ts, package-lock.json, package.json
Test tagging feature to differentiate tests based on different tiers of execution.
Implemented using cypress-grep library which allows to specify either tags or string pattern to run specific test from command line env variables.
Currently tests have been labelled under 3 tiers - 
- tier1 -> CRUD and interlinked tests
- tier2 -> field validations, filter and sort tests
- tier3 -> pagination tests
Example - The below command runs tests tagged with "tier1" only
_`npx cypress run --env grepTags=@tier1 --spec "cypress/integration/tests/controls/stakeholders/*" --browser chrome --config video=false`_
Please see below screenshots for tier wise execution of stakeholders tests - 
**_tier1 run -_**
**_tier2 run -_**
**_tier3 run -_**
=> [RFR] Stakeholders test tagging feature

README.md
Added steps to run tests locally, against Tackle UI instance deployed on local machine using minikube
=> [RFR] Added steps to run tests locally using minikube instance

cypress/integration/models/tags.ts, cypress/utils/utils.ts
Created function selectWithinModal to search for tag type dropdown within modal window only to avoid locating 2 DOM objects with the same captions
Fixed tag creation method, now it is using new function and doesn't fail
=> RFR - Function selectWithinModal  added and tag creation fixed

cypress/integration/tests/developer/controls/stakeholders/filter.test.ts, cypress/integration/tests/developer/controls/stakeholders/pagination.test.ts
Removes duplicated calls to `selectUserPerspective` and changes the "Developer" literal to the defined constant.
=> [RFR] Fix minor test errors

cypress/integration/models/administrator/proxy/proxy.ts, cypress/integration/tests/administrator/proxy/proxy.enable.disable.test.ts, cypress/integration/views/proxy.view.ts
Implemented tests to ensure that a port field cannot contain strings.
Added tests for enabling and disabling HTTP proxy with valid configuration.
=> [RFR] Implement proxy port validation

cypress/integration/models/administrator/credentials/credentials.ts, cypress/integration/models/administrator/credentials/credentialsSourceControlKey.ts, cypress/integration/models/administrator/proxy/proxy.ts, cypress/integration/tests/administrator/credentials/maven_crud.test.ts, cypress/integration/tests/administrator/credentials/pagination.test.ts, cypress/integration/tests/administrator/credentials/proxy_crud.test.ts, cypress/integration/tests/administrator/credentials/sourcecontrol_crud.test.ts, cypress/integration/tests/administrator/proxy/proxy.enable.disable.test.ts, cypress/integration/views/common.view.ts, cypress/integration/views/proxy.view.ts
1. Fix credentials tests for upstream by modifying the notification selector, now it's dynamic.
2. Make sure the 'after' method also checks for skipped tests to avoid failures in files where all tests are skipped but the  'after' method runs.
=> [RFR] fix credential tests for upstream

.github/install_tackle2_crd.yml
Just added `feature_auth_required: true,` into `install_tackle2_crd.yml` to enable deployment of keycloak which is disabled by default.
=> [RFR] Enabled keycloak in minikube

cypress/integration/models/migration/applicationinventory/analysis.ts
Fixed problem for binary analysis test and upload binary analysis test, the problem was that after downloading report, `openReport` method was clicking on analysis again.
In result right side menu was closed and report couldn't be opened. The fix is that each time after downloading report analysis is clicked again and right side menu is closing.
=> [RFR] Fixed binary analysis test 

cypress/e2e/tests/migration/applicationinventory/manageimports/sort.test.ts
The `getNameListOnPage` method from Business Services was failing randomly due to known issues with async methods.
But there is no real need to check for the existence of a business service because, in the previous line, all business services are deleted.
Test passed in jenkins run [#260](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/260/console)
=> [RFR] Fix manageimports sort test

cypress/e2e/models/administration/credentials/credentials.ts
When two credentials are created, in some cases two notifications can be displayed at the same time, causing the close function to fail.
=> [RFR] Fix double notification issue

cypress/e2e/models/migration/applicationinventory/assessment.ts, cypress/e2e/views/assessment.view.ts, cypress/e2e/views/review.view.ts
modified:   cypress/e2e/models/migration/applicationinventory/assessment.ts
modified:   cypress/e2e/views/assessment.view.ts
modified:   cypress/e2e/views/review.view.ts
=> [RFR] Selectors changed for assessment's tests

cypress/utils/utils.ts
Occasionally, applications wouldn't get deleted when  deleteApplicationTableRows() was called in the before() hook. After some investigation , I found that's because the app table was not getting populated . I added a wait call for the app table to be populated and the problem went away.
=> [RFR] Wait for application table to be populated before bulk deletion

cypress/e2e/models/migration/applicationinventory/analysis.ts
Fixed failing upload binary analysis with custom rules, now it will check if score field contains any number at all instead of waiting for particular number. Anyway this value is still there as it is field of the class and it can be used for comparing with windup values, etc.
=> [RFR] Fixed RBAC custom rules failures

cypress/e2e/tests/migration/applicationinventory/assessment/sort.test.ts, cypress/e2e/tests/migration/controls/businessservices/sort.test.ts, cypress/e2e/tests/migration/controls/stakeholders/filter.test.ts, cypress/e2e/tests/migration/controls/stakeholders/sort.test.ts, cypress/e2e/types/constants.ts, cypress/e2e/views/businessservices.view.ts, cypress/e2e/views/common.view.ts, cypress/e2e/views/stakeholders.view.ts, cypress/utils/utils.ts
1) SortAsc and sortDesc methods to be replaced by clickonSortButton() method
2) Sort by group count not relevant anymore in stakeholder - removed test .
3) Clean up unused imports and presevecookies methods.
=> [RFR] Fix sort methods and controls jenkins failures

cypress/e2e/models/migration/applicationinventory/analysis.ts, cypress/support/e2e.js, cypress/utils/utils.ts
One of the main problems that caused the browser to crash when running multiple tests was the large number of log lines generated by each operation we were performing.
Each log line represented a different element in the DOM, and it was leading to an increase in the browser's memory consumption until it eventually crashed
To address this issue, I changed some of the common functions in order to minimize the number of logs they generate, while still providing enough information for debugging failures with just a screenshot.
I implemented this as a default parameter, allowing us to quickly enable all the logs for local debugging when needed.
Additionally, I created a small function to hide all XHR request logs that were being generated.
Finally, I reduced the timeout of certain functions …
=> [RFR] Reduce memory consumption

cypress/e2e/models/administration/credentials/JiraCredentials.ts, cypress/e2e/tests/administration/credentials/field_validation.test.ts, cypress/e2e/tests/administration/credentials/filter.test.ts, cypress/e2e/tests/administration/credentials/jira_crud.test.ts, cypress/e2e/tests/administration/credentials/maven_crud.test.ts, cypress/e2e/tests/administration/credentials/pagination.test.ts, cypress/e2e/tests/administration/credentials/proxy_crud.test.ts, cypress/e2e/tests/administration/credentials/remove_creds_app.test.ts, cypress/e2e/tests/administration/credentials/sourcecontrol_crud.test.ts, cypress/e2e/views/credentials.view.ts, cypress/utils/utils.ts
Cleaned up credential tests from unsued leftovers
Refactored Jira credentials creation to simplify it 
Added Jira credentials creation in createMultipleCredentials() 
Made sure that all created crdentials are removed after test is done
=> [RFR] Cleaned up credential tests from unsued leftovers

cypress/e2e/models/migration/migration-waves/migration-wave.ts, cypress/e2e/tests/migration/migration-waves/export.test.ts, cypress/e2e/tests/migration/migration-waves/export_to_jira_cloud.test.ts, cypress/e2e/types/constants.ts
Automates Polarion TC 340, 359, 360 and 361 for Jira Cloud
This suite generates dynamic test cases for Jira cloud waves export as different issue types.
Please note that these tests are co-dependant, which means that the test cases cannot be executed individually.
For a matter of readability, Jira Datacenter export tests will have to be automated in a different file.
Jenkins run: [#606](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/606/console)
@sshveta can you please review this PR? Thanks
=> [RFR] Export different issue types

cypress/e2e/tests/migration/migration-waves/filter.test.ts
Fixed filter test - now the test finds relevant h2 inside the migration waves table and validate that nothing is shown
=> [RFR] fix filter.test in migration waves

cypress/e2e/models/migration/migration-waves/migration-wave.ts, cypress/e2e/tests/migration/migration-waves/field_validation.test.ts
updated delete method in migration wave to also delete migration waves with no name based on startDate and endDate - 
fixed field validation test in migration wave by:
it was selecting incorrect days in dates such as "32" - fixed the regex for it
fixed method selectDateFromDatePicker as it was selecting incorrect dates which caused delete by date to fail
Jenkins run for field_validation: https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/770/
jenkins run for crud test: https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/771/
=> [RFR] fixed field validation test and updated migration wave delete method

cypress.config.ts, cypress/e2e/views/applicationinventory.view.ts, cypress/e2e/views/common.view.ts, cypress/e2e/views/migration-wave.view.ts, cypress/utils/utils.ts
**removed cy.wait(800) because it was causing test to fail as the dialog was vanishing in this time!!**
jenkins run : https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/tackle-ui-tests-on-ocp/372/
https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/tackle-ui-tests-on-ocp/374/
=> [RFR] adapt some selectors for crud + create-tracker tests to work

cypress/e2e/views/common.view.ts, cypress/utils/utils.ts
Jenkins run : https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/tackle-ui-tests-on-ocp/371/
=> [RFR] fix filter test by adapting "selectFilter" method

cypress/e2e/models/migration/applicationinventory/analysis.ts, cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts, cypress/e2e/views/applicationinventory.view.ts, cypress/e2e/views/common.view.ts, cypress/fixtures/analysis.json
The new Tackle version will change how reports are displayed to the user, focusing more on multiple-analyses trends and general issues rather than specific reports for each applications.
The old reports are hidden right now (Tackle2-ui [PR 891](https://github.com/konveyor/tackle2-ui/pull/891)), that's why I removed the validations from the code. Later we may add them if the reports are available again or automate the new dynamic reports feature.
Jenkins job [#382](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/tackle-ui-tests-on-ocp/382/console) passed.
I also used this PR to refactor some code and remove some other unused code.
@sshveta could you please review this PR? Thanks
=> [RFR] [CR] [TA] Adapt source analysis test

cypress/e2e/models/migration/reports/reports.ts
jenkins run will be available after merging https://github.com/konveyor/tackle-ui-tests/pull/671 as it depends on it's changes
=> [RFR] update verifyApplicationRisk at reports.ts adapting to upstream

cypress/e2e/models/migration/applicationinventory/assessment.ts, cypress/e2e/models/migration/reports/reports.ts, cypress/e2e/tests/migration/reports/filter.test.ts, cypress/e2e/tests/migration/reports/pagination.test.ts, cypress/e2e/views/applicationinventory.view.ts, cypress/e2e/views/common.view.ts
added a missing import
jenkins failed due to ongoing development of Assess in application inventory
https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/tackle-ui-tests-on-ocp/474/
=> [RFR] added missing import in reports.ts

cypress/e2e/models/migration/applicationinventory/application.ts, cypress/e2e/views/applicationinventory.view.ts, cypress/utils/utils.ts
Solved by making `click()` function to select first element instead of searching all. Added parameter to specify which element number user wants to click instead of first one.
=> [RFR] Fixed assessment/crud test

cypress/e2e/models/migration/migration-waves/migration-wave.ts
clicking with focus stop working on creating a migration wave
also clicking using cypress
changed to clicking with JS
jenkins run : https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/tackle-ui-tests-on-ocp/514/console
=> [RFR] changed clicking with focus to clicking using JS when creating migration wave

cypress/e2e/tests/migration/applicationinventory/analysis/bulk_analysis.test.ts
modified:   cypress/e2e/tests/migration/applicationinventory/analysis/bulk_analysis.test.ts
=> [RFR][TA] Custom metrics after bulk analysis

cypress/utils/utils.ts
1)I've updated deleteApplicationTableRows()  since the DOM tree structure on the upstream Application Inventory page has been updated . 
2) The new deleteApplicationTableRows() works only on the Application Inventory -> Assessment page since this has been adapted for PF5.   The  Application Inventory -> Analysis page will be adapted for PF5 after feature freeze. 
3) The deleteApplicationTableRows() fn works fine on an empty table and a non-empty table. 
Notes:
I will update PR with the results from Jenkins run shortly. The PR passed locally.
=> [RFR] [CR] Refactor deleteApplicationTableRows()

PR_TESTER.jenkinsfile
This PR contains jenkinsfile to test tackle ui tests on minikube for PRs.
=> Add PR tester for tackle ui tests

cypress/e2e/models/migration/migration-waves/migration-wave.ts, cypress/e2e/tests/migration/migration-waves/field_validation.test.ts, cypress/e2e/views/migration-wave.view.ts
jenkins run: https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/tackle-ui-tests-on-ocp/542/
https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/tackle-ui-tests-on-ocp/543/
=> [RFR] adapted to submit button and fixed field_validation

cypress/e2e/tests/administration/repository/maven.test.ts, cypress/e2e/tests/migration/applicationinventory/analysis/binary_analysis.test.ts, cypress/e2e/tests/migration/applicationinventory/analysis/upload_binary_analysis.test.ts
=> [RFR] Skipping all binary analysis tests

cypress/e2e/tests/migration/applicationinventory/manageimports/csv.test.ts, cypress/e2e/tests/migration/applicationinventory/manageimports/filter.test.ts, cypress/e2e/tests/migration/applicationinventory/manageimports/pagination.test.ts, cypress/e2e/views/common.view.ts, cypress/utils/utils.ts
Solves: https://issues.redhat.com/browse/MTA-1363
Jenkins run: https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/969/console
=> [RFR] [JF] [TA] adapt manageimport tests

cypress/e2e/tests/migration/controls/stakeholdergroups/create.test.ts, cypress/e2e/views/common.view.ts
modified:   cypress/e2e/views/common.view.ts
=> [RFR][AF] Fix for stakeholder groups tests

cypress/e2e/tests/migration/controls/businessservices/crud.test.ts
jenkins : currently failing due to a bug, marked on test
=> [RFR]marking mta bug for test and adding success message check

cypress/e2e/models/administration/assessment_questionnaire/assessment_questionnaire.ts, cypress/e2e/tests/migration/applicationinventory/assessment/assess_review.test.ts, cypress/e2e/views/assessmentquestionnaire.view.ts
=> [RFR] Add method to enable/disable questionnaire

cypress/e2e/tests/migration/applicationinventory/applications/bulk_deletion_applications.test.ts
Solves [MTA-1548](https://issues.redhat.com/browse/MTA-1548)
This test was failing because the delete button was disabled due to migration waves with associated applications that were not deleted from previous tests.
Since migration waves can remain undeleted due to failures in other tests or bugs in the product, it is not the responsibility of this test to delete those migration waves.
That's why this PR adds a check so that the test won't run if there is remaining data and indicates that it has failed for that reason. It suggests checking the existence of undeleted data as the first likely cause.
Jenkins run [1092](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/1092/console)
=> [RFR] [JF] Improve bulk deletion test

cypress/e2e/models/administration/custom-migration-targets/custom-migration-target.ts, cypress/e2e/tests/administration/custom-migration-targets/crud.test.ts, cypress/e2e/views/custom-migration-target.view.ts
Solves [MTA-1542](https://issues.redhat.com/browse/MTA-1542)
This test will fail as the related bug is still open.
Hi @sshveta could you please review this PR? Thanks!
=> [RFR] Add custom migration target regression test

cypress/e2e/models/migration/applicationinventory/assessment.ts, cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts
The 'Discard assessment/Review' option is now split into 'Discard assessment' and 'Discard review' . So, I'm submitting this PR to address the changes .
=> [RFR] Add separate tests for discarding Assessment and Review

cypress/e2e/models/migration/applicationinventory/assessment.ts, cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts
=> [RFR] [NA] Retake assessment questionnaire

cypress/e2e/tests/migration/applicationinventory/manageimports/pagination.test.ts, cypress/e2e/tests/migration/controls/businessservices/pagination.test.ts, cypress/e2e/tests/migration/controls/jobfunctions/pagination.test.ts, cypress/e2e/tests/migration/controls/stakeholdergroups/pagination.test.ts, cypress/e2e/tests/migration/controls/stakeholders/pagination.test.ts, cypress/e2e/views/applicationinventory.view.ts, cypress/e2e/views/common.view.ts, cypress/utils/utils.ts
1) Refactored delete methods
2) Mark bugs
=> [RFR][CR][JF] Fix tier3 failures

cypress/e2e/models/migration/applicationinventory/analysis.ts, cypress/e2e/models/migration/applicationinventory/application.ts, cypress/e2e/tests/rbac/architect.test.ts, cypress/e2e/tests/rbac/migrator.test.ts, cypress/e2e/types/types.ts, cypress/fixtures/rbac.json
=> [RFR] [JF] Refactored RBAC tests to adopt UI changes

cypress/e2e/models/migration/applicationinventory/archetype.ts
=> [RFR] Add Archetype class

cypress.config.ts, cypress/e2e/models/migration/applicationinventory/assessment.ts, cypress/e2e/tests/migration/applicationinventory/assessment/assess_review.test.ts, cypress/e2e/types/constants.ts, cypress/e2e/views/assessment.view.ts
=> [RFR] automate MTA-382--assess application with multiple questionnaires

cypress/e2e/models/administration/general/generalConfig.ts, cypress/e2e/models/migration/applicationinventory/analysis.ts, cypress/e2e/models/migration/applicationinventory/application.ts, cypress/utils/data_utils.ts, cypress/utils/utils.ts
* Removed unused code
* Minor improvements on code quality
* Fixed some typos
Part of [MTA-1728](https://issues.redhat.com/browse/MTA-1728)
=> [RFR] Minor code quality improvements

cypress/e2e/models/migration/applicationinventory/application.ts, cypress/e2e/tests/migration/applicationinventory/applications/create.test.ts, cypress/e2e/types/constants.ts, cypress/e2e/types/types.ts, cypress/e2e/views/applicationinventory.view.ts
modified:   cypress/e2e/models/migration/applicationinventory/application.ts
modified:   cypress/e2e/tests/migration/applicationinventory/applications/crud.test.ts
modified:   cypress/e2e/types/constants.ts
modified:   cypress/e2e/views/applicationinventory.view.ts
=> [RFR] Automate Application information test case

cypress/e2e/models/administration/custom-migration-targets/custom-migration-target.ts, cypress/e2e/models/migration/applicationinventory/analysis.ts, cypress/e2e/tests/administration/custom-migration-targets/crud.test.ts, cypress/e2e/types/types.ts, cypress/e2e/views/custom-migration-target.view.ts
Solves [MTA-1703](https://issues.redhat.com/browse/MTA-1703) and solves a minor JF
Automates Polarion TC [408](https://polarion.engineering.redhat.com/polarion/redirect/project/MTAPathfinder/workitem?id=MTA-408) 
Jenkins run [1397](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/1397/console)
=> [RFR] Automate language selection

cypress/e2e/models/migration/dynamic-report/issues/issues.ts
Moved selecting filter type out of condition, otherwise filter type was not changed in case of single application filtering
=> [RFR] Fix for single app issues filtering

cypress/e2e/models/migration/applicationinventory/application.ts, cypress/e2e/models/migration/applicationinventory/assessment.ts, cypress/e2e/tests/migration/applicationinventory/assessment/archetype_association.test.ts, cypress/utils/utils.ts
Notes:
1)   I'm validating that 'Archetypes reviewed' is populated with the correct values through this PR.  I will add validateInheritedReviewFields() through another PR . It needs additional testing since the base method is used by both archetypes and applications.
2) [Jenkins job](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1698)
=> [RFR] Verify field(s) are populated on application drawer after review inheritance from multiple archetypes

cypress/e2e/tests/upgrade/create_upgrade_data.test.ts, cypress/e2e/types/types.ts, cypress/fixtures/upgrade-data.json
=> [RFR] Added assessment to pre-upgrade test

cypress.config.ts, cypress/e2e/tests/administration/repository/subversion.test.ts, cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts, cypress/fixtures/application.json
Solves [MTA-1744](https://issues.redhat.com/browse/MTA-1744) by Automating [MTA-1717](https://issues.redhat.com/browse/MTA-1717)
On January 8, 2024,[ GitHub removed support for Subversion](https://github.blog/2023-01-20-sunsetting-subversion-support/), making it unnecessary to maintain the test that was in the source_analysis suite, as it would be practically identical to the one in subversion.test.ts.
I have brought back the Subversion test, making the necessary adaptations, and removed the one from source_analysis since it's a duplicate, and both tests run on the same tier.
---
Jenkins run [1891](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/1891/console)
=> [RFR] Bring back svn tests

cypress/e2e/models/migration/applicationinventory/application.ts, cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts, cypress/e2e/views/applicationinventory.view.ts, cypress/fixtures/questionnaire_import/cloud-native.yaml
automates polarion - [MTA387](https://polarion.engineering.redhat.com/polarion/#/project/MTAPathfinder/workitem?id=MTA-387)
[jenkins](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1903/console)
=> [RFR] Validate auto tagging of applications based on assessment answers

cypress/e2e/tests/migration/migration-waves/crud.test.ts, cypress/e2e/tests/migration/migration-waves/export_to_jira_cloud.test.ts
It would be good to maintain the consistency between the interop and tier0 test suites. So, I'm updating the interop test suite to 
reflect that.
=> [RFR] Update interop test suite

dockerfiles/interop/Dockerfile
This PR removes the installation of unzip, it is no longer needed and is breaking the image
=> Fix Interop Dockerfile

cypress/e2e/models/migration/applicationinventory/assessment.ts, cypress/e2e/tests/administration/custom-migration-targets/field_validation.test.ts, cypress/e2e/tests/migration/applicationinventory/applications/filter.test.ts, cypress/utils/utils.ts, dockerfiles/interop/Dockerfile, package-lock.json, package.json
PR to upgrade our Cypress version to 13.6.4.
There weren’t many breaking changes in this update and I provided a Jenkins run in the PR before and after the upgrade to ensure we have the same results (there is a small difference and its not related to the upgrade).
I went through the changelog and here are the more important changes that affect us implemented in these versions:
- Automation performance is now improved by switching away from websockets to direct CDP calls for Chrome and Electron browsers. Addressed in [[#27592](https://github.com/cypress-io/cypress/issues/27592)](https://github.com/cypress-io/cypress/issues/27592).
- The minimum supported Typescript version is `4.x`.
- Improved performance when finding unique selectors for command log snapshots for Test Replay.
- Node 14 …
=> [RFR] Upgrade cypress to version 13

cypress/e2e/models/migration/archetypes/archetype.ts, cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts
Polarion TC - [MTA502](https://polarion.engineering.redhat.com/polarion/#/project/MTAPathfinder/workitem?id=MTA-502) and [MTA-387](https://polarion.engineering.redhat.com/polarion/#/project/MTAPathfinder/workitem?id=MTA-387)
[jenkins](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/2023/console)
Archetype.open(true); was added due to test failing to open archetype page.
=> [RFR] automate auto tagging of archetypes based on answers and use questionnaire template in test

cypress/utils/utils.ts
On an all tier run on Jenkins, the import tests failed because the Application Inventory page wouldn't load . Hence, I'm increasing the timeout while querying for kebab menu on the Application Inventory page.
=> [RFR] Increase timeout while querying for kebab menu on Application Inventory page

cypress.config.ts, cypress/e2e/models/migration/applicationinventory/application.ts
The Application 'Tags' tab on the side drawer takes long to load . So, I've added a wait to make sure we proceed only after the 'Tags' tab is loaded.
This fixes the 'Automated tagging using Source Analysis on tackle testapp'  failure in analysis/source_analysis.test.ts
=> [RFR] Wait for application tags tab to load

cypress/e2e/tests/migration/controls/businessservices/interlinked.test.ts
page updating was taking a couple of seconds before showing the updated owner name so i added wait and it fixed the error, please note that locally the test is passing due to cypress running faster
jenkins [run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/2266/)
JF jira [link](https://issues.redhat.com/browse/MTA-2361)
=> [RFR] fix JF - interlinked business service

cypress/e2e/tests/migration/migration-waves/export_to_jira_cloud.test.ts
The assertion failed because devs changed the disabled attribute for an aria-disabled one. But the button won't be disabled in the future due to [MTA-2225](https://issues.redhat.com/browse/MTA-2225) so there is no need to keep the assertion.
Jenkins run [2284](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/2284/)
=> [RFR] Remove disabled button assertion for exported apps on migration waves

cypress/e2e/models/migration/applicationinventory/application.ts
this.applicationDetailsTab(details); was causing the test to navigate to "Tags" tab instead of details
switched to sidedrawerTab(this.name, "Details");
jenkins [run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/2309/)
=> [RFR] fix JF - migration waves unlink application test

cypress/e2e/models/migration/applicationinventory/application.ts
The problem was that instead of comparing values, value was assigned which caused an automation bug
=> [RFR] [JF] Fixed failing unlink application test

cypress/e2e/models/migration/applicationinventory/application.ts
Related to https://github.com/konveyor/tackle2-ui/pull/1687
=> [RFR] Check 'Total Effort' instead of 'Effort'

cypress/e2e/tests/upgrade/create_upgrade_data.test.ts, cypress/e2e/views/common.view.ts, cypress/utils/utils.ts
=> [RFR] Added source version validation in 6.2.Z

cypress/e2e/tests/administration/custom-migration-targets/crud.test.ts, cypress/e2e/tests/rbac/custom-migration-target.test.ts
The analysis for the Disconnected cluster is failing because it lacks external network access. Consequently, we've decided to remove the 'dc' tag from 'custom-migration-target.test.ts' and 'rbac/custom-migration-target.test.ts'.
I'm currently reviewing the upload binary analysis since it operates on the DC cluster. Consequently, those test cases will be marked with the 'dc' tag in another PR.
=> [RFR][JF] Remove dc tag from custom-migration-targets test

cypress.config.ts, cypress/e2e/tests/upgrade/create_upgrade_data.test.ts
Since pre-upgrade and post-upgrade tests are triggered in separate test runs - one before the upgrade procedure and one after - we can use the same environment value `mtaVersion`
=> [RFR] Use Cypress.env(mtaVersion) for pre-upgrade test

cypress/e2e/tests/migration/applicationinventory/assessment/archetype_association.test.ts, cypress/e2e/tests/migration/archetypes/crud.test.ts, cypress/e2e/tests/migration/archetypes/miscellaneous.test.ts
1) Added an additional check to verify application  Assessment and Review get reset when archetype assessment/review 
is discarded
2) Moved Archetype assessment discard test
=> [RFR] Verify app Assessment and Review get reset when archetype assessment/review is discarded'

cypress.config.ts, cypress/e2e/tests/upgrade/after_upgrade.test.ts, cypress/e2e/tests/upgrade/create_upgrade_data.test.ts, cypress/support/e2e.js, package-lock.json, package.json
Enables fail fast in Cypress, skipping the rest of tests if `Validate MTA version in UI` test fails.
[Jenkins run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/2737/consoleFull)
For more information, see: https://github.com/javierbrea/cypress-fail-fast/blob/main/README.md
Resolves: https://issues.redhat.com/browse/MTA-2475
=> [RFR] Adding cypress-fail-fast plugin

cypress/e2e/models/migration/dynamic-report/issues/issues.ts, cypress/e2e/tests/migration/dynamic-report/issues/filter.sorting.pagination.test.ts
Bug was caused by redesigned filtering field, checkboxes list instead of usual text input. Applied fix and removed negative test as not relevant. Jenkins job fails only on known bugs.
=> [RFR] Fixed filtering issues

cypress/e2e/models/migration/migration-waves/migration-wave.ts
1. the original motivation no longer applies as bug MTA-706 is fixed
2. providing the end date via date picker fails repeatedly with PatternFly 5.2 (it seems the start date pop-up is still detected in the DOM tree)
Reference-Url: https://github.com/konveyor/tackle2-ui/pull/1680
=> Type MigrationWave end date directly into the input

cypress/e2e/models/migration/applicationinventory/analysis.ts
Supports https://github.com/konveyor/tackle2-ui/pull/1951
=> :sparkles: Support new dropdown for language select

.gitignore, cypress/utils/utils.ts, package.json, tsconfig.json
Motivation for this change is when there have been test run issues where the "after all" action fails because the row actions menu / kebab menu doesn't open.  These changes should allow the menu to be consistently opened.
=> [RFR] Update the row action handling to be more consistent

.prettierignore, cypress/e2e/models/migration/applicationinventory/analysis.ts, tsconfig.json
Follow-up to #1136
To make sure the test does not unselected the desired target language that is automatically selected from the application's tags (language-discovery automatically adds tags when the application is created), switch from a `click()` action to a `check()` action.  A bit more code is used to get to the input checkbox so the `check()` will work.
Note 1: This only became an issue on the test after the 0.5 alpha release when the language-discovery tasks started running consistently and accurately.
Note 2: Updated the `.prettierignore` to exclude the cypress run generated files from checking. Devs won't need to ignore style warnings on mocha json reports anymore.
=> [RFR] Fix selecting language on analysis wizard, targets step

cypress/e2e/models/migration/applicationinventory/analysis.ts, cypress/e2e/tests/administration/custom-migration-targets/crud.test.ts, cypress/fixtures/analysis.json, cypress/fixtures/application.json, cypress/fixtures/custom-rules.json, cypress/fixtures/go-analysis.json, cypress/fixtures/go-application.json, cypress/fixtures/yaml/golang-dep-rules.yaml
Important changes to review:
- Added fixtures
- Changes in `public static selectLanguage` - need it to test drag and drop target cards
I tried not to change the current implementation, but to use dynamic names to be able to run on different language than Java
Jenkins run: https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/3456/console
=> [RFR] Added Go analysis support and use in custom migration targets tests

cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
Resolves https://issues.redhat.com/browse/MTA-3562 
[Jenkins Run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/3529/console) The Tests related to bugs get failed and all other relevant tests Succeeded.
=> [RFR] Fix Source analysis

cypress/e2e/tests/migration/applicationinventory/applications/dependency.test.ts
Solves [MTA-3613](https://issues.redhat.com/browse/MTA-3613)
=> [RFR] Mark Product Bug

cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts, cypress/fixtures/analysis.json, cypress/fixtures/application.json
Automates https://issues.redhat.com/browse/MTA-3442
=> [RFR] Automate bug tackle-testapp-public using 4 targets for analysis

cypress/e2e/tests/migration/applicationinventory/analysis/gradle_analysis.ts, cypress/fixtures/application.json, cypress/fixtures/yaml/jmh-gradle-annotation-state-test-rule.yaml
Solves [MTA-3176](https://issues.redhat.com/browse/MTA-3176) by automating Polarion TC 532
This TC analyzes a Java application managed with Gradle, using a custom rule that should report a total effort of 36.
I created a new suite because I'll be adding more tests for Gradle in the near future.
=> [RFR] Automate first gradle analysis

cypress/e2e/models/administration/assessment_questionnaire/assessment_questionnaire.ts, cypress/e2e/models/migration/applicationinventory/application.ts, cypress/e2e/models/migration/controls/stakeholders.ts, cypress/e2e/tests/migration/applicationinventory/assessment/questionnaire_features.test.ts, cypress/utils/utils.ts
Resolves Jira [MTA-3720](https://issues.redhat.com/browse/MTA-3720)
[Jnekins run ](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/3766/)
=> [RFR] Update open() for a few classes

cypress/e2e/models/migration/task-manager/task-manager.ts, cypress/e2e/tests/migration/task-manager/miscellaneous.test.ts
=> [RFR] Task manager enable premeption

cypress/e2e/models/administration/assessment_questionnaire/assessment_questionnaire.ts, cypress/e2e/models/migration/archetypes/archetype.ts, cypress/e2e/models/migration/controls/stakeholders.ts, cypress/e2e/tests/migration/archetypes/questionnaire_features.test.ts, cypress/utils/utils.ts
This resolves [JF MTA-3829 .](https://issues.redhat.com/browse/MTA-3829)
=> [RFR] Update Archetype.open() method

cypress/e2e/models/migration/archetypes/archetype.ts
Relates to: [konveyor/tackle2-ui#2098](https://github.com/konveyor/tackle2-ui/pull/2098)
=> Using performRowActionByIcon for editing archetype

cypress/fixtures/questionnaire_import/invalid-questionnaire-template.yaml
Updated the value of red to be a string instead of an integer so it becomes invalid
```
thresholds: 
red: "five"  <---- here
yellow: 10 
unknown: 15
```
=> [RFR] updated the invalid questionnaire

cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
Automates https://issues.redhat.com/browse/MTA-4010
[Jenkins link](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/3841/)
=> [RFR][TA] Source analysis on tackle app with hash in Password

cypress.config.ts, cypress/e2e/tests/administration/questionnaires/miscellaneous.test.ts, package-lock.json, package.json
added a way to get the latest downloaded questionnaire file instead of giving a static number
[Jenkins Run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/3976/console)
=> [JF] [RFR] Fix MTA-437 --- Exports and imports existing questionnaire after updating name in file

cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
=> [RFR][JF] Remove Source analysis bug number

cypress/e2e/models/migration/archetypes/archetype.ts, cypress/utils/utils.ts
[Jenkins job ](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/3979/)
Resolves [JF](https://issues.redhat.com/browse/MTA-4154)
=> [RFR] Fix app archetype association test

cypress/e2e/tests/migration/task-manager/sorting.filter.pagination.test.ts, cypress/e2e/views/taskmanager.view.ts
Resolves: https://issues.redhat.com/browse/MTA-4108
Fixing task manager filtering test by making sure that task IDs exist
=> [RFR][JF] Fixed task manager filtering test

cypress/e2e/tests/migration/controls/stakeholdergroups/pagination.test.ts, cypress/utils/utils.ts
Resolves https://issues.redhat.com/browse/MTA-4239 
[Jenkins Run ](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/4010/console)
=> [RFR][JF] Fix deleteAllStakeholderGroups() method

cypress/e2e/tests/migration/applicationinventory/applications/import.test.ts, cypress/fixtures/app_import/csv/lantik_bug.csv, cypress/fixtures/app_import/csv/missing_tags_and_bs.csv
=> [RFR] Application import: Verify assigned BS for imported application if BS already exists

cypress/e2e/tests/migration/applicationinventory/analysis/binary_analysis.test.ts, cypress/e2e/tests/migration/applicationinventory/analysis/upload_binary_analysis.test.ts
Resolves https://issues.redhat.com/browse/MTA-4244 
[Jenkins Run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/4076/)
=> [RFR][JF] Fix upload binary test case

cypress/e2e/tests/administration/repository/subversion.test.ts
removed `Analysis on SVN Repository without trunk folder` TC as it is not relevant any more
This test case was required to test if running analysis on svn repo with trucnk folder missing it should show the relevant error message and the analysis should fail. [see here](https://issues.redhat.com/browse/MTA-1717)
The test failed in the latest run, and a [bug](https://issues.redhat.com/browse/MTA-4324) was opned
But this TC is not required anymore as per discussion with the devs, [see here](https://redhat-internal.slack.com/archives/C048D5SFKSN/p1733409070513449) so it's removed.
**[Jenkins run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/4110/console)**
=> [RFR] [JF] Remove TC that automates MTA-1717

cypress/e2e/tests/migration/dynamic-report/issues/filter.sorting.pagination.test.ts, cypress/fixtures/analysis.json
This is fix for configuration error that now is fixed
=> [RFR] Fixed wrong analysis parameter in issues test and fixed json file

cypress/e2e/tests/migration/task-manager/task_manager.test.ts
Resolves: https://issues.redhat.com/browse/MTA-3327
Jenkins run: https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/tackle-ui-tests-pr-tester/job/PR-1288/1/console
=> [RFR] Task manager: application related tasks are deleted once the app is deleted

cypress/e2e/models/migration/applicationinventory/analysis.ts, cypress/e2e/tests/migration/applicationinventory/analysis/load_analysis.test.ts, cypress/e2e/types/constants.ts
Resolves: https://issues.redhat.com/browse/MTA-4355
Relates to: https://issues.redhat.com/browse/MTA-4354
TIER0 Jenkins run: https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/4171/consoleFull
`load_analysis.test.ts`: https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/4183/console
=> [RFR] Limit analysis verifyStatus timeout to 10 mins

cypress/e2e/models/migration/task-manager/task-manager.ts, cypress/e2e/tests/migration/task-manager/task_manager.test.ts
Resolves: https://issues.redhat.com/browse/MTA-4427
Jenkins run: https://jenkins-csb-migrationqe-main.dno.corp.redhat.com/view/Konveyor/job/mta/job/tackle-ui-tests-pr-tester/view/change-requests/job/PR-1303/1/console
=> [RFR] Check discovery tasks for app with source code and branch name

cypress/e2e/models/migration/applicationinventory/application.ts, cypress/e2e/models/migration/migration-waves/migration-wave.ts
Sometimes, Cypress would think the tooltip was hiding the button, causing it to fail
=> [RFR] Avoid error on unlink test

cypress/e2e/tests/migration/migration-waves/filter_applications.test.ts, cypress/e2e/views/common.view.ts, cypress/utils/utils.ts
Solves [MTA-4455](https://issues.redhat.com/browse/MTA-4455)
Jenkins run [4324](https://jenkins-csb-migrationqe-main.dno.corp.redhat.com/job/mta/job/mta-ui-tests-runner/4324/consoleFull)
=> [RFR] [JF] Fix selectfilter method

cypress/e2e/models/migration/controls/jobfunctions.ts
Related to https://github.com/konveyor/tackle2-ui/pull/2101
Jenkins run: https://jenkins-csb-migrationqe-main.dno.corp.redhat.com/view/Konveyor/job/mta/job/tackle-ui-tests-on-ocp/778/console
=> [RFR] Test of 'Add ActionsColumn to Job Functions table #2101'

cypress/fixtures/analysis.json
The  Analysis for acmeair app upload binary test from upload_binary_analysis.test.ts   is a part of the InterOp suite and is currently failing on the mta_7.2.0 branch.  This PR addresses the failure.
=> Update effort value for binaries  for 7.2.0 branch

cypress/e2e/models/migration/task-manager/task-manager.ts, cypress/e2e/tests/migration/task-manager/miscellaneous.test.ts, cypress/e2e/types/constants.ts, cypress/fixtures/custom-resource.json, cypress/fixtures/yaml/resource-quota.yaml, cypress/utils/utils.ts
Resolves: https://issues.redhat.com/browse/MTA-4387
- Run bulk analysis so there will be tasks in `Pending` and `Running` state 
- Limit pods before testing enable and disable preemption
- Ensure a task with the desired status exists before canceling
Jenkins run: https://jenkins-csb-migrationqe-main.dno.corp.redhat.com/view/Konveyor/job/mta/job/tackle-ui-tests-pr-tester/view/change-requests/job/PR-1318/10/console
=> [RFR] Fix JF for Actions in Task Manager Page

cypress.config.ts
The e2e spec glob was grabbing all `.ts` files instead of the intended `*.test.ts` files.  This caused problems when cypress attempting to run a lot more tests when a `--spec` argument was not specified.  Now, by default, cypress will only run `*.test.ts` files.
=> [RFR] Update e2e spec glob to only include actual tests

cypress/e2e/tests/migration/controls/tags/tag/crud.test.ts, cypress/e2e/tests/migration/migration-waves/crud.test.ts
=> [release-0.6] move tag and mig wave crud tests to tier2

cypress/e2e/tests/migration/reports-tab/reports.test.ts
the [MTA-6276 bug](https://issues.redhat.com/browse/MTA-2676) is no longer failing, the unassessed option is added to the list of risk types
=> Removed bug MTA-6276 marker as the test is passing

cypress/utils/utils.ts
Check if the passed column name has more than one string, if so, then only lower the cases of the first string
**[Jenkins Run](https://jenkins-csb-migrationqe-main.dno.corp.redhat.com/job/mta/job/mta-ui-tests-runner/4501/console)**
=> Fix Column selection

cypress/e2e/models/migration/applicationinventory/analysis.ts, cypress/e2e/models/migration/migration-waves/migration-wave.ts, package.json
Resolves https://issues.redhat.com/browse/MIGENG-2074
If the language discovery task takes longer than expected, there will be no language pre-selected when opening the analysis wizard, I updated the method (which is used only here) to click the `clear all filters` button only if present.
=> :bug: [RFR] Fix custom migration target crud test

cypress/e2e/tests/migration/task-manager/sorting.filter.pagination.test.ts
Since tests are not running in isolation , we cannot assert for task manager status , there might be applications that get created from other tests and fails in validation . Hence removed some negative assertions .
=> [RFR] Fix task manager sorting test

cypress/e2e/tests/migration/applicationinventory/analysis/static_report.test.ts, cypress/support/e2e.ts, cypress/utils/utils.ts
Resolves [MTA-5004](https://issues.redhat.com/browse/MTA-5004).
`cy.visit` prepends the `baseUrl` to the url passed so now that we have set the `baseUrl` property, the visit to the local report was failing.
In this PR I also add a verification to the `isTableEmpty` method to check that the table has finished loading.
=> :seedling: [RFR] Adapt static report test to baseUrl changes

cypress/e2e/tests/administration/questionnaires/miscellaneous.test.ts, cypress/e2e/tests/migration/controls/businessservices/interlinked.test.ts
Resolves [MTA-5020](https://issues.redhat.com/browse/MTA-5020)
CI will fail due to the typo fixed on `cypress/e2e/tests/administration/questionnaires/miscellaneous.test.ts` as it has one failing test caused by a product bug
This test was failing when editting the name of a stakeholder assigned to a bussiness service because when going back to the business services page to check if the stakeholder was updated there as well the test was not waiting for the UI to display the updated values.
=> :bug: [RFR] Fix business service interlinked test

cypress/e2e/tests/migration/dynamic-report/issues/filter.sorting.pagination.test.ts
Since `cypress-tags` works as a preprocessor, all of the test blocks need to have static tag and title arguments. One test suit has a dynamic title (just a simple ternary is technically dynamic) and was always being included.
Switching the `it()` title to be a template string allows the preprocessor to see it as a string and properly apply the tags from the `define()` block.
=> Update a test's title so cypress-tags doesn't include it by accident

cypress/e2e/models/migration/applicationinventory/analysis.ts, cypress/e2e/tests/upgrade/after_upgrade.test.ts
The automation for re-analysis of an already analyzed app after upgrade failed because it takes a few seconds for Analysis status to switch from 'Completed' to 'Not started'. So, I'm adding a new method that waits for analysis status to change.
=> [release-0.7] Fix post upgrade tests
