konveyor/tackle-ui-tests

.github/workflows/main.yaml

Verified with this PR - https://github.com/ganeshhubale/tackle-ui-tests/pull/1

RFR: Add GitHub action to check code formatting

---

cypress/integration/models/stakeholdergroups.ts
cypress/integration/models/stakeholders.ts
cypress/integration/tests/controls/stakeholdergroups/create.test.ts
cypress/integration/tests/controls/stakeholdergroups/crud.test.ts
cypress/integration/types/constants.ts
cypress/integration/views/commoncontrols.view.ts
cypress/integration/views/stakeholdergroups.view.ts
cypress/utils/utils.ts

- Creatd stakeholder group with stakeholder member
- Edited and deleted group
- While editing, provided same member > as per functionality if we select same member again then it deselects
- Checked member attached to group or not by its member count

RFR: Automate test case for stakeholder group with member

---

cypress/integration/tests/controls/stakeholdergroups/create.test.ts
cypress/integration/views/commoncontrols.view.ts
cypress/integration/views/stakeholdergroups.view.ts

- Moved helper warning widgets to common controls view and Removed helper widgets from particular stakeholder group view 
- Updated create and check warning test case for stakeholder group according to helper widgets

RFR: Helper warning widgets moved and test case update

---

cypress/integration/models/businessservices.ts
cypress/integration/tests/controls/businessservices/create.test.ts
cypress/utils/data_utils.ts

This PR contains three test cases automated:
- "Business services name and description constraints check"
- "Cancel and close on business services creation" 
- "Business services name must unique" 
This PR depends on #10 #7

RFR: Automate checks while creating bussiness service 

---

cypress/integration/views/commoncontrols.view.ts

RFR: Fixed assertion error because of table not found

---

cypress/integration/tests/controls/stakeholders/filter.test.ts
cypress/integration/types/constants.ts
cypress/integration/views/commoncontrols.view.ts
cypress/utils/utils.ts

This PR contains - 
- Stakeholder filter test cases
- Approach to login only once before all tests are run
- Clean up the test data in after all block

[RFR] Added new test case for stakeholder filter

---

.github/workflows/cypress-run.yaml
cypress.json

RFR: GitHub Action for recording results to cypress dashboard

---

cypress/integration/tests/controls/jobfunctions/create.test.ts
cypress/integration/tests/controls/stakeholders/create.test.ts
cypress/integration/tests/controls/stakeholders/filter.test.ts

RFR: Fixed common  view import

---

cypress/integration/tests/applicationinventory/application/create.test.ts
cypress/integration/tests/controls/jobfunctions/create.test.ts
cypress/integration/tests/controls/stakeholders/create.test.ts
cypress/integration/tests/controls/stakeholders/filter.test.ts

RFR: Application create form field/button validations

---

cypress/integration/tests/controls/businessservices/sort.test.ts
cypress/integration/types/constants.ts
cypress/utils/utils.ts

1. Business services sort validation 
- Sort by name
- Sort by owner

RFR: Automate business services sort test cases

---

cypress/integration/models/applicationinventory/applicationinventory.ts
cypress/utils/utils.ts

1. Fix for common method - inputText
2. Fix for application edit and delete

RFR: Fixed application CRUD test case

---

cypress/integration/tests/controls/businessservices/crud.test.ts
cypress/utils/utils.ts

RFR: Automate business service crud with owner

---

cypress/integration/tests/controls/businessservices/interlinked.test.ts
cypress/utils/utils.ts

1. Test case for Business service interlinked with  stakeholders
- stakeholders attach, update and delete dependency on business service

RFR: Automate interlinked test case for business services

---

cypress/integration/tests/controls/stakeholdergroups/pagination.test.ts
cypress/utils/utils.ts

- Automate pagination validation for stakeholder groups
- Items per page validations
- Page number validations
- Last page item(s) deletion, impact on page reload validation
- Added wait till widget itemsPerPageMenuOptions appear

RFR: Automated pagination validation for stakeholder groups

---

cypress/integration/tests/controls/businessservices/pagination.test.ts

- Automate pagination validation for business services
- Navigation button validations
- Items per page validations
- Page number validations
- Last page item(s) deletion, impact on page reload validation

RFR: Automate pagination validation for business services

---

cypress/integration/tests/controls/jobfunctions/pagination.test.ts

- Automate pagination validation for job functions
-  Navigation button validations
- Items per page validations
- Page number validations
- Last page item(s) deletion, impact on page reload validation

RFR: Automate pagination validation for job functions

---

README.md
cypress/integration/tests/controls/stakeholdergroups/interlinked.test.ts
cypress/integration/tests/controls/stakeholders/interlinked.test.ts
cypress/utils/utils.ts

- Added stakeholder interlinked test case to validate impact of stakeholder groups and job function
- Edited utils file to remove duplicate function call and add wait
- Updated value check after delete in stakeholder groups interlinked test
- Fixed typo in READ ME
Test run result

[RFR] Interlinked stakeholders test case

---

README.md

As I can see it gets difficult to understand how to fix errors when prettier tool does not succeed.
I have added two steps before pushing code or to check code formatting on local machine.

RFR: Add steps to format code

---

README.md
cypress.json

RFR: Updated to dashboard keys and readme

---

cypress/integration/tests/controls/tags/tag/create.test.ts
cypress/integration/tests/controls/tags/tagtype/create.test.ts
cypress/integration/types/constants.ts
cypress/integration/views/tags.view.ts

This PR contains the create.test.ts scripts for creating tag and tag types

[RFR] Tag and Tag type create validations test scripts

---

cypress/integration/tests/controls/tags/tag/filter.test.ts
cypress/integration/tests/controls/tags/tagtype/filter.test.ts
cypress/integration/tests/controls/tags/tagtype/sort.test.ts
cypress/integration/types/constants.ts

This PR contains test cases for -
- Sorting tag type by name, rank and tag count
- Filtering search results for tag type
- Filtering search results for tags

[RFR] Added sorting and filtering test cases for tag type

---

README.md
cypress.json

RFR: Update cypress dashboard record keys

---

cypress/integration/tests/controls/tags/tagtype/pagination.test.ts

This PR contains pagination test case for Tags view

[RFR] Tags pagination test automation script

---

README.md
cypress.json

RFR: Updated cypress record keys

---

cypress/integration/models/stakeholdergroups.ts
cypress/integration/tests/controls/businessservices/pagination.test.ts
cypress/integration/tests/controls/jobfunctions/pagination.test.ts
cypress/integration/tests/controls/stakeholdergroups/pagination.test.ts
cypress/integration/tests/controls/stakeholders/pagination.test.ts
cypress/integration/tests/controls/tags/tagtype/pagination.test.ts
cypress/utils/utils.ts

This PR contains -
- Optimized row delete function for all pagination test cases
- Use common and re-usable data creation function for each model
- Fix for stakeholdergroup create method in model class

[RFR] Optimization for pagination test cases

---

cypress/integration/tests/controls/businessservices/sort.test.ts
cypress/integration/tests/controls/stakeholdergroups/interlinked.test.ts
cypress/utils/utils.ts

Fixed the constant test run failures

[RFR] Fix test failures

---

cypress/integration/tests/applicationinventory/application/filter.test.ts
cypress/integration/types/constants.ts
cypress/utils/utils.ts

This PR includes:
- Add constants for filter types business service and tags
- Enhanced applySearchFilter method
- This will allow to search multiple values
- Automated test cases 
- Name filter validations
- Descriptions filter validations
- Business service filter validations
- Tag filter validations

RFR: Automate filter validations for application inventory

---

cypress/integration/tests/applicationinventory/application/pagination.test.ts

RFR: Automate pagination validation for application inventory

---

cypress/integration/tests/controls/businessservices/filter.test.ts

This PR includes:
Automation of filter test cases of business services.
- Name filter validations
- Description filter validations
- Owner filter validations

RFR: Automate filter test cases for business services

---

cypress/integration/tests/applicationinventory/application/filter.test.ts
cypress/integration/views/common.view.ts
package-lock.json

RFR: Fixed application filter test cases

---

cypress/integration/models/applicationinventory/applicationinventory.ts
cypress/integration/tests/applicationinventory/manageimports/filter.test.ts
cypress/integration/tests/applicationinventory/manageimports/sort.test.ts
cypress/integration/views/applicationinventory.view.ts

- Sorting test cases for manage application imports page based on date, file name, status and user.
- Filter test case to search imported files by their name

[RFR] : Added sort and filter test case for manage imports page

---

cypress/integration/tests/applicationinventory/manageimports/pagination.test.ts

This PR includes pagination test case for manage imports page

[RFR] : Added pagination test case for manage imports page

---

.github/workflows/report-portal.yaml
cypress.json
cypress/plugins/index.js
cypress/support/commands.js
cypress/support/index.js
package-lock.json
package.json
reportconfig.json

Connect cypress automation framework to report portal.
This GH action helps to collect test run results and upload it to report portal.

RFR: Report portal connect

---

.github/workflows/report-portal.yaml
package.json

RFR: Removed tests script

---

.github/workflows/pull-requests.yaml

RFR: Tackle instance URL

---

.github/pull_request_template.md
.github/workflows/k8s-ci.yml
.github/workflows/k8s-cron.yml
.github/workflows/pull-requests.yaml

- Minikube integration to PR tester GH action

RFR: Pull request tester integrated with minikube

---

.github/workflows/k8s-cron.yml
.github/workflows/report-portal.yaml
cypress.json
reportconfig.json

1. Running cron jobs in parallel mode
2. Creating 4 container

[RFR] Running cypress tests in parallel mode

---

.github/workflows/k8s-cron.yml

RFR: Fixed cron job

---

.github/workflows/k8s-cron.yml

1. Removed unused step - Checkout input branch
2. Removed dev branch mattrix
3. Kept 3 containers

RFR: Remove dev branch from mattrix

---

.github/workflows/k8s-ci.yml
.github/workflows/k8s-cron.yml
.github/workflows/prettier.yaml
.github/workflows/report-portal.yaml
README.md
cypress.json
reportconfig.json

I have removed implementation done using cypress parallel feature.
And kept old implementation as it is.

RFR: Removed parallel test execution

---

.github/workflows/k8s-ci.yml
.github/workflows/k8s-cron.yml
.github/workflows/prettier.yaml
.github/workflows/pull-requests.yaml
cypress/integration/tests/login.test.ts

- GH action for Multiple jobs to execute test cases in parallel mode :- k8s-ci
- smaller updates to other jobs
- Added tier to login test case
- Reduced time taken by **pull_request** github action by sharing values between jobs with condition

RFR: GH action for tiers test cases

---

cypress/integration/models/applicationinventory/applicationinventory.ts
cypress/integration/tests/applicationinventory/application/copy_assessment/copy_assessment.test.ts

- Added new test case for copy assessment from one app to many
- Completed the pending copy to self test case
- Added after() clean up steps for deleting stakeholder groups and applications

[RFR] Added new test case for Copy assessment - one to many

---

cypress/integration/tests/applicationinventory/application/copy_assessment/filter.test.ts
cypress/integration/views/applicationinventory.view.ts
cypress/utils/utils.ts

Script to verify the filters for copy assessment model

[RFR] Added filter test case for copy assessment

---

cypress/integration/models/applicationinventory/applicationinventory.ts
cypress/integration/tests/applicationinventory/application/copy_assessment/pagination.test.ts
cypress/integration/views/applicationinventory.view.ts

- Automated pagination test cases for application copy assessment page

RFR: Copy assessment pagination test automation

---

cypress/integration/tests/applicationinventory/application/copy_assessment/copy_assessment.test.ts

- Global checkbox test cases scenarios covered

RFR: Copy assessment checkbox validations

---

cypress/integration/models/applicationinventory/applicationinventory.ts
cypress/integration/models/businessservices.ts
cypress/integration/models/jobfunctions.ts
cypress/integration/models/stakeholdergroups.ts
cypress/integration/models/stakeholders.ts
cypress/integration/tests/controls/stakeholders/create.test.ts
cypress/integration/tests/controls/stakeholders/crud.test.ts
cypress/integration/tests/controls/stakeholders/filter.test.ts
cypress/integration/tests/controls/stakeholders/interlinked.test.ts
cypress/integration/tests/controls/stakeholders/pagination.test.ts
cypress/integration/tests/controls/stakeholders/sort.test.ts
cypress/integration/views/common.view.ts
cypress/integration/views/stakeholders.view.ts

Fixed stakeholder apis with hub/stakeholder*
Added naviagtion to Developer menu
Fixed locator of pagination.

Stakeholder api fixes

---

cypress/integration/tests/reports/appsrisk.test.ts
cypress/integration/tests/reports/pagination.test.ts
cypress/integration/tests/reports/sort.test.ts

[RFR]: Reports: Business Services mandatory - fix more test

---

.github/crd.yaml
.github/workflows/pull-requests.yaml
cypress/integration/tests/developer/controls/stakeholders/crud.test.ts
package-lock.json
package.json

PRT tester 
Install minikube for PRT

[RFR] PRT tester install minikube for TACKLE2

---

cypress/integration/tests/developer/controls/stakeholdergroups/create.test.ts
cypress/integration/tests/developer/controls/stakeholdergroups/crud.test.ts
cypress/integration/tests/developer/controls/stakeholdergroups/filter.test.ts
cypress/integration/tests/developer/controls/stakeholdergroups/interlinked.test.ts
cypress/integration/tests/developer/controls/stakeholdergroups/pagination.test.ts
cypress/integration/tests/developer/controls/stakeholdergroups/sort.test.ts

…groups/create.test.ts
modified:   cypress/integration/tests/developer/controls/stakeholdergroups/crud.test.ts
modified:   cypress/integration/tests/developer/controls/stakeholdergroups/filter.test.ts
modified:   cypress/integration/tests/developer/controls/stakeholdergroups/interlinked.test.ts
modified:   cypress/integration/tests/developer/controls/stakeholdergroups/pagination.test.ts
modified:   cypress/integration/tests/developer/controls/stakeholdergroups/sort.test.ts

[RFR] Automation fixes for Stakeholder groups test cases

---

cypress/integration/tests/developer/controls/businessservices/create.test.ts
cypress/integration/tests/developer/controls/businessservices/filter.test.ts
cypress/integration/tests/developer/controls/businessservices/interlinked.test.ts
cypress/integration/tests/developer/controls/businessservices/pagination.test.ts
cypress/integration/tests/developer/controls/businessservices/sort.test.ts
cypress/integration/tests/developer/controls/stakeholdergroups/pagination.test.ts
cypress/integration/types/constants.ts

modified:   cypress/integration/tests/developer/controls/businessservices/create.test.ts
modified:   cypress/integration/tests/developer/controls/businessservices/filter.test.ts
modified:   cypress/integration/tests/developer/controls/businessservices/interlinked.test.ts
modified:   cypress/integration/tests/developer/controls/businessservices/pagination.test.ts
modified:   cypress/integration/tests/developer/controls/businessservices/sort.test.ts
modified:   cypress/integration/tests/developer/controls/stakeholdergroups/pagination.test.ts
modified:   cypress/integration/types/constants.ts

[RFR] Automation fixes for Business services test cases

---

cypress.json
cypress/integration/views/login.view.ts
cypress/utils/utils.ts

UI automation for password change screen.

[RFR] Change password UI automation

---

cypress/utils/utils.ts

RFR : fix createMultipleApplications function

---

.github/workflows/pull-requests.yaml
cypress/utils/utils.ts

Not able to push to @amastbau PR #145 so raising this one .

[RFR] PR #145 - Fix select admin menu

---

cypress.json
cypress/integration/tests/developer/controls/stakeholders/create.test.ts
cypress/utils/utils.ts

[RFR] Fix menu selection issue

---

cypress/integration/models/developer/applicationinventory/applicationinventory.ts

[RFR] Add cy.waitForReact() for accessing elements on Application inventory page

---

cypress/integration/tests/developer/applicationinventory/manageimports/csv.test.ts

The following changes have been made through this PR:
1)Update CSV template file name 
2)Assert the right string while reading the downloaded CSV template file

[RFR] Update test with correct file name and assert string

---

cypress/utils/utils.ts

Team is facing this issue of update password text appearing in UI . Fixed it .

[RFR] Fixed update password text issue

---

cypress/integration/models/developer/controls/stakeholdergroups.ts
cypress/integration/models/developer/controls/stakeholders.ts
cypress/integration/tests/developer/controls/stakeholdergroups/sort.test.ts
cypress/utils/utils.ts

modified:   cypress/integration/models/developer/controls/stakeholdergroups.ts
modified:   cypress/integration/models/developer/controls/stakeholders.ts
modified:   cypress/integration/tests/developer/controls/stakeholdergroups/filter.test.ts
modified:   cypress/integration/tests/developer/controls/stakeholdergroups/sort.test.ts

[RFR] Stakeholder groups Automation new fixes

---

cypress/integration/models/developer/controls/jobfunctions.ts
cypress/integration/models/developer/controls/stakeholders.ts
cypress/integration/tests/developer/controls/tags/tagtype/pagination.test.ts
cypress/utils/utils.ts

modified:   cypress/integration/models/developer/controls/jobfunctions.ts
modified:   cypress/integration/models/developer/controls/stakeholders.ts
modified:   cypress/integration/tests/developer/controls/tags/tagtype/pagination.test.ts

[RFR] Stakeholder test cases fixes

---

cypress/integration/models/administrator/credentials/credentials.ts
cypress/integration/models/administrator/credentials/credentialsSourceControl.ts
cypress/integration/models/administrator/credentials/credentialsSourceControlKey.ts
cypress/integration/models/administrator/credentials/credentialsSourceControlUsername.ts
cypress/integration/tests/administrator/credentials/proxy_crud.test.ts
cypress/integration/tests/administrator/credentials/sourcecontrol_crud.test.ts
cypress/integration/types/constants.ts
cypress/integration/types/types.ts
cypress/integration/views/credentials.view.ts
cypress/utils/data_utils.ts
cypress/utils/utils.ts

[RFR] Adding tests for various operations with credentials

---

cypress/integration/tests/developer/applicationinventory/analysis/source_analysis.test.ts
cypress/integration/tests/developer/applicationinventory/assessment/create.test.ts

[RFR] Replace clickApplicationInventory method calls

---

cypress/integration/models/developer/controls/businessservices.ts
cypress/integration/models/developer/controls/jobfunctions.ts
cypress/integration/models/developer/controls/stakeholdergroups.ts
cypress/integration/models/developer/controls/stakeholders.ts
cypress/integration/models/developer/controls/tags.ts
cypress/integration/tests/developer/controls/businessservices/interlinked.test.ts
cypress/integration/types/constants.ts

modified:   cypress/integration/models/developer/controls/businessservices.ts
modified:   cypress/integration/models/developer/controls/jobfunctions.ts
modified:   cypress/integration/models/developer/controls/stakeholdergroups.ts
modified:   cypress/integration/models/developer/controls/stakeholders.ts
modified:   cypress/integration/models/developer/controls/tags.ts
modified:   cypress/integration/tests/developer/controls/businessservices/interlinked.test.ts
modified:   cypress/integration/types/constants.ts

[RFR] Fixes for Business servces and job function test cases

---

cypress/integration/tests/developer/reports/appsrisk.test.ts

modified:   cypress/integration/tests/developer/reports/appsrisk.test.ts

[RFR] Appsrisk test of reports Automation fix

---

cypress/integration/models/administrator/proxy/proxy.ts
cypress/integration/tests/administrator/proxy/proxy.enable.disable.test.ts
cypress/integration/types/types.ts
cypress/utils/data_utils.ts
cypress/utils/utils.ts

Implemented proxy infra, proxy test. Added little fix for deletion action of credentials to align with 2.1 changes

[RFR] Proxy functionality

---

cypress/fixtures/app_import/xml/settings.xml
cypress/integration/models/administrator/credentials/credentialsMaven.ts
cypress/integration/tests/administrator/credentials/maven_crud.test.ts
cypress/integration/types/types.ts
cypress/utils/data_utils.ts

Updated infra for maven credentials type as it was done for others

[RFR] Added tests for maven credentials type.

---

.gitignore
cypress/integration/models/administrator/credentials/credentials.ts
cypress/integration/tests/administrator/credentials/pagination.test.ts
cypress/integration/tests/developer/controls/tags/tagtype/pagination.test.ts
cypress/utils/utils.ts
tsconfig.json

[RFR] Added pagination test for credentials

---

cypress/integration/models/administrator/credentials/credentials.ts
cypress/integration/models/developer/controls/businessservices.ts
cypress/integration/models/developer/controls/jobfunctions.ts
cypress/integration/tests/developer/controls/businessservices/crud.test.ts
cypress/integration/tests/developer/controls/businessservices/filter.test.ts
cypress/integration/tests/developer/controls/jobfunctions/filter.test.ts
cypress/integration/tests/developer/controls/jobfunctions/pagination.test.ts
cypress/integration/tests/developer/controls/jobfunctions/sort.test.ts
cypress/integration/tests/developer/controls/stakeholders/crud.test.ts
cypress/integration/tests/developer/controls/stakeholders/filter.test.ts
cypress/integration/tests/developer/controls/stakeholders/sort.test.ts
cypress/utils/utils.ts

* Business services
* Jov functions
* Stakeholders
Also did some little changes in utils

[RFR] Added fixes for tests

---

cypress/integration/tests/developer/reports/filter.test.ts
cypress/integration/views/reports.view.ts
cypress/utils/utils.ts

modified:   cypress/integration/tests/developer/reports/filter.test.ts

[RFR] Automation fixes for report's Filter tests

---

cypress/integration/models/developer/controls/businessservices.ts
cypress/integration/tests/developer/controls/businessservices/pagination.test.ts
cypress/integration/views/businessservices.view.ts
cypress/utils/utils.ts

[RFR] Fixing pagination test for Business Services

---

cypress/integration/models/administrator/credentials/credentials.ts
cypress/integration/models/administrator/credentials/credentialsProxy.ts
cypress/integration/models/administrator/credentials/credentialsSourceControlKey.ts
cypress/integration/tests/administrator/credentials/proxy_crud.test.ts
cypress/integration/tests/administrator/credentials/sourcecontrol_crud.test.ts
cypress/integration/tests/developer/controls/businessservices/pagination.test.ts
cypress/utils/data_utils.ts
cypress/utils/utils.ts
package-lock.json
package.json

[RFR] Tests for canceled credentials CRUD operations

---

cypress/utils/utils.ts

Now `goToPage()` and `goToLastPage()` functions will not fail if there is only one page

[RFR] Fix for goToPage() function

---

cypress/integration/models/developer/controls/businessservices.ts

[RFR] Fixed getList method to exclude header cell from names list

---

cypress/integration/models/administrator/credentials/credentialsProxy.ts
cypress/integration/models/administrator/credentials/credentialsSourceControlKey.ts
cypress/integration/models/administrator/credentials/credentialsSourceControlUsername.ts
cypress/integration/tests/administrator/credentials/proxy_crud.test.ts
cypress/integration/tests/administrator/credentials/sourcecontrol_crud.test.ts
cypress/utils/data_utils.ts

Now editing and canceling without saving changes works fine

[RFR] Fixed credentials crud tests

---

reportconfig.json

The jenkins job is using reportconfig.json and maximun of the test cases are failing to detect the elements due to hidden locators because of the window size.	
modified:   reportconfig.json

[RFR] Updating reportConfig.json file for jenkins fixes

---

cypress/integration/models/developer/applicationinventory/applicationinventory.ts
cypress/integration/tests/developer/reports/pagination.test.ts

modified:   cypress/integration/tests/developer/reports/pagination.test.ts

[RFR] Reports Pagination Test case Automation fixes

---

cypress/integration/tests/administrator/credentials/pagination.test.ts
cypress/utils/utils.ts

[RFR] Fix for credential pagination test

---

cypress/integration/models/developer/applicationinventory/application.ts
cypress/integration/views/applicationinventory.view.ts
cypress/utils/utils.ts

RFR] Fix application delete method

---

cypress/fixtures/app_import/csv/template_application_import.csv
cypress/integration/tests/developer/applicationinventory/assessment/import.test.ts
cypress/utils/utils.ts

Note : Only the first two tests pass. The last 5 tests fail because there is a change in the behavior between Tackle 1.2 and Tackle 2.x. I'm in discussion with stakeholders about this change. I'll address the 5 failures in a follow up PR once I have a better understanding of the behavior in Tackle 2.x.

[RFR] Provide 2.0 import template file

---

cypress/integration/tests/administrator/credentials/filter.test.ts
cypress/integration/tests/administrator/credentials/pagination.test.ts
cypress/utils/utils.ts

[RFR] Filtering test for credentials

---

cypress/integration/tests/developer/controls/tags/tagtype/sort.test.ts

modified:   cypress/integration/tests/developer/controls/tags/tagtype/sort.test.ts

[RFR] Automation fixes for Sort test case of TagType

---

cypress.json
reportconfig.json

[RFR] Changed reporter json to fix running Jenkins Job

---

package-lock.json
package.json

[RFR] Installed cypress-mochawesome-reporter

---

cypress/integration/tests/developer/applicationinventory/assessment/sort.test.ts

[RFR] Fix navigation in Application inventory sort tests

---

cypress.json
cypress/integration/models/administrator/credentials/credentials.ts
cypress/integration/tests/administrator/credentials/filter.test.ts
cypress/utils/utils.ts
reportconfig.json

[RFR] Adding credentials filtering by type

---

README.md

Adding a link to Konveyor's CoC

Add a link to Konveyor's CoC

---

cypress/integration/tests/developer/applicationinventory/assessment/pagination.test.ts

modified:   cypress/integration/tests/developer/applicationinventory/assessment/pagination.test.ts

[RFR] Autoamtion fixes for Assesment's Pagination Test case

---

cypress/utils/utils.ts

[RFR] Automation fix for import's CSV Test case

---

cypress/integration/models/developer/controls/businessservices.ts

Just added '/' that was missing, now it works fine

[RFR] Fix for BS navigation

---

cypress/integration/tests/developer/applicationinventory/manageimports/sort.test.ts

modified:   cypress/integration/tests/developer/applicationinventory/manageimports/sort.test.ts

[RFR] Automation Fixes for Manage Import's Sort Test case

---

cypress/integration/tests/developer/applicationinventory/manageimports/pagination.test.ts

Pagination test case automation fixes

---

cypress/integration/tests/developer/applicationinventory/assessment/filter.test.ts
cypress/utils/utils.ts

modified:   cypress/integration/tests/developer/applicationinventory/assessment/filter.test.ts

[RFR] Automation fixes for Assessment's Filter test case

---

cypress.json
cypress/fixtures/xml/settings.xml
cypress/integration/tests/developer/applicationinventory/analysis/binary_analysis.test.ts
cypress/integration/tests/developer/applicationinventory/analysis/source_analysis.test.ts
cypress/integration/types/constants.ts
cypress/utils/data_utils.ts
cypress/utils/utils.ts

[RFR] Fixed analysis tests

---

cypress/integration/models/developer/applicationinventory/assessment.ts
cypress/integration/tests/developer/applicationinventory/assessment/copy_assessment/pagination.test.ts
cypress/integration/views/applicationinventory.view.ts

[RFR] Fix Copy assessment pagination

---

cypress/integration/tests/developer/applicationinventory/manageimports/pagination.test.ts
cypress/utils/utils.ts

Manage Import test cases fixes

---

cypress/integration/tests/developer/controls/businessservices/pagination.test.ts
cypress/utils/utils.ts

Business sevices pagination test case fix

---

cypress/integration/tests/developer/applicationinventory/assessment/copy_assessment/filter.test.ts
cypress/utils/utils.ts

[RFR] Fix filter tests for copy assessment page

---

cypress/integration/tests/developer/applicationinventory/assessment/copy_assessment/copy_assessment.test.ts

[RFR] Copy assessment select options validations

---

cypress/integration/tests/developer/controls/businessservices/sort.test.ts

[RFR] Before cleanup for Business services's sorting test
modified:   cypress/integration/tests/developer/controls/businessservices/sort.test.ts

[RFR] Before cleanup for Business services's sorting test

---

cypress/utils/utils.ts

[RFR] Fix proxy tests

---

cypress/integration/tests/developer/controls/businessservices/pagination.test.ts

[RFR] Business service’s Pagination test case fixes

---

cypress/utils/utils.ts

[RFR] Increase timeout while waiting on table data cell elements to appear

---

cypress/fixtures/analysis.json
cypress/integration/models/developer/applicationinventory/analysis.ts
cypress/integration/tests/developer/applicationinventory/analysis/binary_analysis.test.ts
cypress/integration/tests/developer/applicationinventory/analysis/source_analysis.test.ts
cypress/integration/tests/developer/applicationinventory/analysis/upload_binary_analysis.test.ts
cypress/integration/types/types.ts
cypress/integration/views/analysis.view.ts
cypress/utils/utils.ts

[RFR] Automated report story points validation

---

cypress/fixtures/analysis.json
cypress/integration/models/developer/applicationinventory/analysis.ts
cypress/integration/tests/developer/applicationinventory/analysis/upload_binary_analysis.test.ts
cypress/integration/views/analysis.view.ts
cypress/utils/utils.ts

[RFR]Automated DIVA report

---

cypress/integration/tests/administrator/credentials/pagination.test.ts
cypress/utils/utils.ts

[RFR] Jenkins failure fix

---

cypress/integration/tests/developer/applicationinventory/assessment/interlinked.test.ts

modified:   cypress/integration/tests/developer/applicationinventory/assessment/interlinked.test.ts

[RFR] Assessment's Interlinked test case fixes

---

cypress/integration/tests/developer/applicationinventory/assessment/copy_assessment/filter.test.ts

[RFR] Automation fix for copy assessment's filter test case

---

cypress/integration/tests/administrator/credentials/sourcecontrol_crud.test.ts
cypress/utils/data_utils.ts

[RFR] Jenkins failure fix cred method

---

cypress/integration/tests/developer/applicationinventory/assessment/import.test.ts
cypress/utils/utils.ts

Automation fix for Login and Import test case of Assessment's

---

.github/workflows/pull-requests.yaml
cypress/utils/utils.ts

[RFR] New password updated

---

cypress/integration/models/keycloak/users/user.ts
cypress/integration/tests/keycloak/create.test.ts

Added setting up password method for keycloak user

---

.github/workflows/pull-requests.yaml
cypress/integration/models/keycloak/users/user.ts

Added to CI fix for keycloak admin pass

---

cypress/integration/models/keycloak/users/user.ts
cypress/integration/tests/keycloak/create.test.ts
cypress/integration/types/constants.ts
cypress/integration/types/types.ts

[RFR] Adding and removing roles to users in keycloak

---

cypress/utils/utils.ts

[RFR] Update title locator for Application Inventory page

---

.github/workflows/pull-requests.yaml

[RFR] Removed quote from the wrong place

---

cypress/integration/tests/developer/applicationinventory/assessment/dependency.test.ts
cypress/integration/views/applicationinventory.view.ts

[RFR] Update cyclic dependency test

---

cypress/integration/tests/developer/applicationinventory/assessment/filter.test.ts
cypress/integration/types/constants.ts
cypress/utils/utils.ts

[RFR] Credential Type filter validation Test case

---

cypress/integration/models/developer/applicationinventory/assessment.ts
cypress/integration/tests/developer/applicationinventory/assessment/copy_assessment/copy_assessment.test.ts

Discard assessment 

---

cypress/integration/tests/developer/controls/stakeholders/pagination.test.ts
cypress/integration/views/common.view.ts

modified:   cypress/integration/tests/developer/controls/stakeholders/pagination.test.ts

[RFR]Stakeholder's Pagination test case Jenkins fixes

---

cypress/integration/models/keycloak/users/user.ts
cypress/integration/tests/keycloak/rbac.architect.test.ts
cypress/integration/tests/keycloak/rbac.migrator.test.ts
cypress/integration/types/constants.ts
cypress/utils/utils.ts

[RFR] More tests for RBAC

---

cypress/integration/models/developer/applicationinventory/application.ts
cypress/integration/views/applicationinventory.view.ts

[RFR] Select Repo Type

---

.github/workflows/pull-requests.yaml

Forgot to add `$` sign before var name, now it is fixed

[RFR] CI fix

---

cypress/integration/models/developer/applicationinventory/assessment.ts
cypress/integration/tests/developer/applicationinventory/assessment/assess_review.test.ts
cypress/integration/tests/developer/applicationinventory/assessment/copy_assessment/copy_assessment.test.ts
cypress/integration/tests/developer/applicationinventory/assessment/copy_assessment/filter.test.ts
cypress/integration/tests/developer/applicationinventory/assessment/copy_assessment/pagination.test.ts
cypress/integration/tests/developer/applicationinventory/assessment/copy_assessment/sort.test.ts
cypress/integration/tests/developer/applicationinventory/assessment/interlinked.test.ts
cypress/integration/tests/developer/reports/appsrisk.test.ts
cypress/integration/tests/developer/reports/filter.test.ts
cypress/integration/tests/developer/reports/pagination.test.ts
cypress/integration/tests/developer/reports/sort.test.ts
cypress/utils/utils.ts

[RFR] Copy assessment, review and discard assessment, review

---

cypress/integration/models/administrator/credentials/credentialsSourceControlUsername.ts
cypress/integration/tests/rbac/architect.test.ts
cypress/integration/tests/rbac/migrator.test.ts
cypress/utils/utils.ts

[RFR] RBAC - Added infra for validations of analysis functionality

---

cypress/integration/models/administrator/proxy/proxy.ts
cypress/integration/tests/administrator/proxy/proxy.enable.disable.test.ts
cypress/integration/views/proxy.view.ts

Add long proxy hostname validation and update proxy tests code
@sshveta @ibragins Could you please review this pr?

[RFR] Add long proxy hostname validation and update proxy tests code

---

cypress/integration/models/administrator/proxy/proxy.ts
cypress/integration/tests/administrator/proxy/proxy.enable.disable.test.ts
cypress/integration/tests/developer/applicationinventory/analysis/binary_analysis.test.ts
cypress/integration/tests/developer/applicationinventory/analysis/source_analysis.test.ts
cypress/integration/tests/developer/applicationinventory/analysis/upload_binary_analysis.test.ts
cypress/utils/utils.ts

Update proxy references and add test to disable proxy with empty fields which fails right now.

[RFR] Update proxy references and add test to disable proxy with empty fields

---

cypress/integration/models/developer/applicationinventory/analysis.ts
cypress/integration/models/developer/applicationinventory/application.ts
cypress/integration/models/keycloak/users/user.ts
cypress/integration/tests/rbac/architect.test.ts
cypress/integration/tests/rbac/migrator.test.ts
cypress/integration/types/types.ts
cypress/utils/utils.ts

[RFR]: RBAC app analysis validations

---

cypress/integration/models/administrator/credentials/credentials.ts
cypress/integration/tests/administrator/credentials/field_validation.test.ts
cypress/utils/utils.ts

[RFR] Added credentials validation for too short name

---

cypress/integration/models/administrator/credentials/credentialsSourceControlUsername.ts
cypress/integration/models/developer/applicationinventory/analysis.ts
cypress/integration/tests/administrator/repository/git.test.ts
cypress/integration/tests/administrator/repository/subversion.test.ts

- updated username/password locators when creating new credentials

fixed the issue of opening reports for failing TC's

---

cypress/integration/tests/developer/applicationinventory/assessment/create.test.ts
cypress/integration/types/constants.ts
cypress/utils/utils.ts

1) Bulk deletion of applications by selecting 'Select Page'
2) Bulk deletion of applications by selecting 'Select all' 
The PR passed locally on upstream .

[RFR] Bulk deletion of applications

---

cypress/fixtures/analysis.json
cypress/integration/models/developer/applicationinventory/reportPage.ts
cypress/integration/tests/reports/filter.tests.ts
cypress/integration/views/reportPage.view.ts

[RFR] Name and Tag filter validation test cases for Report page
modified:   cypress/integration/tests/reports/filter.tests.ts
modified:   cypress/integration/views/analysis.view.ts

[RFR] Name and Tag filter validation test cases for Report page

---

cypress/integration/tests/developer/applicationinventory/assessment/create.test.ts
cypress/utils/utils.ts

[RFR] Update deleteApplicationTableRows()

---

cypress/integration/models/developer/applicationinventory/analysis.ts

modified:   cypress/integration/models/administrator/credentials/credentialsMaven.ts
modified:   cypress/integration/models/administrator/credentials/credentialsSourceControlKey.ts

[RFR] Upstream automation fixes for Analysis test cases

---

cypress/integration/models/developer/applicationinventory/analysis.ts
cypress/integration/models/developer/applicationinventory/application.ts
cypress/integration/tests/rbac/architect.test.ts
cypress/integration/tests/rbac/migrator.test.ts
cypress/integration/types/types.ts

[RFR] Adding changes to support assessment actions

---

cypress/integration/models/developer/applicationinventory/application.ts
cypress/integration/tests/rbac/architect.test.ts
cypress/integration/tests/rbac/migrator.test.ts

Added selecting 100 items per page for applications 
Added `Tier1` tag for RBAC tests

[RFR] Fixed RBAC tests for Jenkins Job

---

cypress/integration/models/administrator/credentials/credentials.ts
cypress/integration/tests/administrator/credentials/filter.test.ts
cypress/integration/views/credentials.view.ts
cypress/utils/utils.ts

[RFR] Implemented credentials filtering by type

---

cypress/integration/tests/developer/controls/tags/tag/filter.test.ts
cypress/utils/utils.ts

modified:   cypress/integration/tests/developer/controls/tags/tag/filter.test.ts

[RFR] Upstream Fixes for Tag's Filter test case

---

cypress/integration/tests/administrator/repository/git.test.ts
cypress/integration/tests/administrator/repository/subversion.test.ts

Fixes git and subversion tests by clearing the state after all test are finished
**Note:** Both tests pass locally but fail on github-actions because there are no git credentials configured

[RFR] Fix vcs tests for upstream

---

cypress/integration/models/developer/applicationinventory/application.ts
cypress/integration/tests/rbac/architect.test.ts
cypress/integration/tests/rbac/migrator.test.ts

[RFR] RBAC - Added validation availability of binary upload

---

cypress/integration/models/developer/applicationinventory/assessment.ts
cypress/integration/tests/developer/applicationinventory/assessment/assess_review.test.ts

Fixes the assess review test by solving an issue when typing into the +/- number inputs

[RFR] Fix assess_review test for upstream

---

cypress/integration/tests/administrator/credentials/sourcecontrol_crud.test.ts
cypress/integration/tests/administrator/proxy/proxy.enable.disable.test.ts
cypress/integration/tests/developer/applicationinventory/analysis/excludePackages.test.ts
cypress/integration/tests/developer/applicationinventory/reports/filter.tests.ts
cypress/integration/tests/developer/applicationinventory/reports/sort.test.ts
cypress/integration/tests/developer/controls/tags/tag/filter.test.ts

Added tier tag to tests to prevent non-tier1 tests from running on nighly job.

[RFR] Add tags to test for ci cd

---

cypress/fixtures/analysis.json
cypress/fixtures/xml/javax-package-custom.windup.xml
cypress/integration/models/developer/applicationinventory/analysis.ts
cypress/integration/tests/developer/applicationinventory/analysis/excludeTags.test.ts
cypress/utils/utils.ts

Automation of https://polarion.engineering.redhat.com/polarion/redirect/project/MTAPathfinder/workitem?id=MTAP-265
Note: we have bug reported too https://issues.redhat.com/browse/TACKLE-906
new file:   cypress/fixtures/xml/javax-package-custom.windup.xml
new file:   cypress/integration/tests/developer/applicationinventory/analysis/excludeTags.test.ts

[RFR] Exclude tags Automation

---

cypress/integration/models/administrator/credentials/credentialsSourceControlUsername.ts
cypress/integration/models/administrator/repositories/maven.ts
cypress/integration/tests/administrator/repository/maven.test.ts
cypress/utils/data_utils.ts
cypress/utils/utils.ts

Maven repositry tc

---

cypress/integration/models/administrator/credentials/credentials.ts
cypress/integration/models/keycloak/users/userAdmin.ts
cypress/integration/tests/administrator/credentials/filter.test.ts
cypress/integration/views/credentials.view.ts

[RFR] Added test for filtering credentials by user who created them

---

cypress/integration/models/developer/applicationinventory/application.ts
cypress/integration/tests/rbac/architect.test.ts
cypress/integration/tests/rbac/migrator.test.ts
cypress/integration/types/constants.ts

[RFR] Added test to validate review application button

---

cypress/integration/tests/administrator/repository/maven.test.ts

added a comment on the maven test cases explaining why it neves fails

---

cypress/integration/tests/developer/applicationinventory/analysis/excludeTags.test.ts

modified:   cypress/integration/tests/developer/applicationinventory/analysis/excludeTags.test.ts

[RFR] Fix for Exclude Tags Test case

---

cypress/integration/tests/developer/applicationinventory/assessment/create.test.ts
cypress/utils/utils.ts

[RFR] Refactor kebab menu functions

---

cypress/utils/utils.ts

[RFR] Fixes for Import test case of Assessment

---

cypress/integration/models/administrator/credentials/credentials.ts
cypress/integration/tests/administrator/credentials/remove_creds_app.test.ts

[MTAP-220](https://polarion.engineering.redhat.com/polarion/#/project/MTAPathfinder/workitem?id=MTAP-220)

[RFR] Added test that removes credential used by an app

---

cypress/integration/models/developer/applicationinventory/analysis.ts
cypress/integration/tests/developer/applicationinventory/analysis/excludePackages.test.ts
cypress/integration/views/analysis.view.ts

**Note:** This test won't work on github actions because no git credentials are provided

[RFR] Fix exclude packages test for upstream

---

cypress/integration/tests/developer/applicationinventory/assessment/filter.test.ts

The after hook was trying to delete business services before deleting theirs associated applications.
**Note:** This test won't work on github actions because no git credentials are provided

[RFR] Fix assessment filter test for upstream

---

cypress/integration/tests/developer/controls/jobfunctions/create.test.ts
cypress/integration/tests/developer/controls/stakeholdergroups/create.test.ts
cypress/integration/tests/developer/controls/tags/tag/create.test.ts
cypress/integration/tests/developer/controls/tags/tagtype/create.test.ts
cypress/integration/types/constants.ts

Problem was in incorrect expected message that instance with this name already exists.

[RFR] Fix for multiple "create" tests

---

cypress/utils/utils.ts

fix for "Applications import" title not found

---

cypress/integration/models/administrator/credentials/credentials.ts
cypress/integration/views/credentials.view.ts

[RFR] Fix for 'delete credentials in use' test

---

cypress/integration/tests/developer/applicationinventory/assessment/import.test.ts
cypress/utils/utils.ts

modified:   cypress/integration/tests/developer/applicationinventory/assessment/import.test.ts

[RFR] Report test cases fix

---

cypress/integration/tests/administrator/credentials/maven_crud.test.ts

[WIP] Added test running analysis with associated maven creds

---

cypress/integration/tests/developer/applicationinventory/assessment/pagination.test.ts
cypress/utils/utils.ts

[RFR] Fix assessment pagination test

---

cypress/integration/models/developer/applicationinventory/assessment.ts
cypress/integration/models/keycloak/users/user.ts
cypress/integration/tests/rbac/upload_binary_analysis_architect.test.ts
cypress/integration/tests/rbac/upload_binary_analysis_migrator.test.ts
cypress/integration/types/constants.ts
cypress/utils/utils.ts

[RFR] Added tests to run bynary analysis as Migrator and Architect

---

cypress/integration/tests/administrator/credentials/remove_creds_app.test.ts

`cypress/integration/tests/administrator/credentials/remove_creds_app.test.ts`  Was missing the tier1 tag in the after hook.

[RFR] Tag tier 1 test

---

cypress/integration/models/administrator/repositories/maven.ts

Signed off by midays@redhat.com

[RFR] check if clear repo button is disabled before moving with the test

---

cypress/integration/types/constants.ts

[RFR] Fix create tag test

---

cypress/integration/tests/developer/applicationinventory/analysis/excludeTags.test.ts

modified:   cypress/integration/tests/developer/applicationinventory/analysis/excludeTags.test.ts

[RFR] Uncomment the exclude tag's validation

---

cypress/integration/tests/developer/applicationinventory/analysis/binary_analysis.test.ts
cypress/integration/tests/developer/applicationinventory/analysis/source_analysis.test.ts
cypress/integration/tests/developer/applicationinventory/analysis/upload_binary_analysis.test.ts

[RFR] Remove tier 4

---

cypress/integration/views/applicationinventory.view.ts
cypress/utils/utils.ts

1)Update copy locator on copy assessment page
2)Increased timeout in checkSuccessAlert() utility function

[RFR] Update copy locator on copy assessment page

---

cypress/fixtures/analysis.json
cypress/integration/models/developer/applicationinventory/analysis.ts
cypress/integration/tests/developer/applicationinventory/assessment/import.test.ts
cypress/utils/utils.ts

[RFR] Automation fixes for upload binary and assessment's import test cases

---

cypress/integration/models/developer/applicationinventory/assessment.ts
cypress/integration/tests/developer/reports/appsrisk.test.ts
cypress/integration/tests/developer/reports/filter.test.ts
cypress/integration/tests/developer/reports/pagination.test.ts
cypress/integration/tests/developer/reports/sort.test.ts

modified:   cypress/integration/models/developer/applicationinventory/assessment.ts
modified:   cypress/integration/tests/developer/reports/appsrisk.test.ts
modified:   cypress/integration/tests/developer/reports/filter.test.ts
modified:   cypress/integration/tests/developer/reports/pagination.test.ts
modified:   cypress/integration/tests/developer/reports/sort.test.ts

[RFR] Automation Fixes for report's Test cases

---

cypress.json
cypress/fixtures/upgrade-data.json
cypress/integration/models/administrator/credentials/credentialsSourceControlUsername.ts
cypress/integration/models/developer/applicationinventory/analysis.ts
cypress/integration/models/developer/applicationinventory/application.ts
cypress/integration/models/developer/applicationinventory/assessment.ts
cypress/integration/tests/developer/applicationinventory/analysis/binary_analysis.test.ts
cypress/integration/tests/developer/applicationinventory/analysis/source_analysis.test.ts
cypress/integration/tests/developer/applicationinventory/analysis/upload_binary_analysis.test.ts
cypress/integration/tests/upgrade/create_test_data.ts
cypress/integration/types/types.ts
cypress/utils/utils.ts

[RFR] Automation for creating prerequisites for an upgrade

---

cypress/integration/tests/developer/applicationinventory/manageimports/filter.test.ts

Fixed jenkins failure for filter.test.ts
Signed by :sshveta@redhat.com

[RFR] Fix filter jenkins failure

---

cypress/integration/tests/developer/applicationinventory/assessment/assessment_after_import.ts
cypress/integration/types/types.ts
cypress/utils/utils.ts

1) Add coverage for performing an assessment and review of an application after importing it.
https://polarion.engineering.redhat.com/polarion/redirect/project/MTAPathfinder/workitem?id=MTA-294 
2) Updated getRandomApplicationData() function to handle application names that are not appended with a suffix.

[RFR] Perform assessment and review after importing an application

---

cypress/integration/enums/analysisStatuses.enum.ts
cypress/integration/models/developer/applicationinventory/analysis.ts
cypress/integration/types/constants.ts

Moved AnalysisStatuses enum to constants file as requrested by Igor to aim for consistency
@sshveta @ibragins Could you review this PR please?
Thanks

[RFR] move analysis statuses enum to constants file

---

cypress/integration/tests/developer/applicationinventory/assessment/assessment_after_import.ts
cypress/integration/types/types.ts
cypress/utils/utils.ts

[RFR]Reverting PR 357

---

cypress/fixtures/upgrade-data.json
cypress/integration/models/administrator/credentials/credentials.ts
cypress/integration/models/developer/applicationinventory/application.ts
cypress/integration/models/developer/controls/stakeholdergroups.ts
cypress/integration/tests/upgrade/after_upgrade.test.ts
cypress/integration/tests/upgrade/create_test_data.ts
cypress/integration/types/types.ts
cypress/utils/utils.ts

[RFR] Upgrade validations

---

cypress/utils/utils.ts

[RFR] Infra for validating RWX settings

---

cypress/integration/models/developer/applicationinventory/assessment.ts

[RFR] Increase timeout while waiting on assessment to complete

---

cypress/integration/models/developer/applicationinventory/analysis.ts
cypress/integration/models/developer/applicationinventory/application.ts

Fixes analysis tests for upstream

[RFR] Fix analysis tests for upstream

---

cypress/integration/tests/login.test.ts

[RFR] Fix login test

---

cypress/integration/tests/upgrade/after_upgrade.test.ts
cypress/integration/tests/upgrade/create_test_data.ts
cypress/utils/utils.ts

1. Added validation if RWX is enabled or not (currently it will expect external parameter as a workaround)
2. Fixed credentials generation so now binary analysis will not fail
3. Added analysis status validation as now analysis shouldn't fail any more.

[RFR] After upgrade validation of RWX 

---

cypress/integration/tests/upgrade/create_test_data.ts

Fixed credentials creation 
Added validation that analysis didn't fail

[RFR] Fixed credentials for application analysis

---

cypress/integration/tests/upgrade/after_upgrade.test.ts

[RFR] Updated post-upgrade tags

---

cypress/fixtures/upgrade-data.json

[RFR] Updated upgrade-data.json with app name fields

---

cypress/integration/models/developer/controls/businessservices.ts
cypress/integration/tests/developer/applicationinventory/manageimports/sort.test.ts

Fixes the `cypress/integration/models/developer/controls/businessservices.ts` test.

[RFR] Fix manageimports sort test

---

cypress/fixtures/analysis.json
cypress/integration/models/developer/applicationinventory/analysis.ts
cypress/integration/tests/developer/applicationinventory/analysis/source_analysis.test.ts
cypress/integration/types/types.ts
cypress/utils/utils.ts

modified:   cypress/integration/tests/developer/applicationinventory/analysis/source_analysis.test.ts
modified:   cypress/integration/types/types.ts

[RFR] Analyze known open source libraries

---

cypress/integration/models/developer/reports/reportConfig.ts
cypress/integration/tests/developer/reports/download_report.test.ts
cypress/integration/types/constants.ts
cypress/integration/views/reports.view.ts
cypress/utils/utils.ts

Added automation to configure reports
Added singleton class ConfigReports so that single class instance can be retrieved from any place of the code and kept configuration values there.

[RFR] Added configuration for the reports

---

cypress/integration/models/developer/applicationinventory/application.ts
cypress/integration/tests/developer/applicationinventory/assessment/interlinked.test.ts
cypress/integration/views/applicationinventory.view.ts

1) Added new application methods for application details page
2) Removed unused applications methods

[RFR] Add methods for application details page

---

cypress/integration/models/administrator/repositories/git.ts
cypress/integration/models/administrator/repositories/maven.ts
cypress/integration/models/administrator/repositories/subversion.ts
cypress/integration/views/repository.view.ts
cypress/utils/utils.ts

Signed-off by midays@redhat.com

Updated tests to use enableSwitch/ disableSwitch functions

---

cypress/fixtures/analysis.json

[RFR] Fix Story point of known libraries test case

---

cypress/utils/utils.ts

Changed a 200h timeout for a 2 minutes one.
Hi @ibragins @sshveta  could you review this PR please?

[RFR] Remove long timeout

---

cypress/integration/tests/upgrade/after_upgrade.test.ts
cypress/utils/utils.ts

Refactored patching tackle CR
Added timeout and control that pods should reconcile after changing value in CR

[RFR] Improving post-upgrade tests

---

cypress/integration/models/developer/applicationinventory/analysis.ts
cypress/integration/tests/developer/controls/jobfunctions/pagination.test.ts
cypress/integration/tests/developer/controls/stakeholdergroups/crud.test.ts
cypress/integration/tests/developer/controls/stakeholdergroups/filter.test.ts
cypress/integration/tests/developer/controls/stakeholders/sort.test.ts
cypress/integration/views/common.view.ts
cypress/utils/data_utils.ts
cypress/utils/utils.ts

modified:   cypress/integration/tests/developer/controls/jobfunctions/pagination.test.ts
modified:   cypress/integration/tests/developer/controls/stakeholdergroups/crud.test.ts
modified:   cypress/integration/tests/developer/controls/stakeholdergroups/filter.test.ts
modified:   cypress/integration/tests/developer/controls/stakeholders/sort.test.ts
modified:   cypress/integration/views/common.view.ts
modified:   cypress/utils/data_utils.ts

[RFR] fixes for mta_6.0.2 Jenkins failures

---

cypress/integration/models/developer/applicationinventory/analysis.ts
cypress/integration/tests/developer/applicationinventory/reports/filter.test.ts

This requires that multiple applications/dependencies be listed on the analysis report page. 
So, the code has been updated to perform source+deps analysis instead of binary analysis.

[RFR] Fix analysis report filter issues

---

cypress/integration/tests/developer/applicationinventory/reports/filter.test.ts

modified:   cypress/integration/tests/developer/applicationinventory/reports/filter.test.ts

[RFR] report pages filter fix

---

cypress/integration/tests/developer/applicationinventory/manageimports/pagination.test.ts
cypress/integration/tests/developer/applicationinventory/manageimports/sort.test.ts

[RFR] Delete Business services through before() hook

---

cypress/integration/models/developer/applicationinventory/analysis.ts
cypress/integration/tests/developer/applicationinventory/reports/sort.test.ts

[RFR] Fix for broken analysis test cases

---

cypress/integration/tests/developer/applicationinventory/manageimports/pagination.test.ts
cypress/integration/tests/developer/applicationinventory/manageimports/sort.test.ts

[RFR]  Delete business services through before() hook

---

cypress/integration/tests/administrator/repository/maven.test.ts

Test is covering disabling RWX and validating that Maven cache is disabled after that

[RFR] Added test covering bug MTA-311

---

cypress/integration/tests/upgrade/after_upgrade.test.ts

Cosmetic commit, no functional changes, just test title is updated

[RFR] Fixed title for the post-upgrade test

---

cypress/integration/tests/upgrade/after_upgrade.test.ts

Cosmetic commit, no functional changes, just test title and tag are updated

Fixed title for the post-upgrade test and post-upgrade tag

---

cypress/integration/tests/developer/controls/jobfunctions/pagination.test.ts

Fixed `cypress/integration/tests/developer/controls/jobfunctions/pagination.test.ts`
Also moved after hook to end of file to aim for consistency among suites

[RFR] Fix jobfunctions pagination test

---

cypress/integration/tests/developer/controls/stakeholdergroups/pagination.test.ts
cypress/integration/types/constants.ts

modified:   cypress/integration/types/constants.ts

[RFR] Controls automation fixes

---

cypress/integration/tests/developer/applicationinventory/assessment/interlinked.test.ts

modified:   cypress/integration/tests/developer/applicationinventory/assessment/interlinked.test.ts

[RFR] Fix for Skipped assessment's interlinked test

---

cypress/integration/tests/administrator/credentials/sourcecontrol_crud.test.ts
cypress/integration/tests/administrator/custom-migration-targets/crud.test.ts
cypress/integration/tests/developer/applicationinventory/assessment/assessment_after_import.test.ts
cypress/integration/tests/developer/applicationinventory/assessment/copy_assessment/filter.test.ts
cypress/integration/tests/developer/applicationinventory/assessment/copy_assessment/pagination.test.ts
cypress/integration/tests/developer/applicationinventory/assessment/copy_assessment/sort.test.ts
cypress/integration/tests/developer/applicationinventory/assessment/dependency.test.ts
cypress/integration/tests/developer/applicationinventory/assessment/import.test.ts
cypress/integration/tests/developer/applicationinventory/manageimports/csv.test.ts
cypress/integration/tests/developer/reports/appsrisk.test.ts

Fix skipped tests for assessment.
Disconnected cluster tier

[RFR] Disconnected cluster tier

---

cypress/integration/tests/developer/applicationinventory/assessment/filter.test.ts

[RFR] Update available artifact filters on Application inventory page

---

cypress/integration/tests/developer/applicationinventory/assessment/filter.test.ts

[RFR] Fix tag filter on application inventory page

---

cypress/integration/tests/upgrade/create_upgrade_data.test.ts

[RFR] Some little fixes to imporve scenario

---

cypress/integration/models/developer/applicationinventory/analysis.ts

[RFR] Commented checking success alert submitting analysis

---

cypress.json

Added rwx parameter to cypress.json

---

cypress/integration/tests/developer/applicationinventory/manageimports/pagination.test.ts

Business service creation is not required since missing entities get created by default while importing applications.

[RFR] Fix manage imports pagination

---

cypress/integration/tests/developer/applicationinventory/analysis/binary_analysis.test.ts
cypress/integration/tests/developer/applicationinventory/analysis/upload_binary_analysis.test.ts

Fixed failures in upload binary analysis and binary analysis

[RFR] Fixed some failures in analysis

---

cypress/integration/models/developer/applicationinventory/analysis.ts
cypress/integration/types/types.ts
cypress/integration/views/analysis.view.ts

Automated tagging of applications has been introduced in MTA 6.1 . I've added a method to enable the option during analysis if automated tagging needs to be enabled during an analysis .

[RFR] Add method for automated tagging

---

cypress/integration/tests/developer/applicationinventory/analysis/download_report.test.ts

modified:   cypress/integration/tests/developer/applicationinventory/analysis/download_report.test.ts

[RFR] Refactoring download_report test

---

cypress/integration/models/administrator/general/generalConfig.ts
cypress/integration/tests/developer/applicationinventory/analysis/binary_analysis.test.ts
cypress/integration/tests/developer/applicationinventory/analysis/upload_binary_analysis.test.ts

[RFR] Fixed ReportConfig to GeneralConfig renaming

---

cypress/integration/models/developer/applicationinventory/analysis.ts
cypress/integration/tests/rbac/custom-migration-target.test.ts

Automates Polarion TC 317.
Due to the nature of the tests, this PR won't pass on GitHub actions.
Successfully ran in Jenkins [24](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/24/console)
@sshveta Could you review this PR, please? Thanks

[RFR] Add custom migration target rbac tests

---

cypress/fixtures/analysis.json
cypress/fixtures/application.json
cypress/integration/tests/developer/applicationinventory/analysis/source_analysis.test.ts
cypress/utils/utils.ts

Automates  https://github.com/konveyor/example-applications/tree/main/example-1
This PR won't work on GitHub Actions due to the nature of this test.
Successfully executed in Jenkins [run 41](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/41/console)
@sshveta could yo review this PR please?

[RFR] Add konveyor example1 analysis test

---

package-lock.json
package.json
tsconfig.json

[RFR] Added plugin for documentation generation

---

cypress/integration/models/migration/applicationinventory/analysis.ts

Change displayed items to 100 every time an analysis operation is performed.
This won't affect pagination tests as they change the items per page to perform their assertions.
Thanks

[RFR] Force analysis to show 100 items

---

cypress/integration/tests/migration/applicationinventory/assessment/copy_assessment/copy_assessment.test.ts

[RFR] Fix copy assessment select option validations

---

cypress/integration/tests/administration/repository/maven.test.ts

[RFR] Fixed repository/maven test

---

cypress/integration/models/migration/applicationinventory/analysis.ts

Used closeApplicationDetail instead selectApplicationRow in downloadReport method

[RFR] Replace method in downloadReport

---

cypress/integration/tests/migration/applicationinventory/assessment/create.test.ts

Bulk deletion of apps by selecting bulk-selected-apps-checkbox

[RFR] Bulk deletion of apps by selecting bulk-selected-apps-checkbox-

---

cypress/integration/tests/rbac/custom-migration-target.test.ts

Automates Polarion [TC 319](https://polarion.engineering.redhat.com/polarion/#/project/MTAPathfinder/workitem?id=MTA-319)
Adds tests for analysis with custom migration targets.
These tests won't pass in Jenkins due to bug [MTA-458](https://issues.redhat.com/browse/MTA-458)
This suite won't pass in GitHub Actions due to the nature of the tests.

[RFR] Add tests for analysis with custom migration targets

---

cypress/fixtures/analysis.json
cypress/fixtures/application.json
cypress/integration/tests/administration/repository/git.test.ts
cypress/integration/tests/administration/repository/maven.test.ts
cypress/integration/tests/administration/repository/subversion.test.ts
cypress/integration/tests/migration/applicationinventory/analysis/additional_analysis.test.ts
cypress/integration/tests/migration/applicationinventory/analysis/binary_analysis.test.ts
cypress/integration/tests/migration/applicationinventory/analysis/download_report.test.ts
cypress/integration/tests/migration/applicationinventory/analysis/excludePackages.test.ts
cypress/integration/tests/migration/applicationinventory/analysis/excludeTags.test.ts
cypress/integration/tests/migration/applicationinventory/analysis/manuallyAnalyzePackages.test.ts
cypress/integration/tests/migration/applicationinventory/analysis/source_analysis.test.ts
cypress/integration/tests/migration/applicationinventory/analysis/upload_binary_analysis.test.ts
cypress/integration/tests/migration/applicationinventory/reports/filter.test.ts
cypress/integration/tests/migration/applicationinventory/reports/sort.test.ts
cypress/integration/tests/rbac/custom-migration-target.test.ts
cypress/integration/tests/rbac/upload_binary_analysis_architect.test.ts
cypress/integration/tests/rbac/upload_binary_analysis_migrator.test.ts

modified:   cypress/integration/tests/developer/applicationinventory/analysis/additional_analysis.test.ts
modified:   cypress/integration/tests/developer/applicationinventory/analysis/binary_analysis.test.ts
modified:   cypress/integration/tests/developer/applicationinventory/analysis/download_report.test.ts
modified:   cypress/integration/tests/developer/applicationinventory/analysis/excludePackages.test.ts
modified:   cypress/integration/tests/developer/applicationinventory/analysis/excludeTags.test.ts
modified:   cypress/integration/tests/developer/applicationinventory/analysis/manuallyAnalyzePackages.test.ts
modified:   cypress/integration/tests/developer/applicationinventory/analysis/sou …

[RFR] Reformat analysis.json for tackle-ui-tests

---

cypress/integration/models/administration/custom-migration-targets/custom-migration-target.ts
cypress/integration/tests/administration/custom-migration-targets/field_validation.test.ts
cypress/integration/views/custom-migration-target.view.ts

Added repository URL validation test for custom migration targets.
Automates [Polarion TC 328](https://polarion.engineering.redhat.com/polarion/#/project/MTAPathfinder/workitem?id=MTA-328)
This test will fail due to bug [484](https://issues.redhat.com/browse/MTA-484)

[RFR] Add repository url validation test for custom migration targets

---

cypress/integration/models/migration/controls/tagcategory.ts
cypress/integration/tests/migration/controls/tags/tag/filter.test.ts
cypress/integration/tests/migration/controls/tags/tagcategory/create.test.ts
cypress/integration/tests/migration/controls/tags/tagcategory/crud.test.ts
cypress/integration/tests/migration/controls/tags/tagcategory/filter.test.ts
cypress/integration/tests/migration/controls/tags/tagcategory/pagination.test.ts
cypress/integration/tests/migration/controls/tags/tagcategory/sort.test.ts
cypress/integration/tests/upgrade/after_upgrade.test.ts
cypress/integration/tests/upgrade/create_upgrade_data.test.ts
cypress/utils/utils.ts

renamed:    cypress/integration/models/migration/controls/tagtypes.ts -> cypress/integration/models/migration/controls/tagcategory.ts
modified:   cypress/integration/tests/migration/controls/tags/tag/filter.test.ts
renamed:    cypress/integration/tests/migration/controls/tags/tagtype/create.test.ts -> cypress/integration/tests/migration/controls/tags/tagcategory/create.test.ts
renamed:    cypress/integration/tests/migration/controls/tags/tagtype/crud.test.ts -> cypress/integration/tests/migration/controls/tags/tagcategory/crud.test.ts
renamed:    cypress/integration/tests/migration/controls/tags/tagtype/filter.test.ts -> cypress/integration/tests/migration/controls/tags/tagcategory/filter.test.ts
renamed: …

[RFR] Rename Tag Type to "Tag Category"

---

cypress/integration/tests/administration/repository/maven.test.ts

modified:   cypress/integration/tests/administration/repository/maven.test.ts

[RFR] Maven test fix

---

cypress/integration/models/administration/credentials/credentials.ts
cypress/integration/tests/migration/controls/tags/tagcategory/filter.test.ts
cypress/integration/types/constants.ts

Fixed credentials tests
Fixed filter test for tag category
Added some reference documentation to Credentials class

[RFR] Fixes for credentials tests

---

cypress/integration/tests/migration/applicationinventory/analysis/source_analysis.test.ts

Update analysis data structure names in source_analysis_test.ts

[RFR] Update analysis data structure names in source_analysis_test.ts

---

cypress/integration/types/constants.ts

Fixed failing credentials tests for 6.0.3

---

cypress/integration/tests/developer/applicationinventory/manageimports/filter.test.ts
cypress/integration/tests/developer/applicationinventory/manageimports/pagination.test.ts
cypress/integration/tests/developer/applicationinventory/manageimports/sort.test.ts

Starting with 6.0, missing entities including business services get created during application import . Hence, removing redundant code for business service creation .

[RFR] 6.0.3 - Fix manageimports/pagination and manageimports/sort

---

cypress/e2e/models/migration/applicationinventory/analysis.ts
cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
cypress/e2e/types/types.ts
cypress/fixtures/analysis.json
cypress/utils/utils.ts

Automate https://polarion.engineering.redhat.com/polarion/#/project/MTAPathfinder/workitem?id=MTA-307

[RFR] Add test for disabled automated tagging

---

cypress/integration/tests/developer/applicationinventory/analysis/excludeTags.test.ts

Skipping the only test in the suite because a bug won't be packported to 6.0.x.

[RFR] Skip test: Exclude Tags from report using source analysis

---

cypress/utils/utils.ts

Skip success alert check for application imports on 6.0.x

[RFR] Skip success alert check for application imports

---

cypress.config.ts
package-lock.json
package.json
tsconfig.json

After upgrading Cypress, plugins were not being imported, this PR brings back all plugins we were using, this PR should fix multiple tests.

[RFR] Bring plugins back

---

cypress/e2e/tests/administration/credentials/maven_crud.test.ts
cypress/utils/utils.ts

[RFR] Fixed all credentials tests

---

cypress/e2e/models/migration/applicationinventory/analysis.ts

This PR fixes the manually analyzed packages test by removing a duplicated block of code that was triggering an unexpected unique validation error.

[RFR] Fix manually analyzed packages test

---

cypress/utils/utils.ts

Changes included in this PR:
* Updated the `resetUrl` method to take into account also the analysis details tab.
* Refactored the `deleteAllBusinessServices` method to make it work with the last Cypress version.
Thanks to the chainable cypress calls, this new method is also 250% faster than the previous one.
*Note:* I'll keep thir PR as WIP until I test it in Jenkins.

[RFR] Fix business service deletion

---

cypress/e2e/tests/rbac/architect.test.ts
cypress/e2e/tests/rbac/migrator.test.ts
cypress/e2e/tests/rbac/review-assessment.test.ts
cypress/e2e/tests/rbac/upload_binary_analysis_architect.test.ts
cypress/e2e/tests/rbac/upload_binary_analysis_migrator.test.ts
cypress/utils/utils.ts

Reverted changes made to login function that was causing various tests to fail.

[RFR] Fix RBAC tests

---

cypress/e2e/tests/migration/controls/businessservices/pagination.test.ts
cypress/e2e/tests/migration/controls/businessservices/sort.test.ts
cypress/utils/utils.ts

[RFR] Cypress upgrade fixes for Control tests

---

cypress/e2e/tests/rbac/architect.test.ts
cypress/e2e/tests/rbac/custom-rules.test.ts
cypress/e2e/tests/rbac/migrator.test.ts
cypress/e2e/tests/rbac/review-assessment.test.ts
cypress/utils/utils.ts

[RFR] Fix Custom rules tests - failing due to reformating of json

---

cypress/e2e/tests/administration/custom-migration-targets/field_validation.test.ts

Last test of this suite is expected to fail due to bug [484](https://issues.redhat.com/browse/MTA-484)

[RFR] Fix image validation test

---

cypress/e2e/views/common.view.ts
cypress/utils/utils.ts

[RFR] Fix for Report filter test case

---

cypress.config.ts
cypress/e2e/models/keycloak/users/user.ts
cypress/utils/utils.ts

[RFR] Login upgrade

---

cypress/e2e/tests/migration/applicationinventory/assessment/filter.test.ts

Notes : I will update the PR with the results from the Jenkins job shortly.

[RFR] Use the correct data for creating applications in Application inventory filter tests

---

cypress/e2e/tests/upgrade/after_upgrade.test.ts
cypress/e2e/tests/upgrade/create_upgrade_data.test.ts
cypress/utils/utils.ts

[RFR] Fix for pre-upgrade and post-upgrade scenarios

---

cypress/e2e/tests/rbac/architect.test.ts
cypress/e2e/tests/rbac/migrator.test.ts
cypress/fixtures/rbac.json

[RFR] Moved RBAC rules to fixture instead of hard code

---

cypress/e2e/tests/administration/credentials/sourcecontrol_crud.test.ts
cypress/e2e/tests/administration/custom-migration-targets/crud.test.ts
cypress/e2e/tests/migration/applicationinventory/analysis/upload_binary_analysis.test.ts
cypress/e2e/tests/migration/applicationinventory/assessment/assess_review.test.ts
cypress/e2e/tests/migration/controls/businessservices/crud.test.ts
cypress/e2e/tests/migration/controls/stakeholders/crud.test.ts

[RFR] Add interop tag for tests

---

cypress/e2e/tests/upgrade/after_upgrade.test.ts
cypress/e2e/tests/upgrade/create_upgrade_data.test.ts

[RFR] Mta 6.0.3 upgrade tag fixes

---

cypress/e2e/tests/migration/applicationinventory/assessment/assessment_after_import.test.ts
cypress/e2e/tests/migration/applicationinventory/assessment/import.test.ts
cypress/e2e/tests/migration/applicationinventory/assessment/interlinked.test.ts

These tests were being skipped on the Jenkins run. So, I'm updating the tags through this PR.

[RFR] Update tags of a few tests after Cypress upgrade

---

cypress/e2e/tests/migration/applicationinventory/assessment/create.test.ts
cypress/e2e/views/applicationinventory.view.ts

Automates Polarion [TC 331](https://polarion.engineering.redhat.com/polarion/#/project/MTAPathfinder/workitem?id=MTA-331).
Probably this test won't pass due to notification texts changes, but without that, it is working as expected.
@sshveta Could you take a look at this PR please? Thanks
@Neilhamza take a look and please tell me if you have any questions/concerns!

[RFR] Automate contributors field test

---

cypress.config.ts
cypress/e2e/models/administration/credentials/credentials.ts
cypress/e2e/models/administration/credentials/credentialsJira.ts
cypress/e2e/models/administration/credentials/credentialsProxy.ts
cypress/e2e/tests/administration/credentials/jira_crud.test.ts
cypress/e2e/tests/administration/credentials/proxy_crud.test.ts
cypress/e2e/types/constants.ts
cypress/e2e/types/types.ts
cypress/e2e/views/common.view.ts
cypress/e2e/views/general.view.ts
cypress/utils/data_utils.ts
cypress/utils/utils.ts

[RFR] Created required infra for Jira credentials and tests for it

---

cypress/e2e/models/keycloak/users/user.ts
cypress/e2e/tests/rbac/upload_binary_analysis_architect.test.ts
cypress/e2e/tests/rbac/upload_binary_analysis_migrator.test.ts

[RFR] Fixed leftovers for mta 6.0.3

---

cypress/e2e/models/migration/migration-waves/migration-wave.ts
cypress/e2e/tests/migration/migration-waves/crud.test.ts
cypress/e2e/types/constants.ts
cypress/e2e/views/migration-wave.view.ts
cypress/utils/utils.ts

Automates Polarion TC [332](https://polarion.engineering.redhat.com/polarion/#/project/MTAPathfinder/workitem?id=MTA-332)
This will fail due to bug MTA-753
Thanks!

[RFR] Automate migration waves crud

---

cypress/e2e/tests/rbac/custom-rules.test.ts

There were 3 tests failing due to known bug MTA-458, now those tests are skipped cause they will predictably fail. 
Some little refactoring was applied to compensate skipped tests.

[RFR] Fixed custom-rules failures

---

cypress/e2e/tests/migration/applicationinventory/assessment/create.test.ts
cypress/e2e/views/applicationinventory.view.ts
cypress/e2e/views/common.view.ts

Added a test for owner field when creating new application in application inventory

[RFR]Automate owner field test

---

cypress/e2e/models/administration/jira/jira.ts
cypress/e2e/types/types.ts
cypress/e2e/views/jira.view.ts
cypress/utils/utils.ts

[RFR] Jira connection instance infra

---

cypress.config.ts
cypress/e2e/models/migration/custom-metrics/custom-metrics.ts
cypress/e2e/tests/custom-metrics/assessment_metrics.test.ts

new file:   cypress/e2e/models/migration/custom-metrics/custom-metrics.ts

[RFR] Assessment metrics test case Infra

---

cypress.config.ts
cypress/e2e/models/administration/credentials/credentialsBasicJira.ts
cypress/e2e/models/administration/credentials/credentialsTokenJira.ts
cypress/e2e/models/administration/jira/jira.ts
cypress/e2e/tests/administration/credentials/jira_crud.test.ts
cypress/e2e/types/constants.ts
cypress/e2e/types/types.ts
cypress/utils/data_utils.ts

[RFR] Refactored Jira credential types to align with UI changes

---

cypress/e2e/models/migration/controls/businessservices.ts
cypress/e2e/models/migration/controls/stakeholdergroups.ts
cypress/e2e/models/migration/controls/stakeholders.ts
cypress/e2e/models/migration/controls/tagcategory.ts
cypress/e2e/models/migration/controls/tags.ts
cypress/e2e/models/migration/migration-waves/migration-wave.ts
cypress/e2e/tests/migration/migration-waves/crud.test.ts
cypress/e2e/types/constants.ts
cypress/e2e/views/common.view.ts
cypress/e2e/views/migration-wave.view.ts

This PR automates Polarion TC 333 and also adapts some of the new notification texts.
It won't pass in Jenkins because the application creation notification stills not ready.

[RFR] Automate migration waves application association

---

cypress/e2e/tests/migration/migration-waves/filter.test.ts
cypress/utils/utils.ts

Automating migration waves filter test
@sshveta @abrugaro can you please review this PR? thanks!

[RFR] Automating migration waves filter test

---

cypress/e2e/tests/migration/controls/businessservices/crud.test.ts
cypress/e2e/tests/migration/controls/businessservices/interlinked.test.ts
cypress/e2e/tests/migration/controls/stakeholdergroups/crud.test.ts
cypress/e2e/tests/migration/controls/stakeholdergroups/interlinked.test.ts
cypress/e2e/tests/migration/controls/stakeholders/interlinked.test.ts
cypress/e2e/views/businessservices.view.ts
cypress/e2e/views/stakeholdergroups.view.ts

modified:   cypress/e2e/tests/migration/controls/businessservices/crud.test.ts
modified:   cypress/e2e/tests/migration/controls/businessservices/interlinked.test.ts
modified:   cypress/e2e/tests/migration/controls/stakeholdergroups/crud.test.ts
modified:   cypress/e2e/tests/migration/controls/stakeholdergroups/interlinked.test.ts
modified:   cypress/e2e/tests/migration/controls/stakeholders/interlinked.test.ts
modified:   cypress/e2e/views/businessservices.view.ts
modified:   cypress/e2e/views/stakeholdergroups.view.ts

[RFR] New selectors adaptaion in Controls test cases

---

cypress.config.ts
cypress/e2e/models/administration/jira/jira.ts
cypress/e2e/tests/administration/credentials/jira_crud.test.ts
cypress/e2e/tests/administration/jira-connection/jira_connection_test.ts
cypress/e2e/types/constants.ts
cypress/e2e/views/jira.view.ts
cypress/utils/utils.ts

[RFR] Jira connection tests

---

cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts

Added some minor fixes for credential selections in source_analysis suite.

[RFR] Fixes for credentials selection

---

cypress/e2e/tests/rbac/architect.test.ts
cypress/e2e/tests/rbac/migrator.test.ts

Added @rhsso tag to relevant tests, removed unused import

---

cypress/e2e/tests/rbac/architect.test.ts
cypress/e2e/tests/rbac/migrator.test.ts

[RFR] Added @rhsso tag to relevant tests, removed unused import

---

cypress/e2e/tests/administration/repository/subversion.test.ts
cypress/e2e/tests/migration/applicationinventory/assessment/filter.test.ts

This PR adapts the last credentials assignation.

[RFR] fix last credentials assignation

---

cypress/e2e/models/migration/applicationinventory/assessment.ts
cypress/e2e/tests/administration/custom-migration-targets/crud.test.ts
cypress/e2e/views/review.view.ts

Adaptations for the new version.

[RFR] Fix test suites

---

cypress/e2e/tests/migration/applicationinventory/analysis/binary_analysis.test.ts
cypress/e2e/tests/migration/applicationinventory/analysis/download_report.test.ts
cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
cypress/e2e/tests/migration/applicationinventory/analysis/upload_binary_analysis.test.ts
cypress/e2e/tests/rbac/custom-rules.test.ts
cypress/utils/data_utils.ts

[RFR] fix credentials method and mark bugs in titles

---

cypress/e2e/tests/migration/controls/businessservices/create.test.ts
cypress/e2e/tests/migration/controls/stakeholdergroups/create.test.ts
cypress/e2e/tests/migration/controls/stakeholders/create.test.ts
cypress/e2e/tests/migration/controls/stakeholders/filter.test.ts
cypress/e2e/tests/migration/controls/stakeholders/interlinked.test.ts
cypress/e2e/tests/migration/controls/stakeholders/pagination.test.ts
cypress/e2e/tests/migration/controls/stakeholders/sort.test.ts
cypress/e2e/views/common.view.ts
cypress/e2e/views/stakeholders.view.ts
cypress/utils/utils.ts

modified:   cypress/e2e/tests/migration/controls/businessservices/create.test.ts
modified:   cypress/e2e/tests/migration/controls/stakeholdergroups/create.test.ts
modified:   cypress/e2e/tests/migration/controls/stakeholders/create.test.ts
modified:   cypress/e2e/tests/migration/controls/stakeholders/filter.test.ts
modified:   cypress/e2e/tests/migration/controls/stakeholders/interlinked.test.ts
modified:   cypress/e2e/tests/migration/controls/stakeholders/pagination.test.ts
modified:   cypress/e2e/tests/migration/controls/stakeholders/sort.test.ts
modified:   cypress/e2e/views/common.view.ts
modified:   cypress/e2e/views/stakeholders.view.ts

[RFR] Controls test case fixes

---

cypress/e2e/views/applicationinventory.view.ts

The  applicationTagsSelect locator  on the 'Application creation' dialog is being updated through this PR.

[RFR] Update applicationTagsSelect locator

---

cypress/e2e/tests/migration/controls/tags/tag/crud.test.ts

modified:   cypress/e2e/tests/migration/controls/tags/tag/crud.test.ts

[RFR] Added Bug number to Tag CRUD test case

---

cypress/e2e/views/assessment.view.ts

The stakeholdergroupsSelect selector  on the Assessment dialog needs to be updated .

[RFR] Update stakeholdergroupsSelect selector

---

cypress/e2e/tests/migration/applicationinventory/assessment/create.test.ts
cypress/utils/utils.ts

Applications cannot be deleted if associated with waves .
This change is checking if Delete button is enabled only then applications will be deleted.

[RFR] Fix delete all Applications method

---

cypress/e2e/tests/migration/applicationinventory/assessment/create.test.ts
cypress/utils/utils.ts

1) I've updated "Bulk deletion of applications - Select page " because this is a better way of checking all the apps were deleted .

[RFR]Fix Jenkins failure: Bulk deletion of applications - Select page

---

cypress/e2e/models/migration/controls/stakeholders.ts
cypress/e2e/tests/migration/controls/stakeholders/filter.test.ts
cypress/e2e/tests/migration/controls/stakeholders/interlinked.test.ts
cypress/e2e/views/stakeholders.view.ts

modified:   cypress/e2e/models/migration/controls/stakeholders.ts
modified:   cypress/e2e/tests/migration/controls/stakeholders/interlinked.test.ts
modified:   cypress/e2e/views/stakeholders.view.ts

[RFR] Fix and bug tagging for stakeholder's tests

---

cypress/e2e/models/administration/credentials/credentials.ts
cypress/e2e/models/administration/jira-connection/jira.ts
cypress/e2e/tests/administration/jira-connection/filter.test.ts
cypress/e2e/views/credentials.view.ts
cypress/e2e/views/jira.view.ts
cypress/utils/utils.ts

[RFR] Filtering Jira connections added

---

cypress/e2e/tests/migration/migration-waves/field_validation.test.ts

[RFR] Mark product bug and fix automation issue

---

cypress/e2e/tests/migration/controls/tags/tagcategory/create.test.ts
cypress/e2e/views/tags.view.ts

This PR fixes the Tag Category creation test suite.

[RFR] Fix tagcategory create suite

---

cypress/e2e/tests/administration/jira-connection/sort.test.ts
cypress/e2e/types/constants.ts

[RFR] Tests for sorting Jiras

---

cypress/e2e/models/migration/applicationinventory/analysis.ts
cypress/e2e/tests/migration/applicationinventory/analysis/analysis_with_proxyenabled.test.ts
cypress/e2e/tests/migration/applicationinventory/analysis/binary_analysis.test.ts
cypress/e2e/tests/migration/applicationinventory/analysis/download_report.test.ts
cypress/e2e/tests/migration/applicationinventory/analysis/excludePackages.test.ts
cypress/e2e/tests/migration/applicationinventory/analysis/excludeTags.test.ts
cypress/e2e/tests/migration/applicationinventory/analysis/manuallyAnalyzePackages.test.ts
cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
cypress/e2e/tests/migration/applicationinventory/analysis/upload_binary_analysis.test.ts
cypress/utils/utils.ts

1) Removed deleteall applications methods
2) Clean up data in after methods
3) Validation in test 
4) Removed proxy disabling code

[RFR] Refactor Analysis tests

---

cypress/e2e/tests/migration/controls/tags/tag/filter.test.ts

modified:   cypress/e2e/tests/migration/controls/tags/tag/filter.test.ts

[RFR] Tagged the filter test with bug number

---

cypress/e2e/models/administration/credentials/JiraCredentials.ts
cypress/e2e/tests/administration/credentials/filter.test.ts
cypress/e2e/tests/administration/credentials/jira_crud.test.ts

Fixed failing credentials tests
Moved Jira credentials verification outside of model

[RFR] Fixed failing credentials tests

---

cypress/e2e/models/migration/migration-waves/migration-wave.ts

There was an error when a test tried to update the date of a Migration Waves, this PR fixes it.
@sshveta can you review this PR?

[RFR] Fix migration waves minor error

---

cypress/e2e/tests/migration/controls/tags/tag/create.test.ts

modified:   cypress/e2e/tests/migration/controls/tags/tag/create.test.ts

[RFR] Removed the Tag Type constraints from test

---

cypress/e2e/tests/administration/custom-migration-targets/crud.test.ts
cypress/e2e/tests/migration/migration-waves/export.test.ts
cypress/utils/data_utils.ts

An error in this test was preventing a migration target from being put in the first place
A cleaner solution would have been calculating the screen size, but this solution is faster in terms of calculation times.

[RFR] Fix drag-n-drop issue

---

cypress/e2e/models/migration/migration-waves/migration-wave.ts
cypress/e2e/tests/migration/migration-waves/filter_apps.test.ts

[RFR] Migration waves - Application filtering validation

---

cypress/e2e/tests/administration/custom-migration-targets/crud.test.ts
cypress/e2e/tests/administration/repository/maven.test.ts
cypress/utils/utils.ts

Fixes for:
* custom migration target layout changes [MTA-929](https://issues.redhat.com/browse/MTA-929)
* maven repository test [MTA-901](https://issues.redhat.com/browse/MTA-901)
I triggered a Jenkins run with other tests together as maven.test was only failing when grouped with other tests [#573](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/573/consoleFull).
I aborted it after seeing that both suites passed.

[RFR] Fix repo and migration target tests

---

cypress/e2e/tests/migration/reports/appsrisk.test.ts
cypress/e2e/tests/migration/reports/filter.test.ts
cypress/e2e/tests/migration/reports/pagination.test.ts
cypress/e2e/tests/migration/reports/sort.test.ts

Now it will not remove stakeholders, applications, etc that were not created by test itself 
Little tweaks and optimizations
Removed unused imports, etc.
Job run for this PR is [here](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/572/console). Important: There is test that SHOULD fail because of know bug

[RFR] Cleaned up reports tests

---

cypress/e2e/tests/migration/applicationinventory/manageimports/filter.test.ts
cypress/e2e/tests/migration/applicationinventory/manageimports/pagination.test.ts
cypress/e2e/tests/migration/applicationinventory/manageimports/sort.test.ts

[RFR] Remove references to BS and BS related functions in manageimports folder

---

cypress/e2e/tests/migration/applicationinventory/assessment/sort.test.ts

[RFR] Sort applications on business service

---

cypress/e2e/models/migration/applicationinventory/assessment.ts
cypress/e2e/tests/migration/applicationinventory/assessment/copy_assessment/copy_assessment.test.ts
cypress/e2e/views/assessment.view.ts
cypress/utils/utils.ts

[RFR] Fixed most of the tests

---

cypress/e2e/models/migration/applicationinventory/assessment.ts
cypress/e2e/tests/migration/applicationinventory/assessment/copy_assessment/sort.test.ts

Tested in Jenkins run [#583](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/583/console)
@sshveta could you please review this PR?
Thanks!

[RFR] Fix copy assessment sort test

---

cypress/e2e/tests/migration/migration-waves/pagination.test.ts

[RFR] Automate pagination migration waves

---

cypress/e2e/tests/migration/applicationinventory/assessment/assessment_after_import.test.ts
cypress/e2e/tests/migration/applicationinventory/assessment/copy_assessment/pagination.test.ts
cypress/e2e/tests/migration/applicationinventory/assessment/crud.test.ts
cypress/e2e/tests/migration/applicationinventory/assessment/dependency.test.ts
cypress/e2e/tests/migration/applicationinventory/assessment/filter.test.ts
cypress/e2e/tests/migration/applicationinventory/assessment/import.test.ts
cypress/e2e/tests/migration/applicationinventory/assessment/interlinked.test.ts
cypress/e2e/tests/migration/applicationinventory/assessment/pagination.test.ts

[RFR] Clean up assessment folder

---

cypress/e2e/tests/migration/controls/stakeholders/filter.test.ts

modified:   cypress/e2e/tests/migration/controls/stakeholders/filter.test.ts

[RFR] Fix for Stakeholder's filter test

---

cypress/e2e/tests/migration/migration-waves/filter_applications.test.ts
cypress/e2e/tests/migration/migration-waves/filter_apps.test.ts
cypress/utils/utils.ts

[RFR] Migration Waves : Fix filter by BS on manage apps modal

---

cypress/e2e/tests/administration/custom-migration-targets/field_validation.test.ts
cypress/e2e/views/custom-migration-target.view.ts

added clicking cancel on third test so it can continue to the fourth changed not.contain to not.exist because it is null

[RFR]Fixed jenkins failiure for custom migration targets field validations

---

cypress/e2e/models/migration/controls/tags.ts
cypress/e2e/models/migration/migration-waves/migration-wave.ts
cypress/e2e/tests/migration/applicationinventory/assessment/copy_assessment/pagination.test.ts
cypress/e2e/tests/migration/controls/tags/tag/crud.test.ts
cypress/e2e/tests/migration/controls/tags/tag/filter.test.ts
cypress/e2e/tests/migration/controls/tags/tagcategory/filter.test.ts

modified:   cypress/e2e/models/migration/migration-waves/migration-wave.ts
modified:   cypress/e2e/tests/migration/applicationinventory/assessment/copy_assessment/pagination.test.ts
modified:   cypress/e2e/tests/migration/controls/tags/tag/filter.test.ts
modified:   cypress/e2e/tests/migration/controls/tags/tagcategory/filter.test.ts
modified:   cypress/e2e/views/migration-wave.view.ts

[RFR] Fixes for other test cases

---

cypress/e2e/tests/migration/applicationinventory/assessment/create.test.ts
cypress/e2e/tests/migration/applicationinventory/assessment/sort.test.ts

Made the following changes in assessment/sort -
1) Change order of functions in after() block 
2) Remove bug ID since bug is now resolved

[RFR] assessment/sort - Fix Jenkins failure

---

cypress/e2e/tests/migration/applicationinventory/assessment/bulk_deletion_applications.test.ts
cypress/e2e/tests/migration/applicationinventory/assessment/create.test.ts

[RFR]  Fix after() block in assessment/create.ts

---

cypress/e2e/tests/migration/controls/tags/tag/create.test.ts
cypress/e2e/tests/migration/controls/tags/tag/crud.test.ts
cypress/e2e/tests/migration/controls/tags/tagcategory/crud.test.ts
cypress/e2e/tests/migration/controls/tags/tagcategory/filter.test.ts
cypress/e2e/tests/migration/controls/tags/tagcategory/pagination.test.ts

[RFR] Clean up spec files in tags folder

---

cypress/e2e/tests/migration/controls/businessservices/create.test.ts
cypress/e2e/tests/migration/controls/businessservices/filter.test.ts
cypress/e2e/tests/migration/controls/businessservices/pagination.test.ts
cypress/e2e/tests/migration/controls/businessservices/sort.test.ts

[RFR] Cleaning up files in businessservices folder

---

cypress/e2e/tests/migration/controls/businessservices/pagination.test.ts
cypress/e2e/tests/migration/controls/stakeholders/interlinked.test.ts

modified:   cypress/e2e/tests/migration/controls/businessservices/pagination.test.ts
modified:   cypress/e2e/tests/migration/controls/stakeholders/interlinked.test.ts

[RFR] Control's BS's pagination and Stakeholder interlinked tests fix

---

cypress/e2e/tests/migration/controls/stakeholdergroups/filter.test.ts
cypress/e2e/tests/migration/controls/stakeholdergroups/interlinked.test.ts
cypress/e2e/tests/migration/controls/stakeholdergroups/pagination.test.ts
cypress/e2e/tests/migration/controls/stakeholdergroups/sort.test.ts
cypress/e2e/tests/migration/controls/stakeholders/crud.test.ts
cypress/e2e/tests/migration/controls/stakeholders/filter.test.ts
cypress/e2e/tests/migration/controls/stakeholders/interlinked.test.ts
cypress/e2e/tests/migration/controls/stakeholders/pagination.test.ts
cypress/e2e/tests/migration/controls/stakeholders/sort.test.ts

[RFR] Clean up stakeholder tests

---

cypress/e2e/tests/migration/controls/jobfunctions/create.test.ts
cypress/e2e/tests/migration/controls/jobfunctions/crud.test.ts
cypress/e2e/tests/migration/controls/jobfunctions/filter.test.ts
cypress/e2e/tests/migration/controls/jobfunctions/sort.test.ts

[RFR] Cleanup files in jobfunctions folder

---

cypress/e2e/tests/migration/controls/stakeholders/pagination.test.ts

modified:   cypress/e2e/tests/migration/controls/stakeholders/pagination.test.ts

[RFR] Fix for stakeholder's pagination test afterhook

---

cypress/e2e/tests/upgrade/after_upgrade.test.ts

Changed table selector for stakeholders in the test

[RFR] Fixed after-upgrade

---

cypress/e2e/models/migration/applicationinventory/application.ts
cypress/e2e/tests/migration/applicationinventory/assessment/filter.test.ts
cypress/e2e/tests/migration/migration-waves/filter_applications.test.ts
cypress/e2e/types/types.ts
cypress/utils/utils.ts

1) Update application creation method to support application owner 
2) applySearchFilter()  - Add support for application owner
3) createMultipleApplicationsWithBSandTags() -  Add support for application owner

[RFR] Add owner field to application creation method

---

cypress/e2e/tests/migration/applicationinventory/reports/filter.test.ts
cypress/e2e/tests/migration/applicationinventory/reports/sort.test.ts

[RFR] code cleanup

---

cypress.config.ts
cypress/e2e/models/administration/jira-connection/jira.ts
cypress/e2e/models/migration/migration-waves/migration-wave.ts
cypress/e2e/tests/administration/jira-connection/interlinked.test.ts
cypress/e2e/tests/administration/jira-connection/negative.test.ts
cypress/e2e/tests/administration/jira-connection/sort.test.ts
cypress/e2e/tests/migration/applicationinventory/assessment/copy_assessment/copy_assessment.test.ts
cypress/e2e/types/constants.ts
cypress/e2e/views/jira.view.ts

[RFR] Implemented MTA-362 and MTA 363 (Polarion tests)

---

cypress/e2e/tests/administration/jira-connection/interlinked.test.ts

[RFR] Implemented validation of Jira connection error message

---

cypress/e2e/models/administration/credentials/credentialsMaven.ts
cypress/e2e/models/administration/credentials/credentialsProxy.ts
cypress/e2e/models/administration/credentials/credentialsSourceControlKey.ts
cypress/e2e/models/administration/credentials/credentialsSourceControlUsername.ts

[RFR] Removed success validation messages from credentials models

---

cypress/e2e/tests/migration/applicationinventory/assessment/copy_assessment/copy_assessment.test.ts
cypress/utils/utils.ts

[RFR] Copy assessment fix

---

cypress/e2e/models/migration/migration-waves/migration-wave.ts
cypress/e2e/tests/migration/migration-waves/create_tracker.test.ts
cypress/e2e/views/migration-wave.view.ts

[RFR] added tc for MTA-358

---

cypress/e2e/tests/administration/jira-connection/sort.test.ts

[RFR] Fixed removing all jira connections in jira-connections sorting test

---

cypress/e2e/tests/migration/migration-waves/export_to_jira_cloud.test.ts

[RFR] Add interop tag to export_to_jira_cloud.ts

---

cypress/e2e/tests/administration/credentials/filter.test.ts

[RFR] Removed bug number from test header

---

cypress/fixtures/analysis.json

[RFR] Upload binaries updated SP and incidents

---

cypress/e2e/tests/migration/migration-waves/field_validation.test.ts
cypress/e2e/types/constants.ts
cypress/utils/utils.ts

-in dates validations selection dates was being confused with same day last month, fixed -added unique validations - Polarion TC -365 jenkins run:https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/751/

[RFR] added duplicate names validation in migration wave and fixed the date validations

---

cypress/e2e/models/administration/credentials/credentials.ts
cypress/e2e/tests/administration/jira-connection/field_validations.test.ts
cypress/e2e/tests/migration/migration-waves/field_validation.test.ts
cypress/utils/utils.ts

[RFR] Fixed field_validation tests, did some cleanup

---

cypress/e2e/tests/migration/controls/businessservices/create.test.ts
cypress/e2e/tests/migration/controls/jobfunctions/create.test.ts

modified:   cypress/e2e/tests/migration/controls/businessservices/create.test.ts
modified:   cypress/e2e/tests/migration/controls/jobfunctions/create.test.ts

[RFR] Fix for job function and Business service create tests

---

cypress.config.ts
cypress/support/e2e.js
package-lock.json
package.json

[RFR] Integrate cypress log filter plugin

---

cypress.config.ts

[RFR] minor fix

---

cypress/e2e/models/migration/applicationinventory/application.ts
cypress/e2e/tests/migration/applicationinventory/analysis/tag_filter.test.ts
cypress/e2e/views/applicationinventory.view.ts

[RFR] Application details page: Filter tags by tag category

---

cypress/e2e/models/migration/migration-waves/migration-wave.ts
cypress/e2e/tests/migration/migration-waves/sort.test.ts
cypress/e2e/views/migration-wave.view.ts

jenkins run: https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/828/console

[RFR] added test case for application management table in migration waves

---

cypress/e2e/models/migration/applicationinventory/application.ts
cypress/e2e/tests/migration/applicationinventory/analysis/tag_filter.test.ts
cypress/e2e/views/applicationinventory.view.ts

[RFR] 6.2 Application details page: Filter tags by tag category

---

cypress/e2e/models/migration/migration-waves/migration-wave.ts
cypress/e2e/tests/migration/migration-waves/field_validation.test.ts
cypress/e2e/tests/migration/migration-waves/pagination.test.ts
cypress/e2e/views/common.view.ts
cypress/e2e/views/migration-wave.view.ts

jenkins run: https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/tackle-ui-tests-on-ocp/347/console

[RFR] adapted field validation and pagination tests in migration waves upstream

---

cypress/e2e/views/applicationinventory.view.ts

This fixes assessment/crud.test.ts on main.

[RFR] Upstream : Update kebab menu on app inventory view

---

cypress/e2e/views/common.view.ts
cypress/e2e/views/menu.view.ts

Update selectors on the app creation modal

[RFR] Upstream : Update selectors on app creation modal

---

cypress/e2e/models/administration/repositories/maven.ts
cypress/e2e/models/migration/applicationinventory/analysis.ts

This PR does not fix any test by itself, but allow multiple tests to start properly

[RFR] update selectors

---

cypress/e2e/models/migration/applicationinventory/assessment.ts
cypress/e2e/views/assessment.view.ts
cypress/e2e/views/reports.view.ts

1) Updated selectors on Assessment page
2) Updated selector on Configuration page

[RFR] Update selectors on Assessment view

---

cypress/utils/utils.ts

jenkins run : https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/tackle-ui-tests-on-ocp/373/

[RFR] update selector for method getTableColumnData

---

cypress/e2e/models/administration/repositories/git.ts
cypress/e2e/tests/administration/repository/git.test.ts

[RFR] Fixed git.test.ts

---

cypress/utils/utils.ts

[RFR] Fixed user logout for RBAC tests

---

cypress/e2e/models/migration/applicationinventory/analysis.ts
cypress/e2e/models/migration/applicationinventory/application.ts
cypress/e2e/types/constants.ts
cypress/e2e/views/analysis.view.ts
cypress/utils/utils.ts

[RFR] Fixed rbac/architect.test.ts test

---

cypress/utils/utils.ts

[RFR] Fixed patching tackle CR

---

cypress/utils/utils.ts

[RFR] Mta 6.1.1 fix tackle CR patching

---

cypress/e2e/tests/migration/controls/tags/tagcategory/crud.test.ts
cypress/e2e/views/stakeholders.view.ts
cypress/e2e/views/tags.view.ts
cypress/utils/utils.ts

modified:   cypress/e2e/views/stakeholders.view.ts
modified:   cypress/e2e/views/tags.view.ts

[RFR] Automation Fixes for controls test cases

---

cypress/e2e/tests/migration/applicationinventory/analysis/binary_analysis.test.ts
cypress/e2e/tests/migration/applicationinventory/analysis/upload_binary_analysis.test.ts

This PR adapts the remaining analysis tests based on the same premises as #668 
In this case, none of the tests will work due to two bugs I marked on each test title.
@sshveta could you review this PR please? Thanks!

[RFR] [JF] Mark analysis bugs

---

cypress/e2e/models/migration/applicationinventory/analysis.ts
cypress/e2e/tests/migration/applicationinventory/analysis/binary_analysis.test.ts
cypress/e2e/tests/migration/applicationinventory/analysis/download_report.test.ts
cypress/e2e/tests/migration/applicationinventory/analysis/upload_binary_analysis.test.ts
cypress/utils/utils.ts

[RFR] Removing HTML/CSV reports enablement in config

---

cypress/e2e/models/migration/applicationinventory/analysis.ts
cypress/e2e/tests/migration/applicationinventory/analysis/excludePackages.test.ts
cypress/e2e/tests/migration/applicationinventory/analysis/manuallyAnalyzePackages.test.ts
cypress/e2e/views/analysis.view.ts

Solves [MTA-1206](https://issues.redhat.com/browse/MTA-1206)
Jenkins run [451](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/tackle-ui-tests-on-ocp/451/)

[RFR] [CR] [JF] Adapt exclude packages analysis test

---

cypress/e2e/tests/rbac/custom-migration-target.test.ts
cypress/utils/utils.ts

[RFR] Fixed custom migration targets RBAC

---

cypress/e2e/tests/rbac/custom-rules.test.ts
cypress/fixtures/custom-rules.json

Adapted `custom-rules` according to the latest updates of bug [MTA-458](https://issues.redhat.com/browse/MTA-458)
Jenkins run [472](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/tackle-ui-tests-on-ocp/472)

[RFR] [JF] Adapt custom rules test

---

cypress/e2e/models/migration/migration-waves/migration-wave.ts

jenkins run: https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/tackle-ui-tests-on-ocp/489/

[RFR] added .focus() which fixes creating a new migration wave

---

cypress/e2e/tests/migration/applicationinventory/assessment/import.test.ts
cypress/e2e/views/applicationinventory.view.ts
cypress/e2e/views/common.view.ts
cypress/utils/utils.ts

1) Updated application_inventory_kebab_menu()
2) Updated a few selectors

[RFR] Fix app import failures

---

cypress/e2e/models/administration/jira-connection/jira.ts
cypress/e2e/models/migration/migration-waves/migration-wave.ts
cypress/e2e/tests/administration/jira-connection/filter.test.ts
cypress/e2e/tests/administration/jira-connection/interlinked.test.ts
cypress/e2e/views/common.view.ts
cypress/utils/utils.ts

[RFR] Fixes for Jira connection to align with latest upstream

---

cypress/e2e/models/administration/repositories/subversion.ts
cypress/e2e/tests/administration/repository/maven.test.ts
cypress/e2e/tests/administration/repository/subversion.test.ts
cypress/e2e/views/applicationinventory.view.ts
cypress/e2e/views/common.view.ts

[RFR] Fixed repository tests

---

cypress/e2e/tests/administration/custom-migration-targets/field_validation.test.ts

jenkins run : https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/tackle-ui-tests-on-ocp/495/console

[RFR] added focus method for new custom migration target

---

cypress/e2e/models/migration/migration-waves/migration-wave.ts
cypress/e2e/tests/migration/migration-waves/crud.test.ts
cypress/e2e/tests/migration/migration-waves/field_validation.test.ts

Some adaptations for the migration waves tests. I'll invest some time to investigate the issue with the `click` method.
@sshveta @Neilhamza could you please review this PR? Thanks!

[RFR] [JF] Adapt migration wave tests

---

cypress/e2e/views/common.view.ts

[RFR] Fixed submit button

---

cypress/e2e/tests/administration/custom-migration-targets/field_validation.test.ts
cypress/e2e/views/common.view.ts

[RFR] Fixed field validation test in custom targets

---

cypress/e2e/models/administration/credentials/credentials.ts
cypress/e2e/models/administration/jira-connection/jira.ts
cypress/e2e/views/common.view.ts

[RFR] Fixed canceling when deleting Jira connection

---

cypress/e2e/views/applicationinventory.view.ts
cypress/utils/utils.ts

[RFR] Fixed pressing kebab and edit buttons in application rows

---

cypress/e2e/models/migration/applicationinventory/analysis.ts
cypress/utils/utils.ts

[RFR] Fixed analysis wizard after 'Run' button was changed to 'Next'

---

cypress/e2e/views/common.view.ts
cypress/e2e/views/migration-wave.view.ts
cypress/utils/utils.ts

Jenkins: (https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/tackle-ui-tests-on-ocp/570/console)

[RFR] adapt migration-waves filter test

---

cypress/e2e/tests/migration/applicationinventory/analysis/upload_binary_analysis.test.ts

@sshveta @ibragins could you please review this PR? 
Thanks!

[RFR] Mark upload binary analysis bug

---

cypress/e2e/tests/migration/controls/businessservices/create.test.ts
cypress/e2e/views/common.view.ts

jenkins: (https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/961/)

[RFR][AF]fix create test for businessServices

---

cypress/e2e/tests/migration/controls/businessservices/filter.test.ts
cypress/utils/utils.ts

[RFR][AF]adapt selecting filter and mark bugs

---

cypress/e2e/tests/migration/applicationinventory/assessment/dependency.test.ts

[RFR] Add blocker bug for dependency tests

---

cypress/e2e/tests/migration/controls/businessservices/interlinked.test.ts

[RFR] [AF] mark bug and add success message validation

---

cypress/e2e/tests/migration/controls/jobfunctions/create.test.ts

Signed-off-by: midays@redhat.com
fixes: https://issues.redhat.com/browse/MTA-1356
Jenkins job: jango-psql-persistent-ocp-24730-django.apps.cam-tgt-57010.qe.gcp.devcluster.openshift.com

[RFR] [JF] [AF] fix jonfunctoins test

---

cypress/e2e/tests/migration/controls/tags/tag/create.test.ts
cypress/e2e/tests/migration/controls/tags/tagcategory/create.test.ts
cypress/e2e/views/tags.view.ts
cypress/utils/utils.ts

modified:   cypress/e2e/tests/migration/controls/tags/tag/create.test.ts
modified:   cypress/e2e/tests/migration/controls/tags/tagcategory/create.test.ts
modified:   cypress/e2e/views/tags.view.ts

[RFR][AF] Fix for tags test cases

---

cypress/e2e/tests/migration/migration-waves/create_tracker.test.ts
cypress/e2e/tests/migration/migration-waves/crud.test.ts
cypress/e2e/tests/migration/migration-waves/export_to_jira_cloud.test.ts
cypress/e2e/tests/migration/migration-waves/export_to_jira_datacenter.test.ts
cypress/e2e/tests/migration/migration-waves/field_validation.test.ts
cypress/e2e/tests/migration/migration-waves/filter.test.ts
cypress/e2e/tests/migration/migration-waves/filter_applications.test.ts
cypress/e2e/tests/migration/migration-waves/pagination.test.ts
cypress/e2e/tests/migration/migration-waves/sort.test.ts
cypress/utils/utils.ts

jenkins run : https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/982/consoleFull

[RFR] fix migration waves filter test and remove bug marks

---

cypress/e2e/tests/migration/controls/businessservices/create.test.ts
cypress/e2e/tests/migration/controls/businessservices/crud.test.ts
cypress/e2e/tests/migration/controls/businessservices/interlinked.test.ts
cypress/utils/utils.ts

jenkins : [pending](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/993/console)

[RFR] remove success message validation and add it to create test

---

cypress.config.ts

@sshveta Could you please review this PR? thanks.

[RFR] [JF] Update jira stage project id

---

cypress.config.ts
cypress/e2e/models/migration/migration-waves/migration-wave.ts

[RFR] [JF] Fix minor issues

---

cypress/e2e/models/migration/applicationinventory/analysis.ts
cypress/e2e/tests/migration/applicationinventory/assessment/bulk_deletion_applications.test.ts
cypress/e2e/views/applicationinventory.view.ts

Solves [MTA-1417](https://issues.redhat.com/browse/MTA-1417)
**Bulk analysis:**
Jenkins run [1042](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/1042/)
----
**Bulk deletion:**
Jenkins run [1043](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/1043/)
----
@sshveta could you please review this PR? Thanks

[RFR] [JF] adapt bulk analysis and bulk deletion tests

---

cypress/e2e/tests/rbac/custom-migration-target.test.ts

Solves [MTA-1439](https://issues.redhat.com/browse/MTA-1439)
Jenkins run [1039](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/1039/console)
@Shveta22 @ibragins  could you please review this PR? Thanks!

[RFR] [JF] adapt custom migration targets rbac tests and mark bug

---

cypress/e2e/models/migration/applicationinventory/analysis.ts
cypress/e2e/models/migration/applicationinventory/application.ts
cypress/e2e/tests/migration/applicationinventory/analysis/download_report.test.ts
cypress/e2e/types/constants.ts

Solves [MTA-1416](https://issues.redhat.com/browse/MTA-1416) and [MTA-1475](https://issues.redhat.com/browse/MTA-1475)
Jenkins run [1053](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1053/console)
----
Jenkins run [1054](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1054/console)
@sshveta could you please review this PR ? Thanks!

[RFR] [JF] Adapt rbac and download tests

---

cypress/e2e/tests/migration/migration-waves/export_to_jira_cloud.test.ts
cypress/e2e/types/constants.ts

Solves  [MTA-1409](https://issues.redhat.com/browse/MTA-1409)
Jenkins run: [1066](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/1066/console)
----
@sshveta could you please review this PR? Thanks!
Please squash this PR before merging it. Thanks!

[RFR] [JF] Fix export to jira cloud test

---

cypress/utils/utils.ts

[JF] fix filter type selection

---

cypress/e2e/tests/administration/jira-connection/interlinked.test.ts

[RFR] Fixed test that tries to remove Jira connection in use

---

cypress/e2e/tests/administration/jira-connection/interlinked.test.ts

[RFR] Removed test for jira connection in use

---

cypress/e2e/tests/migration/controls/businessservices/crud.test.ts
cypress/e2e/tests/migration/controls/businessservices/filter.test.ts
cypress/e2e/tests/migration/controls/businessservices/interlinked.test.ts

Removed MTA-1375 references

---

cypress/e2e/tests/administration/repository/maven.test.ts
cypress/e2e/tests/custom-metrics/analysis_metrics.test.ts
cypress/e2e/tests/migration/applicationinventory/analysis/upload_binary_analysis.test.ts

Unmarked some bugs and change the bug number to a different one.
This PR solves [MTA-1496](https://issues.redhat.com/browse/MTA-1496) , [MTA-1497](https://issues.redhat.com/browse/MTA-1497) and [MTA-1500](https://issues.redhat.com/browse/MTA-1500)
Jenkins run for maven test: [1088](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/1088/)

[RFR] [JF] unmark bugs

---

cypress/e2e/tests/migration/applicationinventory/applications/import.test.ts

Solves [MTA-1494](https://issues.redhat.com/browse/MTA-1494)

[RFR] [CC] remove import TC

---

cypress.config.ts
cypress/support/e2e.js
package-lock.json
package.json

Solves [MTA-1503](https://issues.redhat.com/browse/MTA-1503)

[RFR] [JF] Add memory management options

---

cypress/e2e/views/common.view.ts

Solves [MTA-1549](https://issues.redhat.com/browse/MTA-1549)
Jenkins run [1091](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/1091/)

[RFR] [JF] Adapt Filter Tests

---

cypress/e2e/models/administration/custom-migration-targets/custom-migration-target.ts
cypress/e2e/views/custom-migration-target.view.ts

Solves [MTA-1553](https://issues.redhat.com/browse/MTA-1553)
Jenkins run [1090](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/1090)

[RFR] [JF] adapt custom migration target tests

---

cypress/e2e/tests/rbac/review-assessment.test.ts
cypress/e2e/tests/rbac/upload_binary_analysis_architect.test.ts
cypress/e2e/tests/rbac/upload_binary_analysis_migrator.test.ts

Solves [MTA-1552](https://issues.redhat.com/browse/MTA-1552)
Marked bugs for the upload binary analysis tests and removed the enabling and disabling review without asessment config from the review-assessment test as that config doesn't exist anymore

[RFR] [JF] adapt rbac tests

---

cypress/e2e/tests/migration/reports/appsrisk.test.ts
cypress/e2e/tests/migration/reports/filter.test.ts
cypress/e2e/tests/migration/reports/pagination.test.ts
cypress/e2e/tests/migration/reports/sort.test.ts

[RFR] Add bug marker for reports

---

cypress/e2e/tests/migration/applicationinventory/manageimports/csv.test.ts

Marks Bug [MTA-1592](https://issues.redhat.com/browse/MTA-1592) and provides a workaround
Jenkins run [1146](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/1146/)

[RFR] Add workaround for csv downloading link

---

cypress/e2e/tests/administration/questionnaires/crud.test.ts

[RFR] Add questionnaire export

---

cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis_without_creds.test.ts
cypress/e2e/tests/migration/migration-waves/crud.test.ts
cypress/e2e/tests/migration/migration-waves/export_to_jira_cloud.test.ts

1) Added/removed few tests to tier0 suite
2) Moved bookserver analysis to a different file

[RFR] Update tier level

---

cypress/e2e/tests/migration/issues/filter.test.ts

[RFR] Fix for issues filtering test

---

README.md
cypress/e2e/tests/migration/migration-waves/export_to_jira_cloud.test.ts
cypress/e2e/tests/migration/migration-waves/export_to_jira_datacenter.test.ts

Solves [MTA-1593](https://issues.redhat.com/browse/MTA-1593)
Cloud:
----
Datacenter:

[RFR] Add exception note to jira export tests

---

cypress/e2e/models/administration/credentials/credentials.ts
cypress/e2e/views/credentials.view.ts

[RFR] Fixed filtering in credentials tests

---

cypress/e2e/tests/migration/controls/jobfunctions/create.test.ts
cypress/e2e/views/common.view.ts

Solves [MTA-1623](https://issues.redhat.com/browse/MTA-1623)
Jenkins run for the controls sorts tests (includes 2 failing tests but not from the controls folder):
[1188](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1188/console)
----
Jenkins run for `jobfunction/create.test.ts`
[1189](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1189/)

[RFR] [JF] Adapt control tets

---

cypress/e2e/models/migration/applicationinventory/assessment.ts
cypress/e2e/tests/migration/applicationinventory/assessment/assess_review.test.ts
cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts

[RFR] Update discard_assessment() method

---

cypress/e2e/models/migration/applicationinventory/analysis.ts
cypress/e2e/models/migration/applicationinventory/application.ts
cypress/e2e/tests/rbac/architect.test.ts
cypress/e2e/tests/rbac/migrator.test.ts
cypress/e2e/types/constants.ts
cypress/e2e/views/analysis.view.ts
cypress/utils/utils.ts

[RFR] Adapted RBAC tests to changes in 7.0.0

---

cypress/e2e/tests/migration/applicationinventory/applications/bulk_deletion_applications.test.ts

Solves [MTA-1632](https://issues.redhat.com/browse/MTA-1632)
Jenkins run [1209](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/1209/console)

[RFR] [JF] Minor bulk deletion fix

---

cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
cypress/e2e/tests/migration/applicationinventory/analysis/upload_binary_analysis.test.ts
cypress/e2e/tests/rbac/upload_binary_analysis_architect.test.ts
cypress/e2e/tests/rbac/upload_binary_analysis_migrator.test.ts
cypress/e2e/views/analysis.view.ts

Solves [MTA-1641](https://issues.redhat.com/browse/MTA-1641)
Brings back the upload analysis tests after [MTA-1420](https://issues.redhat.com/browse/MTA-1420) has been fixed and marks the `upload_binary_analysis_migrator` test with bug [MTA-1455](https://issues.redhat.com/browse/MTA-1455)
Jenkins run [1219](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/1219/console)
----
Added also a minor fix for `source_analysis` test after the combination of both tabs.
Jenkins run [1220](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/1220/)

[RFR] [JF] Bring upload analyses back

---

cypress/e2e/tests/migration/applicationinventory/applications/filter.test.ts

modified:   cypress/e2e/tests/migration/applicationinventory/applications/filter.test.ts
modified:   cypress/e2e/tests/migration/applicationinventory/applications/interlinked.test.ts

[RFR][JF] Fix application's filter and interlinked tests

---

cypress/e2e/tests/administration/credentials/remove_creds_app.test.ts
cypress/utils/utils.ts

[RFR] Adopted deletion of cred used by an app to new rules

---

cypress/e2e/tests/migration/applicationinventory/manageimports/csv.test.ts

Removes the workaround after [MTA-1592](https://issues.redhat.com/browse/MTA-1592) is fixed.

[RFR] Remove csv download workaround

---

cypress/e2e/tests/custom-metrics/analysis_metrics.test.ts

Removing test marker: Bug MTA-1420 in `analysis_metrics.test.ts`

Removing test marker: Bug MTA-1420

---

cypress/e2e/tests/administration/repository/git.test.ts

[RFR] Fixed repository/git test
