konveyor/tackle-ui-tests

- cypress/e2e/models/migration/applicationinventory/analysis.ts
- cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
- cypress/e2e/views/analysis.view.ts
Solves [MTA-1657](https://issues.redhat.com/browse/MTA-1657)
Jenkins run [1243](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1243/console) (The one affected by this tests is passing)
> [RFR] Add effort column test

- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/tests/migration/applicationinventory/analysis/load_analysis.ts
- cypress/fixtures/analysis.json
- cypress/fixtures/application.json
- cypress/fixtures/custom-rules.json
- cypress/fixtures/xml/hazelcast.windup.xml
Solves [MTA-1631](https://issues.redhat.com/browse/MTA-1631)
There are two skipped tests due to bug [MTA-1647](https://issues.redhat.com/browse/MTA-1647)
Jenkins run [1236](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/1236/console)
> [RFR] Add load analysis tests

- cypress/e2e/tests/migration/migration-waves/crud.test.ts
Jenkins run [1247](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1247/)
> [RFR] [JF] Adapt migration waves crud test

- cypress/e2e/models/migration/issues/issues.ts
- cypress/e2e/tests/migration/issues/all-issues/filter.test.ts
> [RFR] Added issues filtering by BS

- cypress/e2e/models/migration/issues/issues.ts
- cypress/e2e/views/issue.view.ts
> [RFR] Aligned automation of issues filtering with recent UI changes

- cypress/e2e/tests/migration/controls/stakeholdergroups/filter.test.ts
- cypress/e2e/tests/migration/migration-waves/filter_applications.test.ts
- cypress/e2e/tests/rbac/disable_keycloak.test.ts
- cypress/e2e/tests/upgrade/create_upgrade_data.test.ts
- cypress/e2e/types/constants.ts
- cypress/e2e/views/common.view.ts
- cypress/utils/utils.ts
This PR:
* Solves [MTA-1701](https://issues.redhat.com/browse/MTA-1701)
* Refactors the `applySearchFilter` method to reduce cognitive complexity and improve readability
* Does some minor refactors on filter tests
* Removes some non-used methods of `utils.ts`
Jenkins run with all filter tests: [1301](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1301/console). The failed tests are due to known bugs.
> [RFR] [JF] Adapt filter tests and refactor filter method

- cypress/e2e/models/migration/issues/issues.ts
- cypress/e2e/tests/migration/issues/all-issues/filter.test.ts
- cypress/e2e/types/types.ts
- cypress/fixtures/analysis.json
> [RFR] Added issues filtering by tags

- cypress/e2e/tests/rbac/disable_keycloak.test.ts
> [RFR] Stopping disabling keycloak to prevent MTA from being broken

- cypress/e2e/models/administration/general/generalConfig.ts
Solves [MTA-1734](https://issues.redhat.com/browse/MTA-1734)
Jenkins run [1330](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1330/)
> [RFR] [JF] Adapt download report test

- cypress/e2e/tests/migration/applicationinventory/analysis/tag_filter.test.ts
Solves [MTA-1735](https://issues.redhat.com/browse/MTA-1735)
Jenkins run [1322](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1322/console)
> [RFR] [JF] Adapt tag filter test

- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/models/migration/issues/issues.ts
- cypress/e2e/tests/migration/issues/all-issues/filter.test.ts
- cypress/e2e/views/issue.view.ts
> [RFR] Added all filters to issues except archetype, refactored mechanism to be more generic

- cypress/e2e/models/migration/applicationinventory/assessment.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/assess_review.test.ts
- cypress/e2e/views/common.view.ts
signed-off-by: mohamed idays midays@redhat.com
[Jenkins run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1350/console)
> [RFR][TA] MTA-422 --- application review during assessment

- cypress/e2e/models/migration/applicationinventory/archetype.ts
- cypress/e2e/views/archetype.view.ts
> [RFR] Add additional Archetype methods

- cypress/e2e/models/administration/custom-migration-targets/custom-migration-target.ts
- cypress/e2e/tests/administration/custom-migration-targets/crud.test.ts
- cypress/e2e/types/constants.ts
- cypress/e2e/views/common.view.ts
Solves [MTA-1704](https://issues.redhat.com/browse/MTA-1704)
Automates Polarion TC [MTA-409](https://polarion.engineering.redhat.com/polarion/#/project/MTAPathfinder/workitem?id=MTA-408)
Jenkins run [1353](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/1353/)
> [RFR] Automate custom migration targets go language

- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/models/migration/issues/issues.ts
- cypress/e2e/tests/migration/issues/allIssues/filter.test.ts
- cypress/e2e/tests/migration/issues/single-issue/filter.test.ts
- cypress/e2e/tests/migration/issues/singleApplication/filter.test.ts
- cypress/utils/utils.ts
1. Added single app issues filtering test
2. Moved some functionality to utils to reuse existing code
> [RFR] Added single app issues filtering test

- cypress/e2e/models/administration/assessment_questionnaire/assessment_questionnaire.ts
- cypress/e2e/tests/administration/questionnaires/crud.test.ts
- cypress/e2e/tests/administration/questionnaires/miscellaneous.test.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/assess_review.test.ts
Jenkins run https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1362/console
> [RFR] Jenkins failures for assessment and questionnaire

- OWNERS.md
> added OWNERS.md

- cypress/e2e/models/migration/applicationinventory/archetype.ts
> [RFR] Add Archetype delete method

- cypress/e2e/models/migration/applicationinventory/archetype.ts
- cypress/e2e/tests/migration/applicationinventory/archetypes/crud.test.ts
- cypress/utils/utils.ts
> [RFR] Archetype CRUD tests

- cypress/e2e/models/migration/applicationinventory/assessment.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/assess_review.test.ts
- cypress/e2e/views/applicationinventory.view.ts
Resolves: [MTA-1751](https://issues.redhat.com/browse/MTA-1751)
[Jenkins run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1389/console)
> [RFR][BA]Automate bug MTA-1751

- cypress/e2e/tests/migration/applicationinventory/assessment/assess_review.test.ts
> [RFR] Added missing bug number

- cypress/e2e/models/migration/archetypes/archetype.ts
- cypress/e2e/tests/migration/archetypes/crud.test.ts
> [RFR] Update archetype.delete()

- cypress/e2e/tests/migration/dynamic-report/dependencies/filter.test.ts
Added negative cases, when text filters are filled with random text to make sure that no result will be returned
> [RFR] Added negative tests to dependencies filtering test

- cypress/e2e/models/migration/archetypes/archetype.ts
- cypress/e2e/tests/migration/archetypes/filter.test.ts
resolves: [MTA-1706](https://issues.redhat.com/browse/MTA-1706)
[Jenkins run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1398/console)
> [RFR][TA] Filter archetype by name

- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/models/migration/applicationinventory/assessment.ts
- cypress/e2e/models/migration/archetypes/archetype.ts
- cypress/e2e/tests/custom-metrics/assessment_metrics.test.ts
- cypress/e2e/tests/migration/applicationinventory/applications/interlinked.test.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/assess_review.test.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/assessment_after_import.test.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts
- cypress/e2e/tests/migration/archetypes/assess_review.test.ts
- cypress/e2e/tests/migration/reports/applicationRisk.test.ts
- cypress/e2e/tests/migration/reports/filter.test.ts
- cypress/e2e/tests/migration/reports/pagination.test.ts
- cypress/e2e/tests/migration/reports/sort.test.ts
- cypress/e2e/tests/rbac/architect.test.ts
- cypress/e2e/views/archetype.view.ts
Notes:
This is just a WIP PR. The selectors have to be moved to view files among other things.
> [RFR] Add Archetype assess method and test

- cypress/e2e/models/administration/assessment_questionnaire/assessment_questionnaire.ts
- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/models/migration/applicationinventory/assessment.ts
- cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis_without_creds.test.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/assess_review.test.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/assessment_after_import.test.ts
- cypress/e2e/views/common.view.ts
- cypress/utils/utils.ts
[MTA-1746](https://issues.redhat.com/browse/MTA-1746)
> [RFR] Automate Bug MTA-1746

- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/models/migration/applicationinventory/assessment.ts
- cypress/e2e/models/migration/archetypes/archetype.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/assess_review.test.ts
- cypress/e2e/tests/migration/archetypes/assess_review.test.ts
- cypress/e2e/views/archetype.view.ts
- cypress/e2e/views/common.view.ts
- cypress/utils/utils.ts
> [RFR] Add method to validate archetype/application review fields

- cypress/e2e/models/migration/dynamic-report/issues/issues.ts
- cypress/e2e/tests/migration/dynamic-report/issues/allIssues/filter.test.ts
- cypress/e2e/views/issue.view.ts
- cypress/utils/utils.ts
> [RFR] Added issues filtering by archetype

- cypress/e2e/models/migration/dynamic-report/dependencies/dependencies.ts
- cypress/e2e/tests/migration/dynamic-report/dependencies/filter.test.ts
> [RFR] Added archetype filtering in dependencies test

- cypress/e2e/models/migration/archetypes/archetype.ts
- cypress/e2e/tests/migration/archetypes/crud.test.ts
Rsolves: [MTA-1514](https://issues.redhat.com/browse/MTA-1514)
[Jenkins Run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1463/console)
> [RFR][TA] Duplicate archetype

- cypress/e2e/models/migration/dynamic-report/dependencies/dependencies.ts
- cypress/e2e/tests/migration/dynamic-report/dependencies/filter.test.ts
> [RFR] Fixed filtering dependencies by tags

- cypress/fixtures/analysis.json
1. Analysis's tag_filter.test.ts  
[Jenkins run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/1481/console) 
2. Automated tagging using Source Analysis on tackle testapp 
[Jenkins Run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/1480/console)
> Analysis test case fixes

- cypress/e2e/tests/migration/applicationinventory/analysis/excludePackages.test.ts
- cypress/e2e/tests/migration/applicationinventory/analysis/manuallyAnalyzePackages.test.ts
> Added Bug number to the tests

- cypress/e2e/tests/rbac/architect.test.ts
- cypress/e2e/tests/rbac/migrator.test.ts
- cypress/fixtures/rbac.json
> [RFR] Removed bug number from migrator's title, added to architect's a new one

- cypress/e2e/tests/migration/applicationinventory/applications/filter.test.ts
- cypress/utils/utils.ts
automate filter by risk test case
jenkins : https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1529/
polarion test case: https://polarion.engineering.redhat.com/polarion/#/project/MTAPathfinder/workitem?id=MTA-431
> [RFR] automate filter by risk - application inventory

- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/models/migration/dynamic-report/issues/issues.ts
- cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis_without_creds.test.ts
- cypress/e2e/types/types.ts
- cypress/fixtures/analysis.json
- cypress/utils/utils.ts
> [RFR] Added affected applications validation

- cypress/e2e/models/administration/assessment_questionnaire/assessment_questionnaire.ts
- cypress/e2e/models/migration/archetypes/archetype.ts
- cypress/e2e/tests/migration/applicationinventory/applications/interlinked.test.ts
jenkins run : https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1535/console
test case that is failing not relevant to the added test case
polarion : https://polarion.engineering.redhat.com/polarion/#/project/MTAPathfinder/workitem?id=MTA-401
> [RFR] validate application association with archetype and app tags 

- cypress/e2e/tests/migration/applicationinventory/applications/filter.test.ts
- cypress/e2e/types/constants.ts
- cypress/utils/utils.ts
jenkins run:
https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1542/console
polarion MTA-413: https://polarion.engineering.redhat.com/polarion/#/project/MTAPathfinder/workitem?id=MTA-413
> [RFR] automate application inventory filter by archetype

- cypress/e2e/tests/migration/applicationinventory/applications/manage_credentials_many_apps.test.ts
- cypress/utils/utils.ts
> [RFR] Added test to manage credentials for multiple applications

- cypress/e2e/tests/migration/migration-waves/create_tracker.test.ts
- cypress/e2e/tests/migration/migration-waves/export_to_jira_cloud.test.ts
Solves [MTA-1855](https://issues.redhat.com/browse/MTA-1855) by automating bug [MTA-1843](https://issues.redhat.com/browse/MTA-1843)
Jenkins run [1544](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/1544/console)
> [RFR] Automates application with associated ticket deletion bug

- cypress/e2e/models/migration/migration-waves/migration-wave.ts
- cypress/e2e/tests/migration/migration-waves/crud.test.ts
Solves [MTA-1853](https://issues.redhat.com/browse/MTA-1853) by automating [MTA-1813](https://issues.redhat.com/browse/MTA-1813)
> [RFR] Update migration wave crud test to include todays date

- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts
- cypress/e2e/views/common.view.ts
automates polarion MTA 390 - https://polarion.engineering.redhat.com/polarion/redirect/project/MTAPathfinder/workitem?id=MTA-390
jenkins run : https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1582/console
> [RFR] automate assess application and overide assessment for that archetype

- cypress/e2e/models/migration/applicationinventory/assessment.ts
- cypress/e2e/models/migration/archetypes/archetype.ts
- cypress/e2e/tests/migration/archetypes/crud.test.ts
- cypress/e2e/views/archetype.view.ts
**Signed-off-by:** mohamed idays midays@redhat.com
**solves:** [MTA-1865](https://issues.redhat.com/browse/MTA-1865)
[Jenkins run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1589/console)
> [RFR] MTA-428: Discard Archetype Review

- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/models/migration/applicationinventory/assessment.ts
- cypress/e2e/tests/rbac/architect.test.ts
- cypress/e2e/views/review.view.ts
Removed bug number from the test
Removed not relevant validation
Fixed selector of button in review
Some more little fixes
> [RFR] Fixes for RBAC tests

- cypress/e2e/models/migration/applicationinventory/assessment.ts
Added more timeout befire looking for the Review tab
[Jenkins run 1](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1601/)
[Jenkins run 2](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1602/)
[Jenkins run 3](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1603/)
> [RFR] [JF] Fix discard archetype

- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/views/migration-wave.view.ts
Solves [MTA-1989](https://issues.redhat.com/browse/MTA-1989)
Jenkins run [1607](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/1607/console)
> [RFR] [JF] Adapt unlink test

- cypress/e2e/models/migration/archetypes/archetype.ts
- cypress/e2e/tests/migration/archetypes/crud.test.ts
- cypress/e2e/views/archetype.view.ts
solves: [MTA-1866](https://issues.redhat.com/browse/MTA-1866)
[Jenkins run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1631/console)
> [RFR] [TA] compare tags after archetype duplication

- cypress/e2e/tests/migration/migration-waves/field_validation.test.ts
jenkins : https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1629/
> [RFR] fix jenkins failure migration waves field validation test

- cypress/e2e/tests/migration/migration-waves/sort.test.ts
jenkins run : https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1625/
> [RFR] fix jenkins failure migration waves sort test

- cypress/e2e/tests/administration/repository/subversion.test.ts
- cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
Solves [MTA-2013](https://issues.redhat.com/browse/MTA-2013)
> [RFR] [JF] Skip svn tests until a server is providad to us

- cypress/e2e/models/migration/applicationinventory/assessment.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/archetype_association.test.ts
- cypress/e2e/views/common.view.ts
Automate application association with archetype when application is created before archetype is created .
> [RFR] Archetype association - Application creation before archetype creation

- cypress/e2e/models/migration/applicationinventory/assessment.ts
- cypress/e2e/tests/migration/reports-tab/links-validation.test.ts
Solves [MTA-1936](https://issues.redhat.com/browse/MTA-1936) by automating Polarion [TC 429](https://polarion.engineering.redhat.com/polarion/redirect/project/MTAPathfinder/workitem?id=MTA-429)
This same file will contain Polarion TC 430 in the future, that's why the comment includes it.
Hi @Shveta22 @kpunwatk, could you please review this PR? Thanks!
---
Jenkins run [1656](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/1656/console)
> [RFR] Add report links validation test

- cypress/e2e/models/migration/applicationinventory/analysis.ts
- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/tests/migration/applicationinventory/analysis/excludePackages.test.ts
- cypress/e2e/tests/migration/applicationinventory/analysis/manuallyAnalyzePackages.test.ts
- cypress/fixtures/analysis.json
TC [Passed](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1663/), 
[Passed ](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1664/console)
modified:   cypress/e2e/models/migration/applicationinventory/application.ts
modified:   cypress/e2e/tests/migration/applicationinventory/analysis/excludePackages.test.ts
> [RFR][JF] Exclude packages test case fix

- cypress/e2e/tests/migration/dynamic-report/issues/allIssues/sort.test.ts
- cypress/utils/utils.ts
> [RFR] Issues sorting test

- cypress/e2e/tests/administration/questionnaires/filter.test.ts
Automates Polarion : https://polarion.engineering.redhat.com/polarion/#/project/MTAPathfinder/workitem?id=MTA-434
Jenkins: https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1697/
> [RFR] Automate questionnaire name filter validation - MTA 434

- cypress/e2e/tests/migration/reports-tab/sort.test.ts
- cypress/e2e/views/reportsTab.view.ts
- cypress/utils/utils.ts
Solves [MTA-2057](https://issues.redhat.com/browse/MTA-2057) by automating [MTA-452](https://polarion.engineering.redhat.com/polarion/#/project/MTAPathfinder/workitem?id=MTA-452)
---
Jenkins run [1711](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/1711/console)
> [RFR] Add report sort test

- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/models/migration/applicationinventory/assessment.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/archetype_association.test.ts
Jenkins jobs
1) [Application review ](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1716)
2) [Application review inheritance from archetypes ](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1717/)
3) [Archetype review ](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1715/)
> [RFR] Verify application Review field after inheritance from multiple archetypes

- cypress/e2e/models/administration/assessment_questionnaire/assessment_questionnaire.ts
- cypress/e2e/tests/administration/questionnaires/miscellaneous.test.ts
automates polarion : https://polarion.engineering.redhat.com/polarion/#/project/MTAPathfinder/workitem?id=MTA-435
jenkins : https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1724/
> [RFR] Automate questionnaires search questions - MTA 435

- cypress/e2e/tests/migration/dynamic-report/dependencies/sort.test.ts
> [RFR] Added sorting test for dependencies

- cypress/e2e/tests/migration/applicationinventory/analysis/affected_files.test.ts
- cypress/fixtures/analysis.json
modified:   cypress/e2e/models/migration/applicationinventory/analysis.ts
new file:   cypress/e2e/tests/migration/applicationinventory/analysis/affected_files.test.ts
> [RFR] Automate Bug MTA-2006

- cypress/e2e/models/administration/assessment_questionnaire/assessment_questionnaire.ts
- cypress/e2e/tests/administration/questionnaires/miscellaneous.test.ts
automates polarion TC 437 : https://polarion.engineering.redhat.com/polarion/#/project/MTAPathfinder/workitem?id=MTA-437
jenkins run : https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1728/
> [RFR] automate exports and imports existing questionnaire after updating name in file

- cypress/e2e/models/migration/applicationinventory/analysis.ts
- cypress/e2e/tests/migration/applicationinventory/analysis/custom-rules.test.ts
- cypress/e2e/tests/rbac/custom-rules.test.ts
- cypress/fixtures/analysis.json
- cypress/fixtures/xml/hibernate-custom.windup.xml
- cypress/fixtures/yaml/01-custom-rule-example.windup.yaml
Solves [MTA-2069](https://issues.redhat.com/browse/MTA-2069) by automating bug [MTA-2001](https://issues.redhat.com/browse/MTA-2001)
---
Jenkins run [1730](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/1730/console)
> [RFR] Automate custom rules bug

- cypress/e2e/tests/migration/dynamic-report/issues/affectedApplications/sort.test.ts
> [RFR] Added test to sort applications in affected apps

- cypress/e2e/tests/migration/dynamic-report/issues/allIssues/pagination.test.ts
> [RFR] Added pagination test for all issues page

- cypress/e2e/models/administration/assessment_questionnaire/assessment_questionnaire.ts
- cypress/e2e/models/migration/reports-tab/reports-tab.ts
- cypress/e2e/tests/migration/reports-tab/filter.test.ts
- cypress/e2e/tests/migration/reports-tab/reports.test.ts
- cypress/e2e/views/reportsTab.view.ts
Solves [MTA-2088](https://issues.redhat.com/browse/MTA-2088) by automating Polarion TC [MTA-469](https://polarion.engineering.redhat.com/polarion/#/project/MTAPathfinder/workitem?id=MTA-469) 
---
Jenkins run [1770](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/1770/console)
> [RFR] Automate reports tab filter test

- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/archetype_association.test.ts
- cypress/e2e/views/common.view.ts
I will paste the results of the Jenkins job shortly .
> [RFR] Verify application assessment inheritance from multiple archetypes

- cypress/e2e/tests/migration/dynamic-report/dependencies/pagination.test.ts
> [RFR] Added pagination test for dependencies

- cypress/e2e/tests/migration/dynamic-report/issues/singleApplication/pagination.test.ts
> [RFR] Added pagination test for single application issues

- cypress/e2e/models/administration/assessment_questionnaire/assessment_questionnaire.ts
- cypress/e2e/tests/administration/questionnaires/crud.test.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/archetype_association.test.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/assess_review.test.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/assessment_after_import.test.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts
- cypress/e2e/tests/migration/archetypes/assess_review.test.ts
- cypress/e2e/tests/migration/reports-tab/filter.test.ts
- cypress/e2e/tests/migration/reports-tab/links-validation.test.ts
- cypress/e2e/tests/migration/reports-tab/reports.test.ts
- cypress/e2e/tests/migration/reports-tab/sort.test.ts
> [RFR] Perform application asessment/review of application associated with unassessed archetypes

- cypress/e2e/tests/migration/applicationinventory/assessment/review/filter.test.ts
- cypress/e2e/views/reportsTab.view.ts
Solves [MTA-2135](https://issues.redhat.com/browse/MTA-2135) by automating Polarion TC [495](https://polarion.engineering.redhat.com/polarion/#/project/MTAPathfinder/workitem?id=MTA-495)
Hi @Shveta22 could you please review this PR? Thanks!
> [RFR] Automate review identified risks filter validations

- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/models/migration/applicationinventory/assessment.ts
- cypress/e2e/models/migration/archetypes/archetype.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts
- cypress/e2e/views/common.view.ts
- cypress/utils/utils.ts
automates [polarion MTA440](https://polarion.engineering.redhat.com/polarion/#/project/MTAPathfinder/workitem?id=MTA-440) and [polarion MTA439](https://polarion.engineering.redhat.com/polarion/#/project/MTAPathfinder/workitem?id=MTA-439) 
[Jenkins]( https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1852)
> [RFR] Discard application and archetype assessment through AssessmentActions page

- cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts
I'll add the results from the Jenkins run shortly.
> [RFR] Verify inheritance after discarding application assessment & review

- cypress/e2e/tests/migration/applicationinventory/assessment/archetype_association.test.ts
- cypress/utils/utils.ts
> [RFR] Verify multiple apps inherit archetype assessment/review

- cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts
automates Polarion - [MTA 441](https://polarion.engineering.redhat.com/polarion/#/project/MTAPathfinder/workitem?id=MTA-441) and [MTA 442](https://polarion.engineering.redhat.com/polarion/#/project/MTAPathfinder/workitem?id=MTA-442)
[jenkins](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1901/console)
> [RFR] Delete assessments from an archived questionnaire from an archetype and application

- cypress/e2e/tests/upgrade/create_upgrade_data.test.ts
- cypress/e2e/types/types.ts
- cypress/fixtures/upgrade-data.json
> [RFR] Added pre-upgrade assessment validation

- cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts
- cypress/utils/utils.ts
We still don't have a successful Jenkins run at this point . The pipeline failed at this stage:
'Installing dependencies for cypress'
> [RFR] App association when an archetype contains a subset  of the tags of another archetype

- cypress/e2e/tests/upgrade/create_upgrade_data.test.ts
- cypress/e2e/types/types.ts
- cypress/fixtures/upgrade-data.json
> Aligned var names and values to match 7.0

- cypress/e2e/models/migration/applicationinventory/analysis.ts
- cypress/e2e/tests/administration/repository/subversion.test.ts
- cypress/fixtures/application.json
Solves [MTA-1744](https://issues.redhat.com/browse/MTA-1744) by automating bug [MTA-1717](https://issues.redhat.com/browse/MTA-1717)
---
Jenkins run [1965](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/1965/console)
> [RFR] [TA] automate svn bug

- dockerfiles/interop/Dockerfile
Need to remove these lines as they are no longer needed and causing failures.
> [LPTOCPCI-1123] Fix interop testing Dockerfile

- cypress/e2e/tests/migration/applicationinventory/assessment/assess_review.test.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts
1) Adding archetype assessment and review to the interop test suite 
2) Adding application archetype assessment and review tests to the tier0 test suite
> [RFR] Expand interop and tier0  tests

- cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts
- cypress/e2e/tests/migration/migration-waves/crud.test.ts
- cypress/e2e/tests/migration/migration-waves/export_to_jira_cloud.test.ts
Backported the following to mta_7.0.0
1) https://github.com/konveyor/tackle-ui-tests/pull/956
2) https://github.com/konveyor/tackle-ui-tests/pull/958
> [RFR] Update interop test suite

- cypress/e2e/models/migration/applicationinventory/assessment.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/questionnaire_features.test.ts
- cypress/e2e/views/common.view.ts
I will update the results from the Jenkins run shortly .
> [RFR] Automate questionnaire auto answer feature

- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/models/migration/applicationinventory/assessment.ts
- cypress/e2e/models/migration/archetypes/archetype.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/questionnaire_features.test.ts
> [RFR] [CR] Replace two assessment methods with verifyButtonEnabled() 

- cypress/e2e/models/migration/archetypes/archetype.ts
- cypress/e2e/tests/migration/archetypes/crud.test.ts
- cypress/e2e/tests/migration/archetypes/questionnaire_features.test.ts
I will update the PR with the results from Jenkins run.
> [RFR] [TA] Test conditional questions during archetype assessment

- cypress/e2e/tests/migration/archetypes/questionnaire_features.test.ts
I will update the PR with the results from the Jenkins run.
> [RFR] Verify auto answering feature for archetypes

- cypress/e2e/tests/migration/controls/businessservices/create.test.ts
modified:   cypress/e2e/tests/migration/controls/businessservices/create.test.ts
> [RFR][JF] Mark as bug business service's create TC

- cypress/e2e/models/migration/applicationinventory/analysis.ts
- cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
- cypress/e2e/types/types.ts
- cypress/e2e/views/analysis.view.ts
- cypress/fixtures/analysis.json
- cypress/utils/utils.ts
modified:   cypress/e2e/models/migration/applicationinventory/analysis.ts
modified:   cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
modified:   cypress/e2e/views/analysis.view.ts
> [RFR][TA] OpenJDK Targets Automation

- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/models/migration/applicationinventory/assessment.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts
- cypress/e2e/views/applicationinventory.view.ts
1) The timeout in  Assessment.take_questionnaire() had to be increased because of an unresolved bug on upstream.
2) [Jenkins run ](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/tackle-ui-tests-on-ocp/642/ )
Results : PASS
> [RFR] [TA] Filter application tag after assessment and archetype association

- cypress/e2e/models/migration/applicationinventory/application.ts
I'm removing code related to copy assessment since the feature is obsolete in MTA 7.0.0.
> [RFR] Remove code related to copy assessment

- cypress/e2e/tests/migration/applicationinventory/applications/filter.test.ts
- cypress/e2e/views/common.view.ts
Solves [MTA-2313](https://issues.redhat.com/browse/MTA-2313)
This PR fixes some selector issues and marks some other tests with the new bug [MTA-2322](https://issues.redhat.com/browse/MTA-2322)
[Jenkins run 2140](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/2140/console)
Because I changed the filter main function,  I executed a Jenkins run of all filter tests to confirm that none of them failed due to the change I did.
[Jenkins run 2134](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/2134/console)
> [RFR] [JFF] ix filter tests

- cypress/utils/utils.ts
> [RFR] Fix Tags Filter test

- cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis_without_creds.test.ts
> [RFR] Fix source_analysis_without_creds.test.ts by adding 'amount of apps on page' parameter

- cypress/e2e/models/administration/assessment_questionnaire/assessment_questionnaire.ts
[Jenkins job ]( https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/2155/)
Results : Pass
> [RFR] [JF] Update questionnaire.enable() method

- cypress/e2e/tests/upgrade/after_upgrade.test.ts
- cypress/utils/utils.ts
Jenkins [run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/2176/console) is successful
> [RFR] Validating status for tackle CR

- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/models/migration/archetypes/archetype.ts
- cypress/e2e/models/migration/controls/businessservices.ts
- cypress/e2e/models/migration/controls/jobfunctions.ts
- cypress/e2e/models/migration/controls/stakeholdergroups.ts
- cypress/e2e/models/migration/controls/stakeholders.ts
- cypress/e2e/models/migration/controls/tagcategory.ts
- cypress/e2e/models/migration/controls/tags.ts
- cypress/e2e/models/migration/migration-waves/migration-wave.ts
- cypress/e2e/models/migration/reports-tab/reports-tab.ts
Make sure to wait for the page to be loaded before proceeding .
> [RFR] [JF] Increase timeout in open() method for several classes

- cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
- cypress/fixtures/analysis.json
- cypress/fixtures/application.json
Solves [MTA-2327](https://issues.redhat.com/browse/MTA-2327) by automating customer bug [MTA-1785](https://issues.redhat.com/browse/MTA-1785)
Jenkins run [2195](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/2195/)
> [RFR] Automate jdk9 analysis bug

- cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts
two bugs blocking TC's in assessment miscellaneous tests
> [RFR] Mark two bugs for two TC's

- cypress/e2e/tests/upgrade/after_upgrade.test.ts
- cypress/utils/utils.ts
> [RFR] Added validation of tackle operator log

- cypress/e2e/views/applicationinventory.view.ts
- cypress/fixtures/analysis.json
modified:   cypress/e2e/views/applicationinventory.view.ts
> [RFR] Analysis's tag filter test fix

- cypress/e2e/tests/migration/applicationinventory/applications/bulk_deletion_applications.test.ts
- cypress/e2e/views/applicationinventory.view.ts
[Jenkins job ]( https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/2259/c)
Results : Pass
> [RFR] Fix App bulk deletion failure

- cypress/e2e/views/credentials.view.ts
> [RFR] JF_fix_credentials_filtering

- cypress/e2e/tests/migration/applicationinventory/applications/filter.test.ts
- cypress/e2e/tests/migration/reports-tab/filter.test.ts
- cypress/e2e/views/reportsTab.view.ts
Remove bug marks on tests marked with bugs that are already fixed.
Jenkins run [2286](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/2286/console)
> [RFR] Remove bug marks

- cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts
changed to "Not started" as this is the expected behavior -> jira [ticket](https://issues.redhat.com/browse/MTA-1973)
jenkins [run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/2315/) :
> [RFR] remove bug mark and modify test in assessment/miscellaneous

- cypress/e2e/models/migration/archetypes/archetype.ts
- cypress/e2e/tests/migration/archetypes/questionnaire_features.test.ts
[Jenkins job ](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/2320/)
Results : Pass
> [RFR] [JF] Fix archetype questionnaire tests

- cypress/e2e/tests/migration/applicationinventory/analysis/analysis_with_proxyenabled.test.ts
- cypress/e2e/tests/migration/applicationinventory/analysis/upload_binary_analysis.test.ts
modified:   cypress/e2e/tests/migration/applicationinventory/analysis/analysis_with_proxyenabled.test.ts
modified:   cypress/e2e/tests/migration/applicationinventory/analysis/upload_binary_analysis.test.ts
> [RFR][JF] Fix analysis_with_proxyenabled test case

- cypress/e2e/tests/rbac/review-assessment.test.ts
> [RFR]  [TA] Perform archetype assessment and review as Architect

- cypress/e2e/models/migration/applicationinventory/assessment.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/archetype_association.test.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/assess_review.test.ts
[Jenkins job](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/2350)
No new failures are seen with this PR
> [RFR] Fix a few assessment tests

- cypress/e2e/models/migration/applicationinventory/application.ts
Change to branch `mta_7.0.0`
Related to https://github.com/konveyor/tackle2-ui/pull/1687
> [RFR] Check 'Total Effort' instead of 'Effort'

- cypress/e2e/tests/administration/custom-migration-targets/field_validation.test.ts
- cypress/utils/utils.ts
Solves [MTA-2420](https://issues.redhat.com/browse/MTA-2420), [MTA-2421](https://issues.redhat.com/browse/MTA-2421) & [MTA-2422](https://issues.redhat.com/browse/MTA-2422) by fixing the custom migration targets and upload binary analysis tests.
---
Jenkins run [2383](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/2383/console)
---
Jenkins run [2382](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/2382/console)
> [RFR] [JF] Fix upload binary analysis and custom migration target tests

- cypress/utils/utils.ts
this PR fixes all the tests except export to jira data center test
jenkins [run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/2371/console)
> [RFR] JF migration-waves/*

- cypress/e2e/models/migration/dynamic-report/issues/issues.ts
- cypress/e2e/tests/migration/dynamic-report/issues/filter.sorting.pagination.test.ts
- cypress/e2e/views/issue.view.ts
The only one test fails due to a known bug
> [RFR] JF: Fix for multiple issues filtering failures

- cypress/e2e/tests/migration/applicationinventory/analysis/tag_filter.test.ts
- cypress/fixtures/analysis.json
modified:   cypress/e2e/tests/migration/applicationinventory/analysis/tag_filter.test.ts
Bug Automated https://issues.redhat.com/browse/MTA-2089
> [RFR] Automate bug to verify rules doesn'y have effort=0

- cypress/e2e/models/migration/applicationinventory/application.ts
Reverts konveyor/tackle-ui-tests#1016
https://github.com/konveyor/tackle2-ui/pull/1764 is not merged yet
> Revert "Check 'Total Effort' instead of 'Effort'"

- cypress/e2e/tests/migration/applicationinventory/analysis/custom-rules.test.ts
- cypress/fixtures/analysis.json
- cypress/fixtures/xml/test.windup.xml
modified:   cypress/e2e/tests/migration/applicationinventory/analysis/custom-rules.test.ts
new file:   cypress/fixtures/administracionEfectivo.ear
new file:   cypress/fixtures/xml/test.windup.xml
> [RFR] Automate bug using custom rule with administracionEfectivo app

- cypress/e2e/tests/migration/applicationinventory/applications/import.test.ts
> [RFR] Remove migration waves as part of set up in import tests

- cypress/e2e/tests/upgrade/after_upgrade.test.ts
- cypress/e2e/tests/upgrade/create_upgrade_data.test.ts
- cypress/e2e/views/common.view.ts
- cypress/utils/utils.ts
> [RFR] Added source and target versions validation before and after upgrade in UI

- cypress/e2e/models/migration/applicationinventory/analysis.ts
- cypress/e2e/tests/migration/applicationinventory/analysis/custom-rules.test.ts
- cypress/e2e/types/types.ts
- cypress/fixtures/analysis.json
- cypress/fixtures/yaml/01-javax-package-custom-target.windup.yaml
Resolves: https://issues.redhat.com/browse/MTA-2447
Jenkins run: https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/2439/console
> [RFR] Analysis: Custom rule for javax.* package import

- cypress/e2e/models/administration/custom-migration-targets/custom-migration-target.ts
- cypress/e2e/tests/administration/custom-migration-targets/crud.test.ts
- cypress/e2e/views/custom-migration-target.view.ts
- cypress/fixtures/custom-rules.json
- cypress/fixtures/xml/corporate-framework-config.windup.xml
Resolves https://issues.redhat.com/browse/MTA-1607
> [RFR][TA] Automate MTA-404 custom rules with source technology

- cypress/e2e/tests/migration/applicationinventory/assessment/archetype_association.test.ts
> [RFR] Assess archetype with multiple questionnaires

- cypress/e2e/tests/upgrade/after_upgrade.test.ts
- cypress/e2e/tests/upgrade/create_upgrade_data.test.ts
- cypress/e2e/views/common.view.ts
- cypress/utils/utils.ts
> [RFR] Added version validation in pre- and after-upgrade

- cypress/e2e/tests/upgrade/after_upgrade.test.ts
- cypress/e2e/tests/upgrade/create_upgrade_data.test.ts
- cypress/e2e/views/common.view.ts
- cypress/utils/utils.ts
> [RFR] Added source and target versions validation before and after upgrade in CLI

- cypress/e2e/models/administration/custom-migration-targets/custom-migration-target.ts
- cypress/e2e/tests/administration/custom-migration-targets/crud.test.ts
- cypress/fixtures/custom-rules.json
Resolves https://issues.redhat.com/browse/MTA-1608
> [RFR][TA] Automate MTA-405 custom rules with target technology

- cypress/e2e/tests/administration/jira-connection/crud.test.ts
Issue was caused my stopped support for Jira basic auth with credentials. Switched auth to bearer token and it fixed the issue.
> [RFR] JF - fixed Jira crud test

- cypress/e2e/tests/upgrade/create_upgrade_data.test.ts
- cypress/e2e/types/types.ts
- cypress/fixtures/upgrade-data.json
> [RFR] Added archetype creation and assessment in pre-upgrade

- cypress/e2e/tests/migration/archetypes/miscellaneous.test.ts
> [RFR] Retake and Discard Archetype Assessment

- cypress/e2e/tests/upgrade/after_upgrade.test.ts
- cypress/e2e/tests/upgrade/create_upgrade_data.test.ts
- cypress/e2e/types/types.ts
- cypress/fixtures/upgrade-data.json
> [RFR] Added archetype creation in pre-upgrade on main

- cypress/e2e/models/migration/archetypes/archetype.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts
- cypress/e2e/tests/migration/archetypes/miscellaneous.test.ts
> [RFR] [TA] View archived assessment for an archetype

- cypress/e2e/models/migration/custom-metrics/custom-metrics.ts
- cypress/e2e/tests/custom-metrics/disable_metrics.test.ts
- cypress/utils/utils.ts
Resolves: https://issues.redhat.com/browse/MTA-1131
Jenkins run: https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/2490/console
> [RFR] Adding disable metrics test

- cypress/e2e/tests/migration/dynamic-report/dependencies/mta_2008_validation.test.ts
> [RFR] MTA-2008: implemented bug validation

- cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts
> [RFR] Add bug marker for discarding application assessment test

- cypress/e2e/tests/migration/applicationinventory/assessment/assessment_after_import.test.ts
> [RFR] Add bug marker for assessment after import tests

- cypress/e2e/tests/migration/applicationinventory/applications/pagination.test.ts
- cypress/e2e/tests/migration/applicationinventory/applications/sort.test.ts
applying force reload fixed the JF
JF - [report portal sort test](https://reportportal-migration-qe.apps.ocp-c1.prod.psi.redhat.com/ui/#mta/launches/all/5717/299914?item0Params=filter.cnt.name%3Dapplication%2520inv%26page.page%3D1)
[report portal pagination test](https://reportportal-migration-qe.apps.ocp-c1.prod.psi.redhat.com/ui/#mta/launches/all/5717/299987?item0Params=filter.cnt.name%3Dapplication%2520inv%26page.page%3D1)
[Jenkins run sort test](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/2538/)
[jenkins run pagination test](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/2543/console)
> [RFR] fix JF - application inventory sort and pagination tests

- cypress/e2e/tests/migration/applicationinventory/applications/sort.test.ts
> [RFR] [JF] Update application sort tests

- cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts
two bugs in mta7.0.3 causing these two tests to fail
> [RFR] assessment - miscellaneous mark two bugs

- cypress/e2e/tests/rbac/disable_keycloak.test.ts
- cypress/utils/utils.ts
[Jenkins run from upstream ](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/tackle-ui-tests-on-ocp/678/)
Results : pass
> [RFR] Test few operations after disabling Keycloak 

- cypress/e2e/tests/migration/applicationinventory/assessment/assess_review.test.ts
Solves [MTA-2494](https://issues.redhat.com/browse/MTA-2494) by removing the bug mark of the test as it is passing already locally and on Jenkins.
https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/2580/console
> [RFR] [JF] emove assess bug mark

- cypress/e2e/tests/migration/dynamic-report/issues/filter.sorting.pagination.test.ts
one failing test due to a bug 
[Jenkins run
](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/2584/console)[report portal fail](https://reportportal-migration-qe.apps.ocp-c1.prod.psi.redhat.com/ui/#mta/launches/all/5717/299943/299958/log?item0Params=filter.cnt.name%3Dfiltering%26page.page%3D1&item1Params=filter.eq.hasStats%3Dtrue%26filter.eq.hasChildren%3Dfalse%26filter.in.type%3DSTEP%26filter.in.status%3DFAILED%252CINTERRUPTED)
> [RFR] fix JF - migration/dynamic-report/issues/filter.sorting.pagination.test.ts

- cypress/e2e/tests/migration/applicationinventory/applications/pagination.test.ts
- cypress/e2e/tests/migration/applicationinventory/manageimports/sort.test.ts
Removing the HTTP intercept from the beforeEach() hook since we don't need to wait on the network request to finish . Applications are created as part of the test set up  and no new apps are created in between the tests .
> [RFR] [JF] Update manageimport sort tests and app pagination tests

- cypress/e2e/models/migration/migration-waves/migration-wave.ts
- cypress/e2e/tests/migration/migration-waves/export_to_jira_datacenter.test.ts
Solves [MTA-2526](https://issues.redhat.com/browse/MTA-2526) by applying small fixes to the jira datacenter export test
Jenkins run [#2626](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/2626/console)
> [RFR] [JF] Fix jira datacenter export test

- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/archetype_association.test.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts
[Jenkins job for archetype association](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/2598/)
Results : pass
> [RFR] Verify Assessment and Review inheritance status

- cypress/e2e/models/administration/custom-migration-targets/custom-migration-target.ts
- cypress/e2e/tests/administration/custom-migration-targets/crud.test.ts
Resolve: https://issues.redhat.com/browse/MTA-2538
Jenkins run:
https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/2674/console
> [RFR] Fix JF for Custom Migration Targets CRUD operations

- cypress/e2e/tests/migration/dynamic-report/issues/filter.sorting.pagination.test.ts
- cypress/e2e/views/issue.view.ts
- cypress/fixtures/analysis.json
[Run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/2710/console) is failing only where it is expected (known bugs)
> [RFR] TC MTA-461 - sorting in issues affected files

- cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis_without_creds.test.ts
- cypress/fixtures/analysis.json
> [RFR][JF] Fix JF for Source Analysis without credentials

- cypress/e2e/tests/rbac/review-assessment.test.ts
> [RFR] Delete tags as part of clean up

- cypress/e2e/models/migration/archetypes/archetype.ts
- cypress/e2e/tests/migration/archetypes/miscellaneous.test.ts
- cypress/e2e/views/archetype.view.ts
I'll update results from the Jenkins run shortly.
> [RFR] Verify associated application count and link for archetypes

- cypress/e2e/tests/migration/applicationinventory/analysis/affected_files.test.ts
- cypress/e2e/tests/migration/applicationinventory/analysis/custom-rules.test.ts
modified:   cypress/e2e/tests/migration/applicationinventory/analysis/affected_files.test.ts
modified:   cypress/e2e/tests/migration/applicationinventory/analysis/custom-rules.test.ts
> [RFR][JF] Fixed affected files and custom rules in analyses test cases

- cypress/e2e/models/migration/dynamic-report/dependencies/dependencies.ts
- cypress/e2e/tests/migration/dynamic-report/dependencies/filter.test.ts
This failure was caused by UI change cause now name filter is checkbox list instead of usual text input. Adopted to this and removed old negative test as not relevant any more.
> [RFR] Fixed filtering dependencies by name

- cypress/e2e/tests/migration/applicationinventory/analysis/load_analysis.test.ts
- cypress/e2e/tests/migration/reports-tab/filter.test.ts
- cypress/fixtures/analysis.json
Solves [MTA-2636](https://issues.redhat.com/browse/MTA-2636) in `cypress/fixtures/analysis.json`
> [RFR] [JF] minor fixes

- cypress/e2e/tests/migration/archetypes/miscellaneous.test.ts
I'm addressing the change in Assessment retake behavior through this PR. This change was introduced in MTA 7.0.3-15 (April 11th build)
> [RFR] Fix Archetype assessment retake failure

- cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts
> [RFR] Update Retake assessment test

- cypress/e2e/tests/migration/migration-waves/export_to_jira_datacenter.test.ts
the test was failing due to ` expect(waveIssues).to.have.length(2);` returning empty array
this is likely a system issue because the test was passing some times and failing other times
for now i just added trim() to the boolean check which should add more validations but not necessarily relevant to the fail -> for now Jenkins passed three times in a row 
removed toLowerCase() as requested
jenkins [run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/2815/console)
JF [Report portal](https://reportportal-migration-qe.apps.ocp-c1.prod.psi.redhat.com/ui/v1/#mta/launches/all/5815/311060)
> [RFR] JF - migrationwaves/export to jira datacenter test

- cypress/e2e/tests/migration/applicationinventory/applications/interlinked.test.ts
> [RFR] Delete tags in app interlinked tests

- cypress/e2e/tests/migration/dynamic-report/issues/filter.sorting.pagination.test.ts
- cypress/fixtures/analysis.json
- cypress/utils/utils.ts
Passing Jenkins job (except known bugs) is [here](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/2828/console)
> [RFR] Refactored issues filtering by name

- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts
There is a change in behavior in MTA 7.0.3-18 and MTA now distinguishes between unassessed applications and applications  assessed with 'Unkown' risk . This PR addresses these changes.
> [RFR] Fix assessment failures

- cypress/e2e/tests/migration/reports-tab/reports.test.ts
Bug: https://issues.redhat.com/browse/MTA-2676
> [RFR] Added bug number MTA-2676

- cypress/e2e/tests/migration/applicationinventory/applications/filter.test.ts
https://issues.redhat.com/browse/MTA-2652
> [RFR] mark bug for risk filter validations

- cypress/e2e/tests/migration/controls/tags/tagcategory/filter.test.ts
- cypress/utils/utils.ts
Resolves https://issues.redhat.com/browse/MTA-2668 
[Jenkins run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/2852/console)
> [RFR][JF] Fix JF for Tag tagCategory filter validations

- cypress/e2e/tests/migration/applicationinventory/assessment/archetype_association.test.ts
> [RFR] Fix archetype association

- cypress/e2e/tests/migration/controls/tags/tagcategory/pagination.test.ts
Resolves https://issues.redhat.com/browse/MTA-2673
> [RFR][JF] Fix JF for Tag category pagination validations

- cypress/e2e/tests/migration/controls/tags/tagcategory/pagination.test.ts
- cypress/e2e/tests/migration/controls/tags/tagcategory/sort.test.ts
Resolves https://issues.redhat.com/browse/MTA-2670
> [RFR][JF] Fix JF for Tag category sort validations

- cypress/e2e/tests/administration/custom-migration-targets/crud.test.ts
Solves [MTA-2674](https://issues.redhat.com/browse/MTA-2674)
> [RFR] Fix custom migration targets crud test

- cypress/e2e/models/migration/dynamic-report/issues/issues.ts
- cypress/e2e/tests/migration/dynamic-report/issues/filter.sorting.pagination.test.ts
- cypress/fixtures/analysis.json
- cypress/utils/utils.ts
> [RFR] Refactored filter function to get multiple values

- cypress/e2e/models/migration/dynamic-report/dependencies/dependencies.ts
- cypress/e2e/tests/migration/dynamic-report/dependencies/filter.test.ts
- cypress/fixtures/analysis.json
[Job](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/2868/console) passed
> [RFR] Refactored dependencies filtering by name

- cypress/e2e/tests/migration/reports-tab/filter.test.ts
> [RFR] Remove bug mark

- cypress/e2e/tests/migration/applicationinventory/assessment/assessment_after_import.test.ts
- cypress/utils/utils.ts
This PR addresses 
1) [MTA-2770](https://issues.redhat.com/browse/MTA-2770)
2) [MTA-2776](https://issues.redhat.com/browse/MTA-2776)
3) [MTA-2775](https://issues.redhat.com/browse/MTA-2775)
4) [MTA-2774](https://issues.redhat.com/browse/MTA-2774)
5) [MTA-2771](https://issues.redhat.com/browse/MTA-2771)
> [RFR] Fix app import tests 

- cypress/e2e/tests/migration/controls/tags/tagcategory/pagination.test.ts
- cypress/e2e/tests/migration/controls/tags/tagcategory/sort.test.ts
Bug is fixed removed the bug no. from tests
> [RFR] Remove bug MTA-2681 from tests

- cypress/e2e/tests/upgrade/after_upgrade.test.ts
- cypress/e2e/tests/upgrade/create_upgrade_data.test.ts
- cypress/e2e/types/types.ts
- cypress/fixtures/upgrade-data.json
Import a questionnaire, do assessment and see if migrated correctly after upgrade
> [RFR] Added upgrade test

- cypress/e2e/models/migration/applicationinventory/assessment.ts
1) I'm not too keen on increasing the timeout , but the tests passed after the timeout was increased .
I've also reported this [Bug](https://issues.redhat.com/browse/MTA-2784)
2) This resolves [JF MTA-2773](https://issues.redhat.com/browse/MTA-2773)
> [RFR] Increase timeout for questionnaire to be listed while taking assessment

- cypress/e2e/tests/migration/applicationinventory/applications/dependency.test.ts
> [RFR] mark bug for cyclic dependencies for applications test

- cypress/e2e/tests/administration/questionnaires/miscellaneous.test.ts
> [RFR] added bug marker for Import invalid questionnaire

- cypress/e2e/tests/administration/questionnaires/crud.test.ts
Both failing tests have the same bug, so I updated them in the same PR
> [RFR] added bug marker for questionnaire CRUD tests

- cypress/e2e/tests/migration/applicationinventory/applications/import.test.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/review/filter.test.ts
> [RFR] Remove bug markers for Review filter and app import tests

- cypress/e2e/models/migration/applicationinventory/analysis.ts
- cypress/e2e/tests/migration/applicationinventory/analysis/custom-rules.test.ts
- cypress/e2e/views/analysis.view.ts
- cypress/fixtures/analysis.json
TA https://issues.redhat.com/browse/MTA-2462
[Jenkins Run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/2959/console)
> [RFR][TA]Verify a file is not a valid XML Test case

- cypress/e2e/tests/migration/applicationinventory/assessment/review/filter.test.ts
1) We were proceeding with the tests without making sure assessment was complete .With these changes, the tests will fail early . 
2) The tests will occasionally hit [bug MTA-2784](https://issues.redhat.com/browse/MTA-2784)
> [RFR] Add few checks to risk filter validation tests

- cypress/e2e/tests/migration/reports-tab/links-validation.test.ts
> [RFR] mark bug for identified risks links validation

- cypress.config.ts
- cypress/e2e/tests/upgrade/after_upgrade.test.ts
- cypress/e2e/tests/upgrade/create_upgrade_data.test.ts
- cypress/e2e/types/types.ts
- cypress/fixtures/upgrade-data.json
- cypress/support/e2e.js
- package-lock.json
- package.json
Jenkins run:
https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/2992/
> mta_7.0.2: Updating upgrade tests with the recent changes

- cypress/e2e/tests/upgrade/after_upgrade.test.ts
- cypress/utils/utils.ts
Jenkins run:
https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/2999/
> Increasing timeout in upgrade testing

- cypress/e2e/models/migration/applicationinventory/assessment.ts
- cypress/e2e/tests/migration/applicationinventory/applications/interlinked.test.ts
- cypress/e2e/views/assessment.view.ts
- Update stakeholder dropdown in assessment wizard to reflect changes in https://github.com/konveyor/tackle2-ui/pull/1799
> :ghost: Update tests to reflect new UI changes

- cypress/e2e/tests/migration/migration-waves/field_validation.test.ts
Solves [MTA-2869](https://issues.redhat.com/browse/MTA-2869)
> [RFR] Fix migration waves field validation test

- cypress/e2e/tests/migration/applicationinventory/analysis/static_report.test.ts
Solves [MTA-2891](https://issues.redhat.com/browse/MTA-2891) by marking the test with Bug https://github.com/konveyor/tackle2-hub/issues/636
> [RFR] [JF] Mark static report bug

- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/tests/migration/dynamic-report/issues/filter.sorting.pagination.test.ts
> [RFR] Fixed sorting by efforts in affected applications

- cypress/e2e/tests/migration/applicationinventory/assessment/questionnaire_features.test.ts
changed function name
**[Jenkins run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/tackle-ui-tests-on-ocp/700/console)**
> [RFR] [JF] fix questionnaire_assesment

- cypress/e2e/views/applicationinventory.view.ts
Resolves [JF MTA-2875](https://issues.redhat.com/browse/MTA-2875)
> [RFR] [JF] Fix tag filtering for applications

- cypress/e2e/models/migration/applicationinventory/manageImports.ts
- cypress/e2e/views/applicationinventory.view.ts
Resolves [JF MTA-2883 ](https://issues.redhat.com/browse/MTA-2883)
> [RFR] [JF] Update Manageimports.open() method

- cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
- cypress/fixtures/analysis.json
modified:   cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
> [RFR] Source analysis upstream fixes

- cypress/e2e/tests/administration/repository/maven.test.ts
> [RFR] Marked bug MTA-2925

- cypress/e2e/tests/administration/credentials/maven_crud.test.ts
- cypress/e2e/tests/migration/applicationinventory/applications/manage_credentials_many_apps.test.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/questionnaire_features.test.ts
- cypress/e2e/tests/migration/archetypes/questionnaire_features.test.ts
- cypress/e2e/tests/migration/reports-tab/archetype_association.test.ts
- cypress/e2e/tests/migration/reports-tab/links-validation.test.ts
- cypress/e2e/tests/migration/reports-tab/sort.test.ts
- cypress/e2e/tests/rbac/upload_binary_analysis_architect.test.ts
- cypress/e2e/tests/rbac/upload_binary_analysis_migrator.test.ts
Solves [MTA-2924](https://issues.redhat.com/browse/MTA-2924)
> [RFR] Change duplicated suite names

- cypress/e2e/models/migration/archetypes/archetype.ts
- cypress/e2e/tests/migration/archetypes/assess_review.test.ts
1) Archetype Assessment and Review status columns have been added to Konveyor recently.
2) [Jenkins job](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/tackle-ui-tests-on-ocp/727/)
> [RFR] Verify archetype assessment/review status

- cypress/e2e/models/migration/applicationinventory/assessment.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/archetype_association.test.ts
> [RFR] Uncapitalize risk value

- cypress/e2e/tests/rbac/custom-rules.test.ts
- cypress/fixtures/custom-rules.json
Solves [MTA-2943](https://issues.redhat.com/browse/MTA-2943)
Jenkins run [3045](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/3045/console)
> [RFR] Adapt custom rules test

- cypress/e2e/tests/migration/archetypes/questionnaire_features.test.ts
[Jenkins job ](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/tackle-ui-tests-on-ocp/737)
Results: pass
> [RFR] [JF] Fix archetype questionnaire feature tests

- cypress/e2e/models/migration/applicationinventory/assessment.ts
> [RFR] Assessment with unknown risk

- cypress/e2e/tests/upgrade/create_upgrade_data.test.ts
`mtaVersion` instead of `sourceMtaVersion`
> Fixed upgrade test to look for the correct variable

- cypress/e2e/tests/migration/applicationinventory/assessment/archetype_association.test.ts
> [RFR] Verify archetype assessment/review status with multiple questionnaires

- cypress/e2e/tests/migration/reports-tab/links-validation.test.ts
> [RFR] Fix link validation test under Reports tab

- cypress/e2e/tests/migration/applicationinventory/analysis/tag_filter.test.ts
- cypress/fixtures/analysis.json
marked a bug that is causing the test to fail
modified relevant analysis data for the test
> [RFR] [JF] mark bug and modify relevant analysis data for tag_filter test

- cypress/e2e/models/migration/controls/businessservices.ts
- cypress/e2e/tests/migration/controls/businessservices/create.test.ts
- cypress/e2e/views/common.view.ts
Relates to: https://github.com/konveyor/tackle2-ui/pull/1921
> [RFR] Business services table update

- cypress/e2e/tests/migration/archetypes/miscellaneous.test.ts
> [RFR] [JF] Update archetype discard assessment & review tests

- cypress/utils/utils.ts
Resolves [7.1 JF](https://issues.redhat.com/browse/MTA-3058)
> [RFR] Update deleteAllBusinessServices() fn

- cypress/e2e/tests/migration/reports-tab/sort.test.ts
> [RFR] [JF] Fix Reports tab sort test

- cypress/e2e/models/migration/migration-waves/migration-wave.ts
Solves [MTA-3081](https://issues.redhat.com/browse/MTA-3081)
> [RFR] Adapt export to jira cloud test

- cypress/e2e/tests/migration/migration-waves/export_to_jira_datacenter.test.ts
Solves [MTA-3018](https://issues.redhat.com/browse/MTA-3081)
Due to changes occurring on the Jira stage server, it is common for us to lose permissions on the token for archiving issues. Therefore, I have disabled issue archiving.
Since the API sorts issues by creation date, the presence of other issues will not pose a problem for the test to find the newly created ones.
---
Jenkins run [3186](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/3186/)
> [RFR] Remove issues deletion

- cypress/e2e/tests/migration/applicationinventory/applications/manage_columns.test.ts
- cypress/e2e/views/applicationinventory.view.ts
- cypress/e2e/views/common.view.ts
- cypress/utils/utils.ts
automates [polarion](https://polarion.engineering.redhat.com/polarion/#/project/MTAPathfinder/workitem?id=MTA-537)
[jenkins](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/3187/console)
> [RFR] [Application Inventory] - automate manage columns

- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/models/migration/applicationinventory/assessment.ts
Reference-Url: https://github.com/konveyor/tackle2-ui/pull/1985
> Use closest Tr tag when searching by app name

- cypress/e2e/tests/migration/controls/businessservices/pagination.test.ts
- cypress/utils/utils.ts
this change shouldnt affect other pagination tests
[jenkins](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/3224/console)
[jira JF 
](https://issues.redhat.com/browse/MTA-3079)
> [RFR] [JF] fix business service pagination

- cypress/e2e/tests/migration/applicationinventory/applications/manage_columns.test.ts
- cypress/e2e/types/constants.ts
- cypress/e2e/views/applicationinventory.view.ts
- cypress/utils/utils.ts
[jenkins](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/3226/console)
> [RFR] enhance manage columns test and add cancel button validations

- cypress/e2e/models/migration/applicationinventory/analysis.ts
Resolves https://issues.redhat.com/browse/MTA-3061
[Jenkins run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/3228/console)
> [RFR] Fix for Source analysis test case

- cypress/e2e/tests/migration/applicationinventory/applications/filter.test.ts
- cypress/utils/utils.ts
all filter tests (all relevant filter tests passed):
https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/3229/
questionnaire filter test (failed because of local cluster data -> passed after cleaning:)
https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/3235/console
application inventory filtering has been modified so refactored the method applySearchFilter to work with the changes
modified "isSpecialKnownFilter
applied changes to filter.test
markes 2 bugs
[jenkins : ](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/3221/console)
fixes JF [3203](https://issues.redhat.com/browse/MTA-3203)
> [RFR] [JF] - fix application filter validation 

- cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis_without_creds.test.ts
> [RFR] Removed analysis test from tier0 by devs request

- cypress/utils/utils.ts
Solves [MTA-3076](https://issues.redhat.com/browse/MTA-3076).
I triggered a jenkins run of all the sort tests in our repository, to ensure that everything still work as expected.
Jenkins run [3259](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/3259/console)
> [RFR] Fix sort tests

- cypress/e2e/models/migration/dynamic-report/dependencies/dependencies.ts
- cypress/e2e/tests/migration/dynamic-report/dependencies/filter.test.ts
- cypress/fixtures/analysis.json
Jenkins [job](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/3263/console) passed
> [RFR] Fixed dependencies filtering

- cypress/e2e/tests/administration/credentials/filter.test.ts
after discussion with the devs, returned the TC and marked the bug
> [RFR] mark bug and return the TC in credentials filter

- cypress/e2e/models/migration/task-manager/task-manager.ts
- cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis_without_creds.test.ts
- cypress/e2e/types/constants.ts
- cypress/e2e/views/taskmanager.view.ts
> [RFR] Initial commit for task manager testing

- cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts
[Jenkins job ](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/3301/)
Results : passed
> [RFR] Update app name in misc assessment test

- cypress/e2e/tests/administration/custom-migration-targets/crud.test.ts
- cypress/e2e/tests/custom-metrics/analysis_metrics.test.ts
https://issues.redhat.com/browse/MTA-3308
https://issues.redhat.com/browse/MTA-3320
> [RFR] Added bug markers

- cypress/e2e/tests/administration/repository/maven.test.ts
remove bug marker, irrelevant comments
**[Jenkins run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/3315/console)**
> [RFR] Fix maven.test.ts

- cypress/e2e/tests/administration/repository/subversion.test.ts
- cypress/e2e/views/analysis.view.ts
- cypress/utils/utils.ts
**[Jenkins run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/3311/console)**
> [RFR] fix svn.test.ts TC

- cypress/e2e/tests/migration/archetypes/questionnaire_features.test.ts
> [RFR] Bug marker for 7.1 questionnaire auto tag bug

- cypress/e2e/tests/migration/reports-tab/archetype_association.test.ts
[Jenkins run ](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/3368/)
Results : pass
> [RFR] Fix archetype association test in reports-tab folder

- cypress/e2e/tests/migration/applicationinventory/applications/filter.test.ts
- cypress/e2e/views/common.view.ts
- cypress/utils/utils.ts
i wasn't able to reuse existing filtering functions due to the new nature of  filtering so i added a function const
added to filter function clear all filters at first because some tests were failing if before tests contains a bug and failed the filter well remain so just a more validation
https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/3358/console
> [RFR] adjust TC filtering by substring in application inventory

- cypress/e2e/models/migration/applicationinventory/analysis.ts
> [RFR] Fixed analysis after UI changes in build 35

- cypress/e2e/tests/migration/dynamic-report/issues/filter.sorting.pagination.test.ts
> [RFR] Fixed last failing tests in issues

- cypress/e2e/tests/migration/applicationinventory/applications/language_discovery.test.ts
- cypress/e2e/views/applicationinventory.view.ts
- cypress/fixtures/application.json
**[Jenkins run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/3421/console)**
> [RFR] Automate TC MTA-586

- cypress/e2e/models/migration/archetypes/archetype.ts
adjust getAssociatedAppsCount() to new modified html
[jenkins](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/3424/console)
> [RFR] [JF] fix interlinked applications TC fail

- cypress/e2e/tests/migration/applicationinventory/applications/manage_credentials_many_apps.test.ts
Removed interception as respective API call doesn't exist anymore
> [RFR] Fixed manage credentials for many apps

- cypress/e2e/tests/migration/applicationinventory/assessment/questionnaire_features.test.ts
[Jenkins job](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/3442/)
> [RFR] Fix questionnaire auto answer feature for applications(7.1)

- cypress/e2e/tests/migration/applicationinventory/applications/filter.test.ts
- cypress/e2e/tests/migration/reports-tab/links-validation.test.ts
links validation test: https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/3495/
filter applications test: https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/3498/console
> [RFR] remove bug mark and adjust test

- cypress/e2e/tests/migration/applicationinventory/assessment/archetype_association.test.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts
Resolves https://issues.redhat.com/browse/MTA-3614
> [RFR] Fix JF for Tests related to application-archetype association

- cypress/e2e/tests/migration/archetypes/questionnaire_features.test.ts
> [RFR] Add bug ID to archetype questionnaire feature test

- cypress/e2e/tests/custom-metrics/analysis_metrics.test.ts
https://issues.redhat.com/browse/MTA-3320 was closed as not a bug
Ticket to modify test case: https://issues.redhat.com/browse/MTA-3492 
Jenkins run: https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/3459/console
> Fixed analysis_metrics.test.ts

- cypress/e2e/tests/migration/applicationinventory/assessment/questionnaire_features.test.ts
> [RFR] Mark bug for application questionnaire test

- cypress/e2e/tests/migration/applicationinventory/applications/manage_credentials_many_apps.test.ts
- cypress/fixtures/analysis.json
> [RFR] Fix analysis.json issues

- cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
- cypress/e2e/tests/migration/applicationinventory/analysis/upload_binary_analysis.test.ts
- cypress/fixtures/analysis.json
modified:   cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
> [RFR] Replace Story point to Efforts

- cypress/e2e/tests/upgrade/after_upgrade.test.ts
- cypress/e2e/tests/upgrade/create_upgrade_data.test.ts
- cypress/fixtures/upgrade-data.json
Jenkins run: https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-upgrade/216/
> [RFR]Added admin user to perform post-upgrade tests

- cypress/e2e/tests/migration/applicationinventory/applications/language_discovery.test.ts
- cypress/e2e/views/menu.view.ts
- cypress/fixtures/application.json
**[Jenkins Run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/3577/console)**
> [RFR] Automate TC 582

- cypress/e2e/tests/migration/applicationinventory/applications/language_discovery.test.ts
- cypress/fixtures/application.json
- cypress/fixtures/language_discovery.json
**[Jenkins run 1](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/3579/console)**
**[Jenkins run 2](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/3586/console)**
Automates TCs 582, 583, 584, 585, 585, 586, 587
> [RFR] Automate TC-583

- cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
- cypress/fixtures/analysis.json
Automates https://issues.redhat.com/browse/MTA-2981
> [RFR][TA] Automate Close-loop bug MTA-2973

- cypress/e2e/models/migration/applicationinventory/analysis.ts
- cypress/e2e/views/common.view.ts
Fixes analysis test 
[Jenkins Run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/3613/console)
> [RFR] Fixes Analysis Test cases

- dockerfiles/interop/Dockerfile
- package-lock.json
- package.json
Jenkins run: https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/3616/
> Cherry-pick: Upgrade cypress version to 13.13.3 (#1202)

- cypress/e2e/models/administration/custom-migration-targets/custom-migration-target.ts
- cypress/e2e/models/migration/applicationinventory/analysis.ts
- cypress/e2e/tests/administration/custom-migration-targets/crud.test.ts
- cypress/e2e/views/analysis.view.ts
- cypress/e2e/views/custom-migration-target.view.ts
Solves [MTA-3672](https://issues.redhat.com/browse/MTA-3672)
> [RFR] Fix custom migration crud test

- cypress/e2e/tests/migration/reports-tab/links-validation.test.ts
Solves [MTA-3696](https://issues.redhat.com/browse/MTA-3696)
> [RFR] Fix Reports links validation test

- cypress/e2e/tests/administration/custom-migration-targets/crud.test.ts
- cypress/e2e/views/custom-migration-target.view.ts
- cypress/support/commands.ts
- cypress/support/e2e.ts
- package-lock.json
- package.json
- tsconfig.json
Solves [MTA-3725](https://issues.redhat.com/browse/MTA-3725)
> [RFR] Update custom migration target crud dnd dependency

- cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
- cypress/e2e/tests/migration/applicationinventory/analysis/upload_binary_analysis.test.ts
- cypress/fixtures/analysis.json
For Upload_binary tests [jenkins run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/3720/console)
> [RFR] Fix upload binary

- cypress/e2e/models/migration/task-manager/task-manager.ts
- cypress/e2e/tests/migration/task-manager/sorting.filter.pagination.test.ts
- cypress/e2e/types/constants.ts
- cypress/e2e/views/taskmanager.view.ts
> [RFR] Task manager sorting TC

- cypress/e2e/models/migration/controls/stakeholders.ts
- cypress/utils/utils.ts
Relates to: https://github.com/konveyor/tackle2-ui/pull/1923
> [RFR] Update Stakeholders edit and delete actions

- cypress/e2e/models/administration/custom-migration-targets/custom-migration-target.ts
> [RFR] Fixed drag n drop issue

- cypress/e2e/models/migration/archetypes/archetype.ts
Relates to: https://github.com/konveyor/tackle2-ui/pull/2098
> Updated archetype edit action

- cypress/e2e/models/migration/archetypes/archetype.ts
Reverts konveyor/tackle-ui-tests#1225
> Revert "Updated archetype edit action"

- cypress/e2e/tests/migration/controls/stakeholders/pagination.test.ts
Resolves: https://issues.redhat.com/browse/MTA-3824
> Fix /migration/controls/stakeholders/pagination.test.ts

- cypress/e2e/tests/migration/applicationinventory/analysis/upload_binary_analysis.test.ts
- cypress/fixtures/analysis.json
> Fix Uplaod Binary Test Case

- cypress/fixtures/analysis.json
> [RFR][JF] Update acmeair-app effort

- cypress/e2e/tests/migration/applicationinventory/analysis/custom-rules.test.ts
- cypress/fixtures/analysis.json
- cypress/fixtures/application.json
- cypress/fixtures/yaml/python-rules.yaml
added TC for python custom rule analysis
**[Jenkins run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/3793/console)**  <-- it's failing becuse of bug MTA-2015
Local run :
> [RFR] Automate_TC MTA-3756

- cypress/e2e/models/migration/controls/stakeholdergroups.ts
Relates to UI change: https://github.com/konveyor/tackle2-ui/pull/2095
> [RFR] Modifying edit and delete functions according the UI change

- cypress/e2e/tests/migration/applicationinventory/analysis/binary_analysis.test.ts
- cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
- cypress/e2e/tests/migration/applicationinventory/analysis/upload_binary_analysis.test.ts
- cypress/fixtures/analysis.json
Resolves https://issues.redhat.com/browse/MTA-3852 
Binary analysis: [Jenkins Run Succeeded](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/3810/) 
[Upload Binary Jenkins Run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/3812/)
[Source Analysis Jenkins run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/3813/)
> [RFR] Replace Story points to efforts and update the effort value

- cypress/e2e/models/migration/applicationinventory/analysis.ts
- cypress/e2e/tests/migration/applicationinventory/analysis/custom-rules.test.ts
- cypress/e2e/types/types.ts
- cypress/e2e/views/analysis.view.ts
- cypress/fixtures/analysis.json
- cypress/utils/utils.ts
Automates: https://issues.redhat.com/browse/MTA-2003
Resolves: https://issues.redhat.com/browse/MTA-2493
Jenkins run: https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/3817/console
* Regression bug found during testing: https://issues.redhat.com/browse/MTA-3863
> Verifying number of rules when uploading file

- cypress/e2e/models/migration/applicationinventory/analysis.ts
- cypress/e2e/tests/migration/applicationinventory/analysis/custom-rules.test.ts
- cypress/fixtures/analysis.json
- cypress/fixtures/xml/basic-custom-rule.xml
- cypress/utils/utils.ts
Solves [MTA-3864](https://issues.redhat.com/browse/MTA-3864)
> [RFR] Update custom rule test

- cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
- cypress/fixtures/analysis.json
> [RFR] Update effort for Source + dependencies analysis on daytrader app

- cypress/e2e/models/migration/applicationinventory/analysis.ts
- cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis_without_creds.test.ts
Automates https://issues.redhat.com/browse/MTA-4011 
[Jenkins Run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/3839/console)
> [RFR][TA] Cancel analysis and validation

- cypress/e2e/tests/migration/applicationinventory/analysis/upload_binary_analysis.test.ts
Fixes https://issues.redhat.com/browse/MTA-3889
> [RFR][JF] Remove dc tag from upload binary test case

- cypress/e2e/tests/migration/applicationinventory/analysis/static_report.test.ts
> [RFR] Remove bug number

- cypress/e2e/tests/migration/applicationinventory/analysis/static_report.test.ts
Solves [MTA-4516](https://issues.redhat.com/browse/MTA-4156) by adapting the static reports test to the UI changes.
> [RFR] Adapt static report test

- cypress/e2e/models/migration/controls/jobfunctions.ts
Related to https://github.com/konveyor/tackle2-ui/pull/2101
> [RFR] Test of Add 'ActionsColumn to Job Functions table #2101'

- cypress/e2e/tests/migration/archetypes/miscellaneous.test.ts
> [RFR] Update associated app count test for archetypes

- cypress/e2e/models/migration/controls/jobfunctions.ts
Reverts konveyor/tackle-ui-tests#1249
> Revert "[RFR] Test of Add 'ActionsColumn to Job Functions table #2101'"

- cypress/e2e/tests/migration/applicationinventory/analysis/custom-rules.test.ts
[Jenkins Run](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/3959/console)
> [RFR][JF] Remove bug number

- cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
- cypress/e2e/tests/migration/controls/stakeholdergroups/pagination.test.ts
> [RFR][JF] Fix Stakeholdergroup's pagination test

- cypress/e2e/tests/migration/applicationinventory/analysis/static_report.test.ts
Solves [MTA-4204](https://issues.redhat.com/browse/MTA-4204)
Jenkins run: [3964](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/3964/console)
> [RFR] Fix static report test

- cypress/e2e/tests/migration/applicationinventory/applications/interlinked.test.ts
[Jenkins run ](https://main-jenkins-csb-migrationqe.apps.ocp-c1.prod.psi.redhat.com/job/mta/job/mta-ui-tests-runner/3981/)
[Resolves JF](https://issues.redhat.com/browse/MTA-4202)
> [RFR] Update app interlinked test

- package-lock.json
Resolves https://github.com/konveyor/tackle-ui-tests/issues/1266
> [RFR] Update package-lock.json

- cypress/e2e/tests/administration/credentials/sourcecontrol_crud.test.ts
Resolves https://issues.redhat.com/browse/MTA-3580
> [RFR] Modify source control crud test

- cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
Resolves https://issues.redhat.com/browse/MTA-4241
> [RFR][JF] Add bug number to source analysis

- cypress/e2e/tests/rbac/review-assessment.test.ts
- cypress/utils/utils.ts
1. Added logout in last test to make sure login window will appear in "After all"
2. Added additional timeout in login function before entering credentials, sometimes page doesn't render quickly if doing logout/login quickly
> [RFR] Fix for review assessment as architect

- cypress/e2e/tests/migration/dynamic-report/issues/filter.sorting.pagination.test.ts
- cypress/fixtures/analysis.json
- cypress/utils/utils.ts
Passes all except one that fails due to a known bug
> [RFR] Update analysis json

- cypress/e2e/models/migration/applicationinventory/analysis.ts
- cypress/e2e/views/analysis.view.ts
changed `Analysis details` to `/analysis details$/i`
> [JF][RFR] Fix svn test case missing button locator

- cypress/e2e/tests/migration/applicationinventory/applications/import.test.ts
> [RFR] Remove bug marker for app import test

- cypress/e2e/tests/migration/dynamic-report/issues/filter.sorting.pagination.test.ts
> [RFR] Skipping filtering, sorting and pagination for issues

- cypress/e2e/tests/migration/applicationinventory/applications/filter.test.ts
> [RFR] MTA 7.1.1 - Fix app risk filter test

- cypress/e2e/models/migration/task-manager/task-manager.ts
- cypress/e2e/tests/migration/task-manager/sorting.filter.pagination.test.ts
- cypress/e2e/tests/migration/task-manager/task_details.test.ts
- cypress/e2e/types/constants.ts
Resolves: https://issues.redhat.com/browse/MTA-3375
Jenkins run: https://jenkins-csb-migrationqe-main.dno.corp.redhat.com/job/mta/job/tackle-ui-tests-pr-tester/job/PR-1299/1/console
> [RFR] Task manager: Open task details from right kebab menu

- cypress/e2e/tests/migration/applicationinventory/analysis/affected_files.test.ts
- cypress/fixtures/analysis.json
- cypress/fixtures/application.json
Automate ticket https://issues.redhat.com/browse/MTA-4302 
Bug https://issues.redhat.com/browse/MTA-4024 
[Jenkins Run](https://jenkins-csb-migrationqe-main.dno.corp.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/4223/console)
> [RFR][TA] Automate cool store bug_MTA_4024

- cypress/utils/utils.ts
> [RFR] MTA 7.1.1 Fix upgrade test - MTA Operator Log

- cypress/e2e/models/migration/controls/stakeholdergroups.ts
- cypress/e2e/tests/migration/applicationinventory/applications/interlinked.test.ts
Backport [PR 1261](https://github.com/konveyor/tackle-ui-tests/pull/1261)
> [RFR] 7.1.1 - Update App interlinked test

- cypress/e2e/tests/migration/applicationinventory/analysis/affected_files.test.ts
- cypress/fixtures/analysis.json
Automate ticket https://issues.redhat.com/browse/MTA-4413
Bug https://issues.redhat.com/browse/MTA-4025
[Jenkins Run](https://jenkins-csb-migrationqe-main.dno.corp.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/4234/)
> [RFR][TA] Automate cool store bug_MTA_4025

- cypress/e2e/tests/migration/archetypes/miscellaneous.test.ts
> [RFR] Update archetype misc test

- cypress/e2e/models/migration/task-manager/task-manager.ts
- cypress/e2e/tests/migration/task-manager/task_details.test.ts
- cypress/e2e/views/common.view.ts
- cypress/e2e/views/taskmanager.view.ts
- cypress/utils/utils.ts
Resolves: https://issues.redhat.com/browse/MTA-3325
Jenkins run: https://jenkins-csb-migrationqe-main.dno.corp.redhat.com/blue/organizations/jenkins/mta%2Ftackle-ui-tests-pr-tester/detail/PR-1302/1/pipeline
> [RFR] Tasks: download task details

- cypress/e2e/tests/migration/task-manager/task_manager.test.ts
Resolves: https://issues.redhat.com/browse/MTA-4428
Jenkins run: https://jenkins-csb-migrationqe-main.dno.corp.redhat.com/view/Konveyor/job/mta/job/tackle-ui-tests-pr-tester/view/change-requests/job/PR-1304/2/console
> [RFR] Task manager: Create a binary app - no discovery task is trigerred

- cypress/e2e/tests/migration/task-manager/manage_columns.test.ts
- cypress/e2e/views/common.view.ts
- cypress/e2e/views/taskmanager.view.ts
- cypress/utils/utils.ts
Resolves: https://issues.redhat.com/browse/MTA-3379
Jenkins run: https://jenkins-csb-migrationqe-main.dno.corp.redhat.com/view/Konveyor/job/mta/job/tackle-ui-tests-pr-tester/view/change-requests/job/PR-1306/3/console
> [RFR] Task manager - table column management validation

- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/models/migration/task-manager/task-manager.ts
- cypress/e2e/tests/migration/applicationinventory/applications/application_popover.test.ts
- cypress/e2e/tests/migration/task-manager/task_manager.test.ts
- cypress/utils/utils.ts
Resolves: https://issues.redhat.com/browse/MTA-4429
Jenkins run: https://jenkins-csb-migrationqe-main.dno.corp.redhat.com/view/Konveyor/job/mta/job/tackle-ui-tests-pr-tester/view/change-requests/job/PR-1305/2/console
> [RFR] Validate task links from application popover

- cypress/e2e/tests/migration/applicationinventory/analysis/binary_analysis.test.ts
- cypress/fixtures/analysis.json
Resolves https://issues.redhat.com/browse/MTA-4476
> [RFR]Update binary analysis test case

- cypress/utils/utils.ts
Resolves [JF ](https://issues.redhat.com/browse/MTA-4469)
> [RFR] Update validatePageTitle() fn

- cypress/e2e/tests/migration/task-manager/sorting.filter.pagination.test.ts
- cypress/utils/utils.ts
- Use `validateTextPresence` instead of `notExists`
- Ensuring the 'sort by status' test is executed last
Jenkins run: https://jenkins-csb-migrationqe-main.dno.corp.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/4332/console
> [RFR][JF] Fix task-manager tests

- cypress/e2e/tests/migration/applicationinventory/analysis/upload_binary_analysis.test.ts
- cypress/fixtures/analysis.json
Fixes [MTA-4464](https://issues.redhat.com/browse/MTA-4464)
[Jenkins run](https://jenkins-csb-migrationqe-main.dno.corp.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/4350/console)
> [RFR][JF] FIx upload binary test case

- cypress/e2e/tests/migration/applicationinventory/analysis/affected_files.test.ts
- cypress/fixtures/analysis.json
Automates https://issues.redhat.com/browse/MTA-4414 
Bug https://issues.redhat.com/browse/MTA-4026
[jenkins Run](https://jenkins-csb-migrationqe-main.dno.corp.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/4354)
> [RFR][TA] Automate cool store bug_MTA_4026

- cypress/e2e/tests/migration/applicationinventory/analysis/affected_files.test.ts
- cypress/fixtures/analysis.json
Automates https://issues.redhat.com/browse/MTA-4415
Bug https://issues.redhat.com/browse/MTA-4027
> [RFR][TA] Automate cool store bug_MTA_4027

- cypress/e2e/tests/custom-metrics/analysis_metrics.test.ts
Resolves: https://issues.redhat.com/browse/MTA-4565
> [RFR] Use deleteApplicationTableRows instead of deleteByList

- .github/workflows/k8s-ci.yml
- .github/workflows/k8s-cron.yml
This PR fixes and optimizes jobs for : 
1. UI TIER0 Nightly
2. UI Test Tier1,2,3 jobs.
> Fix nightly ui tier0 and Test UI tier1,2,3 jobs.

- cypress/e2e/models/migration/archetypes/archetype.ts
- cypress/e2e/models/migration/controls/tags.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/review/filter.test.ts
- cypress/e2e/views/applicationinventory.view.ts
- cypress/utils/utils.ts
Resolves the following tier0 failure                                                                                                                                           [JF](https://issues.redhat.com/browse/MTA-4573)
> [RFR] Update Tag.edit()

- cypress/e2e/models/migration/controls/jobfunctions.ts
Resolves the following Jenkins failures
[MTA-4572](https://issues.redhat.com/browse/MTA-4572)
[MTA-4575](https://issues.redhat.com/browse/MTA-4575)
[MTA-4568](https://issues.redhat.com/browse/MTA-4568)
[MTA-4564](https://issues.redhat.com/browse/MTA-4564)
[MTA-4562](https://issues.redhat.com/browse/MTA-4562)
> [RFR] [JF] Update jobfunctions methods

- cypress/e2e/models/migration/controls/tagcategory.ts
Resolves [JF ](https://issues.redhat.com/browse/MTA-4574)
> [RFR] [JF] Update TagCategory.edit()

- .github/workflows/k8s-ci.yml
> Disable workflow tier1,2,3

- konveyor-tier1-nightly.jenkinsfile
> Fix for cypress going through non test files

- cypress/e2e/tests/migration/controls/tags/tag/crud.test.ts
- cypress/e2e/tests/migration/migration-waves/crud.test.ts
> Move tag and migration wave crud tests to tier2

- cypress/e2e/models/migration/archetypes/archetype.ts
- cypress/e2e/models/migration/controls/tags.ts
- cypress/e2e/tests/migration/applicationinventory/assessment/review/filter.test.ts
- cypress/utils/utils.ts
> [RFR] Revert "PR 1326 Update Tag.edit()"

- cypress/e2e/models/migration/controls/tagcategory.ts
> Revert "PR 1328 Update TagCategory.edit()"

- cypress/e2e/models/migration/controls/jobfunctions.ts
> Revert "PR 1327 Update jobfunctions methods"

- cypress/e2e/tests/migration/reports-tab/filter.test.ts
> [RFR] :ghost: Mark reports tab filter bug

- .github/workflows/ui-tier0.yaml
> Add tier0 pr tester workflow

- cypress/e2e/tests/migration/reports-tab/filter.test.ts
> :ghost: [RFR] Backport of 95e525c0fe6daa5c53ee034d5911df25ca82c50f

- cypress/e2e/tests/migration/task-manager/sorting.filter.pagination.test.ts
> [RFR] Splitted big filtering test into smaller parts

- .github/workflows/prettier.yaml
- cypress/e2e/views/login.view.ts
- cypress/utils/utils.ts
fixed the login failure, added a function to fill the `Update Account Information` page
**[Jenkins Run](https://jenkins-csb-migrationqe-main.dno.corp.redhat.com/job/mta/job/tackle-ui-tests-on-ocp/799/console)**
> [RFR] fixed the login failure, added a function to fill the `Update Account Information` page

- .github/workflows/prettier.yaml
- cypress/e2e/models/migration/applicationinventory/analysis.ts
- cypress/e2e/tests/upgrade/after_upgrade.test.ts
> [release-0.6] Upgrade : Download static analysis report after re-analysis

- cypress/e2e/tests/migration/applicationinventory/analysis/static_report.test.ts
> [RFR] [release-0.6] Update static report test

- cypress/e2e/tests/migration/reports-tab/filter.test.ts
> [RFR]  :ghost: Remove bug number

- cypress/e2e/tests/migration/reports-tab/filter.test.ts
> [RFR] :ghost: Backport of remove bug number

- cypress/e2e/models/migration/controls/tagcategory.ts
Resolves [JF](https://issues.redhat.com/browse/MTA-4766)
> [RFR] [release-0.7] Update TagCategory.delete()

- cypress/e2e/models/migration/controls/tagcategory.ts
- cypress/e2e/tests/upgrade/after_upgrade.test.ts
> [RFR] [release-0.7] Upgrade: Update pod list

- cypress/e2e/models/keycloak/users/user.ts
- cypress/e2e/views/rbac.view.ts
> [RFR] Backported RBAC fixes from main

- cypress/e2e/tests/migration/applicationinventory/applications/manage_credentials_many_apps.test.ts
> [RFR] Fixed Manage credentials source analysis

- cypress/e2e/models/migration/applicationinventory/analysis.ts
- cypress/e2e/tests/upgrade/after_upgrade.test.ts
> [release-0.7] [RFR] Upgrade : Download static analysis report after re-analysis

- cypress/e2e/tests/migration/dynamic-report/dependencies/pagination.test.ts
- cypress/e2e/tests/migration/dynamic-report/dependencies/sort.test.ts
> [RFR] Added bug marker for failing tests

- cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
- cypress/fixtures/analysis.json
modified:   cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
> [RFR][JF] Fix source Analysis test cases

- cypress/e2e/tests/migration/migration-waves/export_to_jira_datacenter.test.ts
A small refactor over the structure of the export_to_jira_datacenter test to reduce the number of requests made to Jira.
> [RFR] Refactor export to jira datacenter suite

- cypress/e2e/tests/migration/applicationinventory/analysis/custom-rules.test.ts
Resolves https://issues.redhat.com/browse/MTA-4761 
[Jenkins Run](https://jenkins-csb-migrationqe-main.dno.corp.redhat.com/job/mta/job/mta-ui-tests-runner/4743/)
> [RFR][JF] Add bug number to test cases

- cypress/e2e/tests/migration/applicationinventory/applications/bulk_deletion_applications.test.ts
> [RFR] Bulk deletion - Select all: Mark bug

- cypress/e2e/tests/migration/migration-waves/export_to_jira_datacenter.test.ts
> [RFR] 0.7 🌱 Backport of Refactor export to jira datacenter suite

- cypress/e2e/tests/migration/migration-waves/export_to_jira_datacenter.test.ts
> [RFR] [Backport release-0.6] :seedling: Refactor export to jira datacenter suite (#1391)

- cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
[Jenkins Run](https://jenkins-csb-migrationqe-main.dno.corp.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/4736/console)
Resolves https://issues.redhat.com/browse/MTA-4876
>  [RFR][JF] Remove bug number from source analysis test case 

- cypress/e2e/tests/migration/dynamic-report/dependencies/pagination.test.ts
- cypress/e2e/tests/migration/dynamic-report/dependencies/sort.test.ts
> [RFR] Corrected bug marker for failing tests

- cypress/e2e/tests/migration/applicationinventory/analysis/tag_filter.test.ts
> [main] Update bug marker for filter tests for analysis automated tags

- cypress/e2e/tests/migration/applicationinventory/analysis/custom-rules.test.ts
- cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
[Jenkins Run](https://jenkins-csb-migrationqe-main.dno.corp.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/4760)
Fixes https://issues.redhat.com/browse/MTA-4893
> [RFR][JF] Add Correct bug number to test case

- cypress/e2e/tests/migration/applicationinventory/analysis/tag_filter.test.ts
> [RFR] [release-0.7] Update bug marker for  auto tag generation test

- cypress/e2e/tests/upgrade/after_upgrade.test.ts
- cypress/e2e/tests/upgrade/create_upgrade_data.test.ts
> [main] Upgrade : Download static analysis report after re-analysis

- cypress/e2e/models/migration/applicationinventory/application.ts
Resolves [JF](https://issues.redhat.com/browse/MTA-4926)
> Update selector for application edit button

- cypress/e2e/tests/upgrade/after_upgrade.test.ts
> [release-0.7] Update pod list after upgrade

- cypress/e2e/tests/administration/repository/subversion.test.ts
- cypress/fixtures/application.json
Automates https://issues.redhat.com/browse/MTA-4431 
[Jenkins Run](https://jenkins-csb-migrationqe-main.dno.corp.redhat.com/view/MTA/job/mta/job/mta-ui-tests-runner/4795)
> [RFR][TA] Automates a bug with SVN repo when filenames have special characters

- cypress/e2e/tests/migration/dynamic-report/dependencies/filter.test.ts
> [RFR] Changed bug marker to a relevant one

- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/views/applicationinventory.view.ts
Resolves [JF](https://issues.redhat.com/browse/MTA-4928)
> [release 0.7] Update selector for edit button for applications

- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/views/applicationinventory.view.ts
> [RFR] Add edit button for app inventory page

- cypress/e2e/models/keycloak/users/user.ts
- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/tests/rbac/architect.test.ts
- cypress/e2e/tests/rbac/migrator.test.ts
- cypress/e2e/tests/rbac/review-assessment.test.ts
> [RFR] Fixed Architect RBAC operations test

- cypress/e2e/models/migration/controls/tagcategory.ts
- cypress/e2e/tests/migration/controls/tags/tagcategory/create.test.ts
- cypress/e2e/tests/migration/controls/tags/tagcategory/crud.test.ts
- cypress/e2e/tests/migration/controls/tags/tagcategory/filter.test.ts
- cypress/e2e/tests/migration/controls/tags/tagcategory/sort.test.ts
As `Rank` is removed from tag category functionality since 7.3.0 - adjusting automation to remove it there as well
> [RFR] Removed all related to ranks in tagcategory

- cypress/e2e/models/migration/applicationinventory/assessment.ts
- cypress/e2e/tests/rbac/upload_binary_analysis_architect.test.ts
- cypress/e2e/tests/rbac/upload_binary_analysis_migrator.test.ts
Had to force a timeout as page doesn't always finish rendering in time.
Removed `logout()` usage for upload binary tests for architect and migrator
> [RFR] Final fix for Assessment and review as architect test

- cypress/e2e/tests/migration/applicationinventory/analysis/tag_filter.test.ts
> [RFR] Analysis tag filter : Remove rank during TagCategory object initialization

- cypress/e2e/tests/migration/archetypes/questionnaire_features.test.ts
> Add bug marker for conditional questional test

- cypress/e2e/tests/upgrade/create_upgrade_data.test.ts
- cypress/utils/utils.ts
> [release-0.7] Update Tag category creation for pre upgrade test

- cypress/e2e/models/migration/archetypes/archetype.ts
- cypress/e2e/tests/migration/archetypes/miscellaneous.test.ts
Fixed a few tests that were failing
> Update archetype tests to verify assessment status

- cypress/e2e/models/migration/applicationinventory/analysis.ts
Backport of https://github.com/konveyor/tackle-ui-tests/pull/1447
> :seedling: [backport release-0.7] [RFR] Adapt download report test

- cypress/e2e/models/administration/custom-migration-targets/custom-migration-target.ts
- cypress/e2e/models/migration/applicationinventory/analysis.ts
- cypress/e2e/tests/administration/custom-migration-targets/crud.test.ts
Resolves [MTA-5048](https://issues.redhat.com/browse/MTA-5048)
> :bug: [RFR] Fix custom migration target tests

- cypress/e2e/tests/migration/applicationinventory/analysis/static_report.test.ts
- cypress/support/e2e.ts
- cypress/utils/utils.ts
Main PR of https://github.com/konveyor/tackle-ui-tests/pull/1433
> :seedling: [RFR] Fix static report main

- cypress/e2e/models/migration/applicationinventory/analysis.ts
Resolves [MTA-5027](https://issues.redhat.com/browse/MTA-5027)
Now the download buttons take a bit longer to enable.
> :seedling: [RFR] Adapt download report test

- cypress/e2e/tests/migration/dynamic-report/issues/filter.sorting.pagination.test.ts
Enabled back Issues tests, cause they were disabled due to CI issue
> [RFR] Enabling back Issues tests

- cypress/e2e/tests/rbac/architect.test.ts
- cypress/e2e/tests/rbac/migrator.test.ts
Combined tests into one because of unstable DOM issue .
> [RFR] RBAC tests DOM issue

- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/tests/migration/applicationinventory/applications/crud.test.ts
- cypress/e2e/views/applicationinventory.view.ts
Resolves 
1) [JF MTA-5055](https://issues.redhat.com/browse/MTA-5055l)
2) [JF MTA-5058](https://issues.redhat.com/browse/MTA-5058)
> Update selector for edit button on App Inventory page

- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/views/applicationinventory.view.ts
> [main] Update selector for edit button on App Inventory page

- cypress/e2e/tests/migration/applicationinventory/assessment/questionnaire_features.test.ts
> Add bug ID to app questionnaire test

- cypress/e2e/tests/migration/task-manager/sorting.filter.pagination.test.ts
Filtering, sorting and pagination in Task Manager Page
✓ Filtering tasks (66208ms)
✓ Sorting tasks (28993ms)
✓ Pagination validation
> [RFR] sorting/ Filtering tests in task manager

- cypress/e2e/models/administration/custom-migration-targets/custom-migration-target.ts
- cypress/e2e/tests/administration/custom-migration-targets/crud.test.ts
- cypress/e2e/tests/administration/custom-migration-targets/trigger_validation.test.ts
Backport of https://github.com/konveyor/tackle-ui-tests/pull/1464
Extra checks for [MTA-5060](https://issues.redhat.com/browse/MTA-5060)
Run [4929](https://jenkins-csb-migrationqe-main.dno.corp.redhat.com/job/mta/job/mta-ui-tests-runner/4929/console)
> 🌱 [Backport release-0.7] [RFR] Add timeouts to custom migration targets tests 

- cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts
> Add bug to auto tag test

- .github/workflows/global-ci.yaml
> Enable installing proper konveyor version for global ci

- cypress/e2e/tests/migration/applicationinventory/assessment/miscellaneous.test.ts
- cypress/e2e/tests/migration/archetypes/miscellaneous.test.ts
> Application assessment : Remove redundant code 

- cypress/e2e/tests/upgrade/create_upgrade_data.test.ts
> [main] Pre upgrade: Remove rank during TagCategory object initialization

- cypress/e2e/tests/migration/archetypes/miscellaneous.test.ts
> [main] Update archetype tests to verify assessment status

- cypress/e2e/tests/migration/dynamic-report/dependencies/filter.test.ts
- cypress/e2e/tests/migration/dynamic-report/dependencies/sort.test.ts
> [RFR] Fixed bug number for dependency tests

- cypress/e2e/tests/rbac/upload_binary_analysis_migrator.test.ts
Fixed upload binary as migrator test, ticket https://issues.redhat.com/browse/MTA-5161
Successfull Jenkins run: https://jenkins-csb-migrationqe-main.dno.corp.redhat.com/job/mta/job/mta-ui-tests-runner/4990/console
> [RFR] Fixed upload binary as migrator test

- cypress/utils/utils.ts
Resolves [JF](https://issues.redhat.com/browse/MTA-5142)
> [release-0.7] Update exists() fn

- cypress/e2e/tests/migration/reports-tab/archetype_association.test.ts
> [release-0.7] Fix reports tab test

- cypress/e2e/tests/migration/applicationinventory/manageimports/csv.test.ts
Fixes [JF](https://issues.redhat.com/browse/MTA-5042)
> [release-0.7] Fix Download Import CSV test

- cypress/e2e/tests/migration/applicationinventory/applications/manage_credentials_many_apps.test.ts
- cypress/fixtures/analysis.json
> [RFR] Manage source credential fix

- cypress/e2e/tests/migration/applicationinventory/analysis/gradle_analysis.test.ts
Relates to [MTA-5172](https://issues.redhat.com/browse/MTA-5172)
> :seedling: [backport release-0.7] [RFR] rename gradle test and add bug number

- cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
- cypress/utils/utils.ts
> [RFR] Assessment as architect test

- cypress/e2e/tests/migration/applicationinventory/applications/interlinked.test.ts
Resolves [JF](https://issues.redhat.com/browse/MTA-5189)
> [release-0.7] Fix Application interlinked test

- cypress/e2e/tests/migration/archetypes/crud.test.ts
> [release-0.7] Fix archetype test

- cypress/fixtures/analysis.json
Solves [MTA-5200](https://issues.redhat.com/browse/MTA-5200)
> :seedling: [RFR] Fix application tag filter test

- cypress/e2e/tests/migration/applicationinventory/analysis/affected_files.test.ts
- cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis.test.ts
- cypress/fixtures/analysis.json
> [RFR] Combined two daytrader tests

- cypress/e2e/tests/administration/repository/maven.test.ts
- cypress/utils/utils.ts
Solves [MTA-5158](https://issues.redhat.com/browse/MTA-5158)
The session needed to be cleared after rerolling the pods
> :bug: [RFR] Fix maven test

- cypress/e2e/tests/administration/repository/maven.test.ts
- cypress/utils/utils.ts
> :bug: [RFR] [backport release-0.7] Backport fix maven test

- cypress/utils/utils.ts
Port [PR ](https://github.com/konveyor/tackle-ui-tests/pull/1482) to main.
> [main] Remove updateAccountInformation() fn

- cypress/e2e/models/keycloak/users/user.ts
> [RFR] Fixed flow for RBAC user creation

- cypress/e2e/tests/custom-metrics/analysis_metrics.test.ts
Solves [MTA-5217](https://issues.redhat.com/browse/MTA-5217)
> :bug: [RFR] Fix metrics test

- cypress/e2e/tests/migration/task-manager/task_manager.test.ts
- cypress/e2e/views/common.view.ts
> [release 0.7] Task Manager: Test View All Tasks link from within the task drawer

- cypress/e2e/tests/migration/task-manager/miscellaneous.test.ts
- cypress/e2e/tests/migration/task-manager/task_manager.test.ts
- cypress/e2e/views/common.view.ts
> [main] Task Manager: Test View All Tasks link from within the task drawer

- cypress/e2e/tests/migration/migration-waves/sort.test.ts
Backport of #1526 
Solves [MTA-5233](https://issues.redhat.com/browse/MTA-5322)
Jenkins run [#5223](https://jenkins-csb-migrationqe-main.dno.corp.redhat.com/job/mta/job/mta-ui-tests-runner/5223/)
---
> [backport release-0.7] :bug: [RFR] Fix waves sort test

- cypress/e2e/tests/migration/migration-waves/sort.test.ts
Solves [MTA-5233](https://issues.redhat.com/browse/MTA-5322)
Jenkins run [#5223](https://jenkins-csb-migrationqe-main.dno.corp.redhat.com/job/mta/job/mta-ui-tests-runner/5223/)
---
> :bug: [RFR] Fix waves sort test

- cypress/e2e/models/migration/applicationinventory/analysis.ts
- cypress/e2e/tests/upgrade/after_upgrade.test.ts
- cypress/e2e/tests/upgrade/create_upgrade_data.test.ts
> [release-0.6] Add Analysis.waitStatusChange() method

- cypress/e2e/views/tags.view.ts
> [release-0.7] Remove unused selectors related to tag ranks

- cypress/e2e/tests/upgrade/after_upgrade.test.ts
- cypress/e2e/tests/upgrade/create_upgrade_data.test.ts
> [release-0.7] Upgrade: Increase timeout for Analysis completion

- cypress/e2e/tests/migration/applicationinventory/applications/filter.test.ts
Duplicate of https://github.com/konveyor/tackle-ui-tests/pull/1478
> [release-0.7] filter by analysis

- .github/workflows/prettier.yaml
- cypress/e2e/tests/migration/task-manager/application_tasks_tab.test.ts
- Updated prettier.yaml
- Automate TC MTA-624
Duplicate of [1518](https://github.com/konveyor/tackle-ui-tests/pull/1518) for release-0.7 branch
> [release-0.7] Ensure Tasks tab lists correct task kinds

- cypress/e2e/tests/migration/archetypes/miscellaneous.test.ts
Resolves [JF](https://issues.redhat.com/browse/MTA-5348)
> [release-0.7] Archetypes: Fix associated app link test

- cypress/e2e/tests/migration/dynamic-report/issues/filter.sorting.pagination.test.ts
Backport of https://github.com/konveyor/tackle-ui-tests/pull/1540
Solves [MTA-5315](https://issues.redhat.com/browse/MTA-5315)
> 🌱 [backport: release-0.7] [RFR] Remove leftover data from issues test

- cypress/e2e/tests/migration/applicationinventory/assessment/archetype_association.test.ts
Corresponding [7.3 PR ](https://github.com/konveyor/tackle-ui-tests/pull/1534)
> [main] Update view archetype test

- cypress/e2e/tests/migration/dynamic-report/dependencies/sort.test.ts
> [RFR] Fixed bug marker for release-0.6

- cypress/e2e/models/migration/task-manager/task-manager.ts
- cypress/e2e/tests/migration/task-manager/task_details.test.ts
Resolves: https://issues.redhat.com/browse/MTA-5530
Jenkins run: https://jenkins-csb-migrationqe-main.dno.corp.redhat.com/job/mta/job/tackle-ui-tests-pr-tester/job/PR-1551/2/console
> [RFR] Fix migration/task-manager/task_details.test.ts

- cypress/e2e/tests/migration/applicationinventory/analysis/source_analysis_without_creds.test.ts
> :seedling: [RFR] Mark source creds bug

- cypress/e2e/models/migration/applicationinventory/application.ts
- cypress/e2e/tests/migration/applicationinventory/analysis/tag_filter.test.ts
- cypress/fixtures/analysis.json
Porting [PR 1548 ](https://github.com/konveyor/tackle-ui-tests/pull/1548/) to release-0.7
> [release-0.7] Update tagAndCategoryExists() fn

- cypress/e2e/tests/migration/applicationinventory/analysis/tag_filter.test.ts
> [RFR] Analysis Tag filter test - Remove commented lines

- cypress/e2e/tests/rbac/architect.test.ts
- cypress/e2e/tests/rbac/migrator.test.ts
> Patch rhbk tag to existing rhsso tests
